-- Existing synthetic canonical page and rollback-only SEO records; no users/providers.
begin;
set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';page public.project_website_pages%rowtype;version uuid:='99999999-9999-4999-8999-999999997141';tracked uuid:='99999999-9999-4999-8999-999999997150';keyword uuid:='99999999-9999-4999-8999-999999997260';j jsonb;input jsonb;review jsonb;saved jsonb;binding uuid;site text;begin
 select * into page from public.project_website_pages where organization_id=org and project_id=project and page_key='page:1';if not found then raise exception 'Verified AD1 fixture absent';end if;
 insert into public.project_website_page_seo_links(organization_id,project_id,brand_id,page_id,link_number,tracked_page_id,architecture_artifact_id,architecture_version_id,architecture_approval_id,architecture_checksum,created_by)
 select org,project,page.brand_id,page.id,coalesce((select max(link_number) from public.project_website_page_seo_links where page_id=page.id),0)+1,tracked,page.architecture_artifact_id,version,page.initial_approval_id,v.content_checksum,auth.uid() from public.artifact_versions v where v.id=version;
 insert into public.tracked_page_audits(id,organization_id,tracked_page_id,audit_date,core_web_vitals_mobile,schema_valid,issues,notes,source_type,created_by,created_at) values('99999999-9999-4999-8999-999999997261',org,tracked,'2000-01-01',0,false,array['Synthetic manual finding'],'Rollback-only manual evidence','manual',auth.uid(),'2000-01-01T09:00:00Z');
 insert into public.tracked_page_audits(id,organization_id,tracked_page_id,audit_date,indexed,index_status,core_web_vitals_mobile,schema_valid,source_type,source_connection_id,created_by,created_at) values('99999999-9999-4999-8999-999999997262',org,tracked,'2000-01-02',true,'indexed',95,true,'search_console','99999999-9999-4999-8999-999999997232',auth.uid(),'2000-01-02T09:00:00Z');
 insert into public.tracked_keywords(id,organization_id,brand_id,tracked_page_id,keyword,target_rank_tier,created_by) values(keyword,org,page.brand_id,tracked,'alpha phrase','top_10',auth.uid());
 insert into public.keyword_rank_snapshots(id,organization_id,tracked_keyword_id,snapshot_date,position,search_console_clicks,search_console_impressions,fetched_at) values('99999999-9999-4999-8999-999999997263',org,keyword,'2000-01-02',7.5,0,null,'2000-01-03T09:00:00Z');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'page_audits',null,'',null,null,0,1);
 perform pg_temp.check_true(j#>>'{context,page_key}'='page:1' and j#>>'{context,initial_path}'='home' and j#>>'{context,source_state}'='available' and jsonb_array_length(j->'items')=1,'Bounded SEO context binds exact original page/root/version/current explicit bridge');
 perform pg_temp.check_true(j#>>'{context,recheck_required}'='true' and j#>'{context,recheck_reasons}' ? 'legacy_observation_not_version_bound','Legacy observation cannot claim exact current-version check acceptance');
 perform pg_temp.check_true(j#>'{context,recheck_reasons}' ? 'implementation_changed_after_observation','Later implementation changes require a recheck without causal claims');
 perform pg_temp.check_true(j#>>'{context,provider_request_made}'='false' and j->>'provider_period_known'='false','Read performs no provider request and does not infer legacy provider period');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'page_audits',null,'Rollback-only');
 perform pg_temp.check_true(j->>'matching'='1' and j#>>'{items,0,core_web_vitals_mobile}'='0' and j#>'{items,0,indexed}'='null'::jsonb and j#>>'{items,0,schema_valid}'='false','Manual zero/false/missing values remain distinct');
 perform pg_temp.check_true(j#>>'{items,0,version_binding}'='unknown' and j#>'{items,0,reporting_time_zone}'='null'::jsonb,'Manual evidence remains explicitly unbound and timezone unknown');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'page_audits',null,'','2000-01-02','2000-01-02');
 perform pg_temp.check_true(j#>'{items,0,core_web_vitals_mobile}'='null'::jsonb and j#>'{items,0,indexed}'='null'::jsonb and j#>'{items,0,issues}'='null'::jsonb,'Provider audit values withheld when historical resource provenance is unknown');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'planned_targets',null,'alpha');
 perform pg_temp.check_true(j#>>'{items,0,record_kind}'='planned_target' and j#>>'{items,0,target_rank_tier}'='top_10' and not (j#>'{items,0}') ? 'position','Planned targets remain separate from query observation metrics');
 perform pg_temp.check_true(j#>'{items,0,exact_source_version_id}'='null'::jsonb,'Legacy artifact-root link never fabricates an approved exact source version');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'query_observations',keyword,'alpha','2000-01-01','2000-01-03');
 perform pg_temp.check_true(j#>>'{items,0,record_kind}'='query_observation' and j#>>'{items,0,query}'='alpha phrase' and not (j#>'{items,0}') ? 'target_rank_tier','Observed query metadata does not become a planned target');
 perform pg_temp.check_true(j#>'{items,0,position}'='null'::jsonb and j#>'{items,0,search_console_clicks}'='null'::jsonb and j#>>'{items,0,metrics_withheld_reason}'='legacy_resource_provenance_unknown','Unknown query resource context stays unavailable rather than fabricated zero');
 perform pg_temp.check_true(j#>'{items,0,period_start}'='null'::jsonb and j#>'{items,0,device}'='null'::jsonb and j#>'{items,0,data_through}'='null'::jsonb,'Collection date does not infer provider period/device/data-through');
 perform pg_temp.check_true((select position=7.5 and search_console_clicks=0 and search_console_impressions is null from public.keyword_rank_snapshots where id='99999999-9999-4999-8999-999999997263'),'Stored original provider metrics retained without mutation or blind copying');
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'planned_targets',null,'no-such-target');
 perform pg_temp.check_true(j->>'matching'='0' and (j->>'total')::int>=1 and j->'items'='[]'::jsonb,'Empty filtered target page preserves whole totals');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,%L)',org,project,page.id,version,'query_observations','99999999-9999-4999-8999-999999997299'),'42501','Foreign/missing query keyword rejected');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L)',org,project,page.id,'99999999-9999-4999-8999-999999997147','page_audits'),'42501','Different architecture root cannot borrow this page bridge');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L)',org,project,'99999999-9999-4999-8999-999999997299',version,'page_audits'),'42501','Missing or foreign project page rejected');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L)',org,project,page.id,version,'combined'),'22023','Combined target/query category rejected');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,null,%L,null,null,0,51)',org,project,page.id,version,'page_audits',''),'22023','Unbounded history limit rejected');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,null,%L,%L,%L)',org,project,page.id,version,'page_audits','','2000-01-01','2001-01-01'),'22023','Unbounded collection date history rejected');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,null,%L,%L,%L)',org,project,page.id,version,'planned_targets','','2000-01-01','2000-01-02'),'22023','Planned targets cannot pretend to be dated observations');
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,null,%L,null,null,0,25,%L)',org,project,page.id,version,'page_audits','','99999999-9999-4999-8999-999999997299'),'42501','Missing/foreign GSC binding rejected before provider data exposure');
 select public_config->>'site_url' into site from public.integration_connections where id='99999999-9999-4999-8999-999999997232' and organization_id=org;
 select id into binding from public.project_reporting_bindings where organization_id=org and project_id=project and connection_id='99999999-9999-4999-8999-999999997232' and department_id='marketing';
 if binding is null then
 input:=jsonb_build_object('binding_id',null,'expected_revision',0,'engagement_id',page.engagement_id,'department_id','marketing','connection_id','99999999-9999-4999-8999-999999997232','resource_kind','gsc_site','resource_key',site,'permitted_operations',jsonb_build_array('reporting_read'),'state','enabled');
 review:=public.preview_project_reporting_binding(org,project,input);saved:=public.confirm_project_reporting_binding(org,project,input,review->>'review_sha256','99999999-9999-4999-8999-999999997264');binding:=(saved->>'binding_id')::uuid;
 end if;
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'query_observations',null,'',null,null,0,25,binding);
 perform pg_temp.check_true(j#>>'{context,reporting_binding_id}'=binding::text and j#>>'{context,provider_observations_ready}'='false' and j#>>'{context,reporting_reason}' is not null,'Explicit current GSC binding checked without retroactive provider provenance');
 delete from public.integration_connection_engagements where organization_id=org and connection_id='99999999-9999-4999-8999-999999997232' and engagement_id=page.engagement_id and department_id='marketing';
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'query_observations',null,'',null,null,0,25,binding);
 perform pg_temp.check_true(j#>>'{context,reporting_reason}'='reporting_binding_context_unavailable' and j#>'{items,0,position}'='null'::jsonb,'Current mapping revocation rechecked and historical provider values remain withheld');
 insert into public.tracked_page_audits(organization_id,tracked_page_id,audit_date,source_type,notes,created_by) values(org,tracked,'2000-01-03','manual',repeat('x',140000),auth.uid());
 perform pg_temp.expect_error(format('select public.list_project_website_page_seo_observations(%L,%L,%L,%L,%L,null,%L,null,null,0,1)',org,project,page.id,version,'page_audits',''),'22023','Whole bounded response rejects oversized legacy evidence without silent truncation');
 update public.engagements set status='on_hold' where id=page.engagement_id;
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'planned_targets');
 perform pg_temp.check_true(j#>>'{context,source_state}'='approved_source_unavailable' and j#>>'{items,0,record_kind}'='planned_target','Withdrawn current source remains explicit while safe historical metadata retained');
 update public.projects set archived_at=now() where id=project;
 j:=public.list_project_website_page_seo_observations(org,project,page.id,version,'page_audits',null,'','2000-01-01','2000-01-02');
 perform pg_temp.check_true(j#>>'{context,source_state}'='archived','Archived project retains scoped historical reads');
end $$;
set local role authenticated;
select pg_temp.check_true(public.list_project_website_page_seo_observations('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','2b5d24af-3f22-4792-bc0d-e2afbe7d00c0','99999999-9999-4999-8999-999999997141','planned_targets')->>'category'='planned_targets','Actual authenticated role reads bounded exact page SEO API');
select pg_temp.check_true(not has_function_privilege('authenticated','private.website_seo_context(uuid,uuid,uuid,uuid,uuid)','execute'),'Authenticated cannot directly invoke private SEO scope helper');
reset role;
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999997299',true);
select pg_temp.expect_error('select public.list_project_website_page_seo_observations(''99999999-9999-4999-8999-999999999901'',''99999999-9999-4999-8999-999999999974'',''2b5d24af-3f22-4792-bc0d-e2afbe7d00c0'',''99999999-9999-4999-8999-999999997141'',''page_audits'')','42501','Unknown actor cannot read new project SEO views');
select pg_temp.check_true(not has_function_privilege('anon','public.list_project_website_page_seo_observations(uuid,uuid,uuid,uuid,text,uuid,text,date,date,integer,integer,uuid)','execute') and not has_function_privilege('service_role','public.list_project_website_page_seo_observations(uuid,uuid,uuid,uuid,text,uuid,text,date,date,integer,integer,uuid)','execute'),'Anon/service-role cannot bypass scoped project SEO reads');
rollback;
