-- Named synthetic existing-actor fixtures in one rollback; no users/providers.
begin;
set local lock_timeout='5s';set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
-- Local clone legacy activity default is restored exactly by ROLLBACK, never a production workaround.
alter table public.activity_events alter column organization_id set default '99999999-9999-4999-8999-999999999901'::uuid;
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
insert into public.workstreams(id,organization_id,project_id,department_id,name,status) values('99999999-9999-4999-8999-999999997501','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','marketing','Synthetic reviewed campaign planning','active');
insert into public.deliverables(id,organization_id,project_id,workstream_id,title,description,deliverable_type,status,visibility,owner_id,created_by,due_date) values('99999999-9999-4999-8999-999999997500','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999997501','Synthetic campaign delivery','Existing governed deliverable fixture','article','in_production','internal_only','99999999-9999-4999-8999-999999999902','99999999-9999-4999-8999-999999999902','2026-10-10');
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';eng uuid:='99999999-9999-4999-8999-999999999975';service uuid:='99999999-9999-4999-8999-999999997171';campaign uuid:='99999999-9999-4999-8999-999999997172';deliverable uuid:='99999999-9999-4999-8999-999999997500';actor uuid:='99999999-9999-4999-8999-999999999902';request uuid:='99999999-9999-4999-8999-999999997510';plan uuid:='99999999-9999-4999-8999-999999997173';input jsonb;review jsonb;saved jsonb;saved2 jsonb;q text;oldrole text;olddept text;versions bigint;commands bigint;work bigint;tasks bigint;users bigint;begin
 input:=jsonb_build_object('title','Synthetic reviewed delivery plan','brief','Preserve exact campaign strategy and governed delivery history','format','Article','content_pillar','Product education','topic','Launch adoption','due_date','2026-10-15','contributor_ids',jsonb_build_array(actor),'change_summary','Reviewed planning fields','source_version_id',null,'client_approval_required',true);
 select count(*) into versions from public.deliverable_versions;select count(*) into commands from public.project_campaign_deliverable_plan_commands;select count(*) into tasks from public.tasks;select count(*) into work from public.work_items;select count(*) into users from auth.users;
 review:=public.preview_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,null,input);
 perform pg_temp.check_true(review->>'zero_write'='true' and (select count(*) from public.deliverable_versions)=versions and (select count(*) from public.project_campaign_deliverable_plan_commands)=commands,'Exact campaign deliverable review makes zero writes');
 perform pg_temp.check_true(review#>>'{snapshot,context,service,id}'=service::text and review#>>'{snapshot,plan,id}'=plan::text and review#>>'{snapshot,contributors,0,user_id}'=actor::text,'Existing service/plan/contributor identities are retained');
 perform pg_temp.check_true(review#>>'{snapshot,approval_state}'='unapproved_new_version' and review#>>'{snapshot,ready_to_publish}'='false','Contributor/brief metadata cannot certify approval or publication');
 q:=format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,null,',org,project,eng,service,campaign,plan,deliverable);
 perform pg_temp.expect_error(q||quote_literal(input||'{"extra":true}')||'::jsonb)','22023','Unsupported metadata cannot be silently saved');
 perform pg_temp.expect_error(q||quote_literal(input||'{"brief":42}')||'::jsonb)','22023','Brief text cannot be coerced');
 perform pg_temp.expect_error(q||quote_literal(input||jsonb_build_object('brief',repeat('x',12001)))||'::jsonb)','22023','Oversized brief cannot be truncated');
 perform pg_temp.expect_error(q||quote_literal(input||'{"due_date":"2026-02-30"}')||'::jsonb)','22008','Invalid planned deadline rejected');
 perform pg_temp.expect_error(q||quote_literal(input||'{"client_approval_required":"true"}')||'::jsonb)','22023','Approval requirement remains a real boolean');
 perform pg_temp.expect_error(q||quote_literal(input||jsonb_build_object('contributor_ids',jsonb_build_array(actor,actor)))||'::jsonb)','22023','Repeated contributors rejected');
 perform pg_temp.expect_error(q||quote_literal(input||'{"contributor_ids":["99999999-9999-4999-8999-999999997599"]}')||'::jsonb)','42501','Contributor must be existing active same-organization Team');
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,null,%L)',org,project,eng,'99999999-9999-4999-8999-999999999977',campaign,plan,deliverable,input),'42501','Content service cannot become Marketing context');
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,null,%L)',org,project,eng,service,campaign,'99999999-9999-4999-8999-999999997599',deliverable,input),'42501','Exact selected canonical plan required');
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,plan,input),'40001','Expected canonical deliverable head must match');
 saved:=public.confirm_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,null,input,review->>'review_checksum',request);
 perform pg_temp.check_true((select count(*) from public.deliverable_versions)=versions+1 and saved#>>'{version,review_status}'='in_production' and saved#>>'{version,state_version}'='1','Confirmation uses one new unchanged governed canonical version');
 perform pg_temp.check_true(saved#>>'{planning,input,brief}'=input->>'brief' and saved#>>'{planning,input,content_pillar}'='Product education' and saved#>>'{planning,input,topic}'='Launch adoption' and saved#>>'{planning,input,due_date}'='2026-10-15','Private exact-version planning carries brief/pillar/topic/planned deadline');
 perform pg_temp.check_true(saved#>'{version,preview_metadata}'='{}'::jsonb and saved#>>'{planning,deliverable_version_id}'=saved#>>'{version,id}','Internal brief/contributor metadata never enters client preview payload');
 perform pg_temp.check_true((select owner_id=actor and due_date='2026-10-10' and current_version_id=(saved#>>'{version,id}')::uuid from public.deliverables where id=deliverable) and (select count(*) from public.tasks)=tasks and (select count(*) from public.work_items)=work and (select count(*) from auth.users)=users,'Root owner/deadline/Tasks/Work Items/users unchanged');
 perform pg_temp.check_true((select count(*) from public.deliverable_lifecycle_events where deliverable_version_id=(saved#>>'{version,id}')::uuid and event_type='created')=1 and (select count(*) from public.deliverable_action_requests where actor_id=actor and request_id=request and action='create')=1,'Canonical lifecycle/action audit retained rather than bypassed');
 saved2:=public.confirm_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,null,input,review->>'review_checksum',request);
 perform pg_temp.check_true(saved2=saved and (select count(*) from public.deliverable_versions)=versions+1,'Original UUID replay returns one original version/receipt');
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,null,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,input||'{"topic":"Changed"}',review->>'review_checksum',request),'23505','Altered original UUID payload rejected');
 perform pg_temp.check_true(public.get_project_campaign_deliverable_plan_operation(org,project,request)=saved and public.get_project_campaign_deliverable_plan_operation(org,project,'99999999-9999-4999-8999-999999997599') is null,'Own exact UUID read-only recovery has no latest fallback');
 input:=input||jsonb_build_object('source_version_id',saved#>>'{version,id}','topic','New planned topic');
 review:=public.preview_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,(saved#>>'{version,id}')::uuid,input);
 perform pg_temp.check_true(review#>>'{snapshot,source,id}'=saved#>>'{version,id}' and review#>>'{snapshot,source,review_status}'='in_production','Source version/file/status provenance explicit without inheriting approval');
 update public.deliverables set due_date='2026-10-11' where id=deliverable;
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input,review->>'review_checksum','99999999-9999-4999-8999-999999997511'),'40001','Changed canonical root deadline invalidates new confirmation');
 update public.deliverables set due_date='2026-10-10' where id=deliverable;
 review:=public.preview_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,(saved#>>'{version,id}')::uuid,input);
 update public.organization_memberships set status='revoked' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input,review->>'review_checksum','99999999-9999-4999-8999-999999997511'),'42501','Revoked contributor/actor cannot confirm new version');
 update public.organization_memberships set status='active' where organization_id=org and user_id=actor;
 update public.engagement_services set status='on_hold' where id=service;
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,null,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>'{planning,input}',saved#>>'{original_snapshot,review_checksum}',request),'22023','Confirm always requires exact review checksum');
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input),'42501','Withdrawn current Marketing service rejects a new review');
 perform pg_temp.check_true(public.get_project_campaign_deliverable_plan_operation(org,project,request)=saved,'Current service withdrawal preserves original own operation receipt');
 update public.engagement_services set status='active' where id=service;
 update public.projects set archived_at=clock_timestamp() where id=project;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input),'42501','Archived project cannot create a new delivery plan');
 perform pg_temp.check_true(public.get_project_campaign_deliverable_plan_operation(org,project,request)=saved,'Project archive preserves original read-only receipt');
 update public.projects set archived_at=null where id=project;
 review:=public.preview_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,(saved#>>'{version,id}')::uuid,input);
 update public.deliverable_versions set title='Changed unapproved source title' where id=(saved#>>'{version,id}')::uuid;
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input,review->>'review_checksum','99999999-9999-4999-8999-999999997511'),'40001','Changed exact source checksum invalidates new consent');
 update public.deliverable_versions set title=saved#>>'{version,title}' where id=(saved#>>'{version,id}')::uuid;
 update public.deliverable_versions set withdrawn_at=clock_timestamp() where id=(saved#>>'{version,id}')::uuid;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input),'42501','Withdrawn source cannot be reused as a new version');
 perform pg_temp.check_true(public.get_project_campaign_deliverable_plan_operation(org,project,request)=saved,'Withdrawn source does not rewrite original private planning receipt');
 update public.deliverable_versions set withdrawn_at=null where id=(saved#>>'{version,id}')::uuid;
 select role,department_id into oldrole,olddept from public.organization_memberships where organization_id=org and user_id=actor;
 update public.organization_memberships set role='contributor',department_id='design' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_deliverable_plan(%L,%L,%L,%L,%L,%L,%L,%L,%L)',org,project,eng,service,campaign,plan,deliverable,saved#>>'{version,id}',input),'42501','Canonical authoring/Marketing project authority not expanded');
 update public.organization_memberships set role=oldrole,department_id=olddept where organization_id=org and user_id=actor;
 perform pg_temp.expect_error('update public.project_campaign_deliverable_plans set input=input','55000','Private exact-version planning provenance immutable');
 perform pg_temp.expect_error('update public.project_campaign_deliverable_plan_commands set receipt=receipt','55000','Original planning receipts immutable');
 perform pg_temp.check_true(not has_table_privilege('authenticated','public.project_campaign_deliverable_plans','SELECT') and not has_table_privilege('anon','public.project_campaign_deliverable_plans','SELECT') and not has_table_privilege('service_role','public.project_campaign_deliverable_plans','SELECT'),'Internal planning direct reads denied for Team/client/anonymous/service role');
 perform pg_temp.check_true(not has_table_privilege('authenticated','public.project_campaign_deliverable_plan_commands','SELECT') and not has_table_privilege('service_role','public.project_campaign_deliverable_plan_commands','INSERT'),'No direct authenticated/service receipt access');
end $$;
set local role authenticated;
do $$declare original jsonb;input jsonb;review jsonb;saved jsonb;begin
 original:=public.get_project_campaign_deliverable_plan_operation('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999997510');
 input:=original#>'{planning,input}';input:=input||jsonb_build_object('source_version_id',original#>>'{version,id}','topic','Authenticated canonical planning');
 review:=public.preview_project_campaign_deliverable_plan('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999999975','99999999-9999-4999-8999-999999997171','99999999-9999-4999-8999-999999997172','99999999-9999-4999-8999-999999997173','99999999-9999-4999-8999-999999997500',(original#>>'{version,id}')::uuid,input);
 saved:=public.confirm_project_campaign_deliverable_plan('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999999975','99999999-9999-4999-8999-999999997171','99999999-9999-4999-8999-999999997172','99999999-9999-4999-8999-999999997173','99999999-9999-4999-8999-999999997500',(original#>>'{version,id}')::uuid,input,review->>'review_checksum','99999999-9999-4999-8999-999999997512');
 perform pg_temp.check_true(saved#>>'{version,version_number}'='2' and saved#>>'{planning,input,source_version_id}'=original#>>'{version,id}','Actual authenticated writer retains source version and canonical new-version audit');
 perform pg_temp.expect_error('select * from public.project_campaign_deliverable_plan_commands','42501','Authenticated direct receipt reads denied');
 perform pg_temp.expect_error('select private.campaign_deliverable_plan_input(null)','42501','Authenticated private helper denied');
end $$;
reset role;
set local role anon;
select pg_temp.expect_error('select public.get_project_campaign_deliverable_plan_operation(null,null,null)','42501','Anonymous receipt recovery denied');
reset role;
set local role service_role;
select pg_temp.expect_error('select public.get_project_campaign_deliverable_plan_operation(null,null,null)','42501','Service-role recovery denied');
reset role;
rollback;
