begin;
\ir project_website_pages.fixture.sql
create function pg_temp.page_assert(p_ok boolean,p_name text) returns void language plpgsql as $$begin if p_ok is distinct from true then raise exception 'FAIL %',p_name;end if;raise notice 'PASS %',p_name;end;$$;
create function pg_temp.page_error(p_sql text,p_state text,p_name text) returns void language plpgsql as $$begin begin execute p_sql;exception when others then if sqlstate<>p_state then raise exception 'FAIL % expected % got %: %',p_name,p_state,sqlstate,sqlerrm;end if;raise notice 'PASS %',p_name;return;end;raise exception 'FAIL % did not reject',p_name;end;$$;
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';version uuid:='99999999-9999-4999-8999-999999997141';new_version uuid:='99999999-9999-4999-8999-999999997143';request uuid:=gen_random_uuid();save_request uuid:=gen_random_uuid();link_request uuid:=gen_random_uuid();keys jsonb;preview jsonb;result jsonb;again jsonb;page uuid;other uuid;ops jsonb;history jsonb;before_count bigint;begin
 select jsonb_agg('page:'||i order by i) into keys from generate_series(1,101)i;
 select count(*) into before_count from public.project_website_page_commands;
 preview:=public.preview_project_website_pages(org,project,version,keys);
 perform pg_temp.page_assert(jsonb_array_length(preview->'pages')=101 and (select count(*) from public.project_website_page_commands)=before_count and not exists(select 1 from public.project_website_pages where project_id=project),'101-page preview writes zero records');
 result:=public.register_project_website_pages(org,project,version,keys,preview->>'review_sha256',request);
 page:=(result->'pages'->0->>'page_id')::uuid;other:=(result->'pages'->1->>'page_id')::uuid;
 perform pg_temp.page_assert(jsonb_array_length(result->'pages')=101 and (select count(*) from public.project_website_pages where project_id=project)=101,'101-page atomic identity registration');
 again:=public.register_project_website_pages(org,project,version,keys,preview->>'review_sha256',request);
 perform pg_temp.page_assert(again-'idempotent_replay'=result-'idempotent_replay' and again->>'idempotent_replay'='true','Exact registration retry returns original stable IDs');
 perform pg_temp.page_error(format('select public.register_project_website_pages(%L,%L,%L,%L,%L,%L)',org,project,version,'["page:1"]',preview->>'review_sha256',request),'23505','Changed batch cannot reuse operation UUID');
 perform pg_temp.page_error(format('select public.register_project_website_pages(%L,%L,%L,%L,%L,%L)',org,project,version,keys,'stale',gen_random_uuid()),'40001','Confirmation rejects stale preview');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)',org,project,'99999999-9999-4999-8999-999999997147','["page:1"]'),'23505','Same page key never merges another architecture root');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)',org,project,'99999999-9999-4999-8999-999999997145','["page:1"]'),'42501','Newer unapproved draft is excluded');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)',org,'99999999-9999-4999-8999-999999999999',version,'["page:1"]'),'42501','Foreign project rejected');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)','99999999-9999-4999-8999-999999999999',project,version,'["page:1"]'),'42501','Foreign organization rejected');
 ops:=jsonb_build_object('planned_url','https://example.invalid/home','recorded_live_url',null,'redirect_url',null,'publication_state','in_progress','template','Service page','work_item_id','99999999-9999-4999-8999-999999997160','implementation_notes',E'Keep the approved structure\nCheck the mobile layout','qa_evidence','');
 result:=public.save_project_website_page_operations(org,project,page,version,0,ops,save_request);
 perform pg_temp.page_assert(result->>'revision_number'='1','First immutable operational revision');
 again:=public.save_project_website_page_operations(org,project,page,version,0,ops,save_request);
 perform pg_temp.page_assert(again->>'revision_id'=result->>'revision_id' and again->>'idempotent_replay'='true','Lost save response recovers exact original revision');
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,0,%L,%L)',org,project,page,version,ops,gen_random_uuid()),'40001','Competing stale operational edit rejected');
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,1,%L,%L)',org,project,page,version,ops||'{"owner_id":"99999999-9999-4999-8999-999999999902"}',gen_random_uuid()),'22023','Parallel assignment fields rejected');
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,1,%L,%L)',org,project,page,version,jsonb_set(ops,'{work_item_id}','"99999999-9999-4999-8999-999999997130"'),gen_random_uuid()),'42501','Unlinked canonical work is not adopted by title');
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,1,%L,%L)',org,project,page,version,jsonb_set(ops,'{planned_url}','"https://secret:password@example.invalid/path"'),gen_random_uuid()),'22023','Credential URL rejected');
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,1,%L,%L)',org,project,page,version,jsonb_set(ops,'{publication_state}','"published"'),gen_random_uuid()),'22023','Published evidence requires recorded live URL');
 ops:=ops||jsonb_build_object('planned_url','https://example.invalid/welcome','recorded_live_url','https://example.invalid/home','redirect_url','https://example.invalid/welcome','publication_state','published','qa_evidence','Synthetic manual record; no external publication');
 result:=public.save_project_website_page_operations(org,project,page,new_version,1,ops,gen_random_uuid());
 perform pg_temp.page_assert(result->>'revision_number'='2' and result->>'page_id'=page::text,'Approved rename keeps stable page identity');
 history:=public.get_project_website_page_history(org,project,page);
 perform pg_temp.page_assert(history->'page'->>'initial_path'='home' and history->'revisions'->0->>'planned_path'='welcome' and history->'revisions'->1->>'planned_path'='home' and history->'revisions'->0->>'recorded_live_url'='https://example.invalid/home','URL redirect and original path history retained');
 perform pg_temp.page_assert((select linked_page_path='home' and linked_page_key='page:1' and assignee_id='99999999-9999-4999-8999-999999999902' and due_date='2026-10-10' from public.work_items where id='99999999-9999-4999-8999-999999997160'),'Canonical work assignment and immutable path unchanged');
 result:=public.link_project_website_page_seo(org,project,page,new_version,'99999999-9999-4999-8999-999999997150',0,link_request);
 again:=public.link_project_website_page_seo(org,project,page,new_version,'99999999-9999-4999-8999-999999997150',0,link_request);
 perform pg_temp.page_assert(result->>'link_number'='1' and result->>'link_id'=again->>'link_id' and again->>'idempotent_replay'='true','Explicit same-brand SEO link has exact retry');
 perform pg_temp.page_error(format('select public.link_project_website_page_seo(%L,%L,%L,%L,%L,0,%L)',org,project,other,new_version,'99999999-9999-4999-8999-999999997150',gen_random_uuid()),'23505','One current SEO target cannot silently map two project pages');
 perform pg_temp.page_error(format('select public.link_project_website_page_seo(%L,%L,%L,%L,%L,1,%L)',org,project,page,new_version,'99999999-9999-4999-8999-999999999999',gen_random_uuid()),'42501','Foreign SEO target denied');
 result:=public.list_project_website_pages(org,project,new_version);
 perform pg_temp.page_assert(result->'counts'->>'total'='101' and result->'counts'->>'published'='1' and result->'counts'->>'planned'='100' and result->'counts'->>'linked_seo'='1' and result->'counts'->>'assigned'='1' and result->'counts'->>'has_deadline'='1' and jsonb_array_length(result->'pages')=25,'101-page paging and nonexclusive status/link/assignment counts');
 perform pg_temp.page_assert(result->'pages'->0->>'owner_id'='99999999-9999-4999-8999-999999999902' and result->'pages'->0->>'due_date'='2026-10-10','Read derives current owner/deadline from canonical work');
 result:=public.list_project_website_pages(org,project,new_version,'','published');
 perform pg_temp.page_assert(result->'counts'->>'filtered_total'='1' and result->'counts'->>'total'='101' and jsonb_array_length(result->'pages')=1,'Filter does not collapse whole-architecture counters');
 result:=public.list_project_website_pages(org,project,new_version,'',null,'page:1',75,25);
 perform pg_temp.page_assert(result->'counts'->>'filtered_total'='100' and jsonb_array_length(result->'pages')=25,'Hierarchy filter and explicit offset remain bounded');
 result:=public.list_project_website_pages(org,project,new_version,'welcome');
 perform pg_temp.page_assert(result->'counts'->>'filtered_total'='1' and result->'pages'->0->'source'->>'path'='welcome','Search uses exact selected approved rename, never latest draft');
 result:=public.link_project_website_page_seo(org,project,page,new_version,null,1,gen_random_uuid());
 perform pg_temp.page_assert(result->>'link_number'='2' and result->'tracked_page_id'='null'::jsonb and (public.get_project_website_page_history(org,project,page)->'seo_links'->1->>'tracked_page_id')='99999999-9999-4999-8999-999999997150','Explicit unlink preserves original SEO history');
 perform pg_temp.page_error(format('update public.project_website_pages set initial_path=%L where id=%L','renamed',page),'55000','Page identity immutable');
 perform pg_temp.page_error(format('delete from public.project_website_page_revisions where page_id=%L',page),'55000','Operational history immutable');
 perform pg_temp.page_error(format('select public.list_project_website_pages(%L,%L,%L,%L,null,null,0,101)',org,project,new_version,''),'22023','Over-bounded page size rejected');
 perform pg_temp.page_assert(public.get_project_website_page_operation(org,project,save_request)->'result'->>'revision_number'='1','UUID-only recovery reads the original operation, not latest page revision');
 perform pg_temp.page_assert(public.get_project_website_page_operation(org,project,gen_random_uuid()) is null,'Unknown operation remains unresolved without guessed latest history');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)',org,project,version,'["missing"]'),'22023','Unknown source page key rejected');
 perform pg_temp.page_error(format('select public.preview_project_website_pages(%L,%L,%L,%L)',org,project,version,'["page:1","page:1"]'),'22023','Duplicate selected page key rejected');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"page_key":"a","slug":"home","title":"A","page_type":"hub","parent_page_key":"b"},{"page_key":"b","slug":"other","title":"B","page_type":"supporting","parent_page_key":"a"}]}''::jsonb)','22023','Native hierarchy cycle rejected');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"page_key":"a","slug":"home","title":"A","page_type":"hub","parent_page_key":"missing"}]}''::jsonb)','22023','Native missing parent rejected');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"page_key":"a","slug":"home","title":"A","page_type":"hub"},{"page_key":"b","slug":"HOME","title":"B","page_type":"supporting"}]}''::jsonb)','22023','Native duplicate normalized path rejected');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"slug":"home / contact","title":"A","page_type":"hub"}]}''::jsonb)','55000','Legacy normalization disagreement requires explicit reconciliation');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"page_key":"a","slug":"../unsafe","title":"A","page_type":"hub"}]}''::jsonb)','22023','Native traversal path rejected');
 perform pg_temp.page_error('select private.website_architecture_pages(''{"pages":[{"page_key":"a","slug":"https://example.invalid/home","title":"A","page_type":"hub"}]}''::jsonb)','22023','Native URL identity rejected');
 perform pg_temp.page_assert((public.get_project_website_page_history(org,project,page)->'seo_links'->1->>'architecture_version_id')=new_version::text,'SEO link keeps its exact approved architecture version');
 -- Fail the final receipt INSERT to prove the new revision and its history roll back together.
 execute 'create function pg_temp.reject_page_receipt() returns trigger language plpgsql as $f$begin raise exception ''Synthetic receipt failure'';end;$f$';
 execute 'create trigger synthetic_receipt_failure before insert on public.project_website_page_commands for each row execute function pg_temp.reject_page_receipt()';
 perform pg_temp.page_error(format('select public.save_project_website_page_operations(%L,%L,%L,%L,2,%L,%L)',org,project,page,new_version,ops,gen_random_uuid()),'P0001','Final receipt failure rejects whole operational save');
 perform pg_temp.page_assert((select count(*)=2 from public.project_website_page_revisions where page_id=page),'Failed atomic receipt leaves no orphan operational revision');
 execute 'drop trigger synthetic_receipt_failure on public.project_website_page_commands';
 perform pg_temp.page_assert((select content->'pages'->0->>'slug'='home' and content->'pages'->0->'sections'->0->>'heading'='Approved heading' from public.artifact_versions where id=version),'Canonical architecture fields unchanged');
end;$$;
-- Direct grants cannot bypass native writers; service has read-only internal catalog access.
select pg_temp.page_assert(not has_table_privilege('authenticated','public.project_website_pages','INSERT') and not has_table_privilege('service_role','public.project_website_page_revisions','INSERT') and not has_function_privilege('service_role','public.register_project_website_pages(uuid,uuid,uuid,jsonb,text,uuid)','EXECUTE'),'No direct or service native write bypass');
set local role authenticated;
select pg_temp.page_assert((select count(*)=101 from public.project_website_pages),'Active team RLS sees project records');
reset role;
update public.organization_memberships set status='suspended' where organization_id='99999999-9999-4999-8999-999999999901' and user_id='99999999-9999-4999-8999-999999999902';
set local role authenticated;
select pg_temp.page_assert((select count(*)=0 from public.project_website_pages),'Revoked active-team RLS hides all page records');
select pg_temp.page_error('select public.list_project_website_pages(''99999999-9999-4999-8999-999999999901'',''99999999-9999-4999-8999-999999999974'',''99999999-9999-4999-8999-999999997141'')','42501','Removed membership denies read API');
reset role;
rollback;
