-- Synthetic existing-actor fixtures in one rollback. No users/providers/production writes.
begin;
set local lock_timeout='5s';set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
insert into public.artifacts select (jsonb_populate_record(null::public.artifacts,to_jsonb(a)||jsonb_build_object('id','99999999-9999-4999-8999-999999997300','artifact_type','audience','title','Synthetic approved campaign audience'))).* from public.artifacts a where id='99999999-9999-4999-8999-999999997140';
insert into public.artifact_versions select (jsonb_populate_record(null::public.artifact_versions,to_jsonb(v)||jsonb_build_object('id','99999999-9999-4999-8999-999999997301','artifact_id','99999999-9999-4999-8999-999999997300','content',jsonb_build_object('audience','Synthetic campaign audience'),'content_checksum',encode(sha256(convert_to(jsonb_build_object('audience','Synthetic campaign audience')::text,'UTF8')),'hex')))).* from public.artifact_versions v where id='99999999-9999-4999-8999-999999997141';
insert into public.artifact_approvals select (jsonb_populate_record(null::public.artifact_approvals,to_jsonb(v)||jsonb_build_object('id','99999999-9999-4999-8999-999999997302','artifact_id','99999999-9999-4999-8999-999999997300','artifact_version_id','99999999-9999-4999-8999-999999997301'))).* from public.artifact_approvals v where id='99999999-9999-4999-8999-999999997142';
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';eng uuid:='99999999-9999-4999-8999-999999999975';campaign uuid:='99999999-9999-4999-8999-999999997172';request uuid:='99999999-9999-4999-8999-999999997310';expected uuid;input jsonb;review jsonb;saved jsonb;saved2 jsonb;query text;plans bigint;links bigint;commands bigint;tasks bigint;work bigint;users bigint;oldrole text;olddept text;actor uuid:='99999999-9999-4999-8999-999999999902';
begin
 select id into expected from public.marketing_campaign_plan_versions where organization_id=org and campaign_id=campaign order by version_number desc limit 1;
 select count(*) into plans from public.marketing_campaign_plan_versions;select count(*) into links from public.project_campaign_plan_links;select count(*) into commands from public.project_campaign_plan_commands;select count(*) into tasks from public.tasks;select count(*) into work from public.work_items;select count(*) into users from auth.users;
 input:=jsonb_build_object('title','Synthetic canonical reviewed draft','objective','Keep exact source and canonical version lineage','channels',jsonb_build_array('Website','Instagram'),'starts_on','2026-10-10','ends_on','2026-10-20','audience','Existing audience strategy','landing_page_url','https://example.invalid/campaign','planned_budget',0,'currency_code','USD','approved_message_version_id',null,'measurement_plan_version_id',null,'creative_requirements',jsonb_build_array(jsonb_build_object('format','Article','intended_placement','Website blog','message_version_id',null,'due_date','2026-10-15')),'change_summary','Synthetic reviewed plan','source_plan_version_id',null,'marketing_service_id','99999999-9999-4999-8999-999999997171','owner_id',actor,'strategy_version_ids',jsonb_build_array('99999999-9999-4999-8999-999999997301'));
 review:=public.preview_project_campaign_plan(org,project,eng,campaign,expected,input);
 perform pg_temp.check_true((select count(*) from public.marketing_campaign_plan_versions)=plans and (select count(*) from public.project_campaign_plan_links)=links and (select count(*) from public.project_campaign_plan_commands)=commands and review->>'zero_write'='true','Exact canonical plan review makes zero writes');
 perform pg_temp.check_true(review#>>'{snapshot,sources,0,version_id}'='99999999-9999-4999-8999-999999997301' and review#>>'{snapshot,sources,0,approval,approval_id}'='99999999-9999-4999-8999-999999997302','Audience strategy retains exact original approved version and approval');
 perform pg_temp.check_true(review#>>'{snapshot,owner,user_id}'=actor::text and review#>>'{snapshot,service,id}'='99999999-9999-4999-8999-999999997171' and review#>>'{snapshot,ready_to_publish}'='false','Existing Team owner/service do not authorize publication');
 query:=format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,',org,project,eng,campaign,expected);
 perform pg_temp.expect_error(query||quote_literal(input||'{"extra":"unsupported"}')||'::jsonb)','22023','Unknown plan fields rejected without silent truncation');
 perform pg_temp.expect_error(query||quote_literal(input||'{"title":""}')||'::jsonb)','22023','Empty canonical title rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"title":23}')||'::jsonb)','22023','Text cannot be coerced from number');
 perform pg_temp.expect_error(query||quote_literal(input||'{"starts_on":"2026-02-30"}')||'::jsonb)','22008','Nonexistent calendar date rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"ends_on":"2026-10-01"}')||'::jsonb)','22023','End date before start rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"channels":["Website","Website"]}')||'::jsonb)','22023','Duplicate channel selection rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"currency_code":null}')||'::jsonb)','22023','Zero budget still requires explicit currency');
 perform pg_temp.expect_error(query||quote_literal(input||'{"planned_budget":-1}')||'::jsonb)','22023','Negative planning budget rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"landing_page_url":"https://secret@example.invalid"}')||'::jsonb)','22023','Credential-bearing landing URL rejected');
 perform pg_temp.expect_error(query||quote_literal(input||'{"owner_id":"99999999-9999-4999-8999-999999997399"}')||'::jsonb)','42501','Unknown/non-Team owner cannot be synthesized');
 perform pg_temp.expect_error(query||quote_literal(input||'{"marketing_service_id":"99999999-9999-4999-8999-999999999977"}')||'::jsonb)','42501','Content service cannot become Marketing scope');
 perform pg_temp.expect_error(query||quote_literal(input||'{"strategy_version_ids":["99999999-9999-4999-8999-999999997141"]}')||'::jsonb)','42501','Architecture cannot be inferred as audience strategy');
 perform pg_temp.expect_error(query||quote_literal(input||'{"strategy_version_ids":["99999999-9999-4999-8999-999999997301","99999999-9999-4999-8999-999999997301"]}')||'::jsonb)','22023','Duplicate exact strategy references rejected');
 saved:=public.confirm_project_campaign_plan(org,project,eng,campaign,expected,input,review->>'review_checksum',request);
 perform pg_temp.check_true(saved#>>'{plan,parent_version_id}'=expected::text and (select count(*) from public.marketing_campaign_plan_versions)=plans+1 and (select count(*) from public.project_campaign_plan_links)=links+1 and (select count(*) from public.project_campaign_plan_commands)=commands+1,'One confirmation atomically reuses canonical draft writer and records links/receipt');
 perform pg_temp.check_true((saved#>>'{plan,planned_budget}')::numeric=0 and saved#>>'{plan,currency_code}'='USD' and saved->>'approval_state'='draft','Zero budget/currency and unapproved draft remain explicit');
 perform pg_temp.check_true((select format from public.marketing_campaign_plan_creative_requirements where plan_version_id=(saved#>>'{plan,id}')::uuid)='Article' and (select count(*) from public.tasks)=tasks and (select count(*) from public.work_items)=work and (select count(*) from auth.users)=users,'Canonical requirements preserved with no cloned work or users');
 perform pg_temp.check_true(public.confirm_project_campaign_plan(org,project,eng,campaign,expected,input,review->>'review_checksum',request)=saved and (select count(*) from public.marketing_campaign_plan_versions)=plans+1,'Original actor/UUID/payload replays identical receipt and one plan');
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb,%L,%L)',org,project,eng,campaign,expected,input||'{"objective":"Changed"}',review->>'review_checksum',request),'23505','Changed same-UUID payload conflicts rather than duplicating');
 perform pg_temp.check_true(public.get_project_campaign_plan_operation(org,project,request)=saved and public.get_project_campaign_plan_operation(org,project,'99999999-9999-4999-8999-999999997319') is null,'Read-only recovery returns original receipt or unknown without latest fallback');
 perform pg_temp.check_true(public.get_project_campaign_plan_version(org,project,eng,campaign,(saved#>>'{plan,id}')::uuid)#>>'{links,owner_id}'=actor::text,'Explicit immutable version read retains exact original associations');
 perform pg_temp.expect_error(query||quote_literal(input)||'::jsonb)','40001','Competing canonical plan makes old expected head stale');
 update public.engagements set status='on_hold' where id=eng;
 perform pg_temp.check_true(public.confirm_project_campaign_plan(org,project,eng,campaign,expected,input,review->>'review_checksum',request)=saved,'Recognized original operation replays retained receipt without renewing withdrawn source engagement');
 expected:=(saved#>>'{plan,id}')::uuid;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb)',org,project,eng,campaign,expected,input),'42501','Withdrawn source engagement blocks new plan review');
 update public.engagements set status='active' where id=eng;
 review:=public.preview_project_campaign_plan(org,project,eng,campaign,expected,input);
 update public.engagement_services set target_date='2026-10-19' where id='99999999-9999-4999-8999-999999997171';
 perform pg_temp.expect_error(format('select public.confirm_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb,%L,%L)',org,project,eng,campaign,expected,input,review->>'review_checksum','99999999-9999-4999-8999-999999997311'),'40001','Changed current service metadata invalidates reviewed snapshot');
 update public.engagement_services set status='on_hold' where id='99999999-9999-4999-8999-999999997171';
 perform pg_temp.expect_error(format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb)',org,project,eng,campaign,expected,input),'42501','Withdrawn Marketing service blocks new canonical draft');
 update public.engagement_services set status='active' where id='99999999-9999-4999-8999-999999997171';
 update public.organization_memberships set status='revoked' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb)',org,project,eng,campaign,expected,input),'42501','Revoked actor cannot write');
 update public.organization_memberships set status='active' where organization_id=org and user_id=actor;
 select role,department_id into oldrole,olddept from public.organization_memberships where organization_id=org and user_id=actor;
 update public.organization_memberships set role='project_owner',department_id='content' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb)',org,project,eng,campaign,expected,input),'42501','Project-owner role does not broaden existing canonical Marketing writer access');
 update public.organization_memberships set role=oldrole,department_id=olddept where organization_id=org and user_id=actor;
 update public.projects set archived_at=clock_timestamp() where id=project;
 perform pg_temp.expect_error(format('select public.preview_project_campaign_plan(%L,%L,%L,%L,%L,%L::jsonb)',org,project,eng,campaign,expected,input),'42501','Archived project blocks new drafts');
 perform pg_temp.check_true(public.get_project_campaign_plan_operation(org,project,request)=saved,'Archived project preserves Team original-operation history');
 update public.projects set archived_at=null where id=project;
 input:=input||'{"owner_id":null,"strategy_version_ids":[],"starts_on":null,"ends_on":null,"planned_budget":null,"currency_code":null}';
 review:=public.preview_project_campaign_plan(org,project,eng,campaign,expected,input);
 perform pg_temp.check_true(review#>'{snapshot,blocking_reasons}' @> '["campaign_owner_missing","approved_audience_strategy_missing","campaign_dates_incomplete"]' and review#>>'{snapshot,ready_to_publish}'='false','Incomplete plan can be reviewed while missing readiness remains explicit');
 saved2:=public.confirm_project_campaign_plan(org,project,eng,campaign,expected,input,review->>'review_checksum','99999999-9999-4999-8999-999999997312');
 perform pg_temp.check_true(saved2#>'{links,owner_id}'='null'::jsonb and saved2->>'ready_to_publish'='false','Incomplete canonical draft saves without invented owner/approval');
 perform pg_temp.expect_error(format('update public.project_campaign_plan_links set owner_id=null where id=%L',(saved#>>'{links,id}')),'55000','Original plan associations are immutable');
 perform pg_temp.expect_error(format('delete from public.project_campaign_plan_commands where request_id=%L',request),'55000','Original command receipts are immutable');
end $$;
create temporary table auth_plan_input as select id expected,jsonb_build_object('title','Synthetic authenticated canonical draft','objective','Verify real authenticated writer grant','channels',jsonb_build_array('Website'),'starts_on',null,'ends_on',null,'audience','','landing_page_url',null,'planned_budget',0,'currency_code','USD','approved_message_version_id',null,'measurement_plan_version_id',null,'creative_requirements',jsonb_build_array(),'change_summary','Synthetic authenticated API verification','source_plan_version_id',null,'marketing_service_id','99999999-9999-4999-8999-999999997171','owner_id',null,'strategy_version_ids',jsonb_build_array()) input from public.marketing_campaign_plan_versions where campaign_id='99999999-9999-4999-8999-999999997172' order by version_number desc limit 1;
 grant select on auth_plan_input to authenticated;
set local role authenticated;
do $$declare ctx record;review jsonb;receipt jsonb;org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';eng uuid:='99999999-9999-4999-8999-999999999975';campaign uuid:='99999999-9999-4999-8999-999999997172';begin select * into ctx from auth_plan_input;review:=public.preview_project_campaign_plan(org,project,eng,campaign,ctx.expected,ctx.input);receipt:=public.confirm_project_campaign_plan(org,project,eng,campaign,ctx.expected,ctx.input,review->>'review_checksum','99999999-9999-4999-8999-999999997313');perform pg_temp.check_true(receipt->>'request_id'='99999999-9999-4999-8999-999999997313' and receipt#>>'{plan,parent_version_id}'=ctx.expected::text,'Authenticated review/confirm writes exactly the canonical parent version through closed tables');end $$;

select pg_temp.check_true(public.get_project_campaign_plan_operation('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999997310')->>'request_id'='99999999-9999-4999-8999-999999997310','Authenticated API reads original receipt with closed table access');
select pg_temp.expect_error('select * from public.project_campaign_plan_links','42501','Authenticated direct association-table access denied');
select pg_temp.expect_error('select private.campaign_plan_input(null)','42501','Private plan helpers inaccessible to authenticated');
reset role;
set local role anon;
select pg_temp.expect_error('select public.get_project_campaign_plan_operation(null,null,null)','42501','Anonymous native plan API denied');
reset role;
set local role service_role;
select pg_temp.expect_error('select public.get_project_campaign_plan_operation(null,null,null)','42501','Service role cannot bypass actor-owned plan recovery');
reset role;
rollback;
