-- Named synthetic existing-actor fixtures in one rollback; no users/providers.
begin;
set local lock_timeout='5s';set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
-- Local clone legacy activity default is restored exactly by ROLLBACK, never a production workaround.
alter table public.activity_events alter column organization_id set default '99999999-9999-4999-8999-999999999901'::uuid;
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
insert into public.workstreams(id,organization_id,project_id,department_id,name,status) values('99999999-9999-4999-8999-999999997501','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','marketing','Synthetic reviewed campaign planning','active');
insert into public.deliverables(id,organization_id,project_id,workstream_id,title,description,deliverable_type,status,visibility,owner_id,created_by,due_date) values('99999999-9999-4999-8999-999999997500','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999997501','Synthetic campaign delivery','Existing governed deliverable fixture','article','in_production','internal_only','99999999-9999-4999-8999-999999999902','99999999-9999-4999-8999-999999999902','2026-10-10');
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';eng uuid:='99999999-9999-4999-8999-999999999975';service uuid:='99999999-9999-4999-8999-999999997171';campaign uuid:='99999999-9999-4999-8999-999999997172';plan uuid:='99999999-9999-4999-8999-999999997173';deliverable uuid:='99999999-9999-4999-8999-999999997500';actor uuid:='99999999-9999-4999-8999-999999999902';input jsonb;review jsonb;saved jsonb;data jsonb;version uuid;versions bigint;commands bigint;oldkind text;oldrole text;begin
 input:=jsonb_build_object('title','Synthetic read delivery plan','brief','Private exact-version brief remains private','format','Article','content_pillar','Product education','topic','Exact native history','due_date','2026-10-15','contributor_ids',jsonb_build_array(actor),'change_summary','Synthetic read fixture','source_version_id',null,'client_approval_required',false);
 review:=public.preview_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,null,input);
 saved:=public.confirm_project_campaign_deliverable_plan(org,project,eng,service,campaign,plan,deliverable,null,input,review->>'review_checksum','99999999-9999-4999-8999-999999997550');version:=(saved#>>'{version,id}')::uuid;
 select count(*) into versions from public.deliverable_versions;select count(*) into commands from public.project_campaign_deliverable_plan_commands;
 data:=public.list_project_campaign_deliverable_candidates(org,project,eng,'deliverables',null,'Existing unmatched title',0,1);
 perform pg_temp.check_true((data->>'total')::bigint>=2 and data->>'matching'='0' and data->'items'='[]','Whole deliverable total independent of filtered search');
 data:=public.list_project_campaign_deliverable_candidates(org,project,eng,'deliverables',null,'Synthetic campaign delivery',0,1);
 perform pg_temp.check_true(data#>>'{items,0,id}'=deliverable::text and data#>>'{items,0,owner_id}'=actor::text and data#>>'{items,0,due_date}'='2026-10-10' and not(data#>'{items,0}'?'preview_metadata'),'Bounded existing deliverable selector shows canonical owner/deadline without internal brief');
 data:=public.list_project_campaign_deliverable_candidates(org,project,eng,'deliverables',null,deliverable::text,0,1);
 perform pg_temp.check_true(data->>'matching'='1' and data#>>'{items,0,id}'=deliverable::text,'Explicit exact-ID canonical head read has no title/latest fallback');
 data:=public.list_project_campaign_deliverable_candidates(org,project,eng,'versions',deliverable,'',0,1);
 perform pg_temp.check_true(data#>>'{items,0,id}'=version::text and data#>>'{items,0,review_status}'='in_production' and data#>>'{items,0,has_current_engagement_planning}'='true' and not(data#>'{items,0}'?'preview_metadata'),'Exact canonical version selector never auto-inherits approval or private contents');
 data:=public.get_project_campaign_deliverable_version(org,project,eng,deliverable,version);
 perform pg_temp.check_true(data#>>'{planning,input,brief}'=input->>'brief' and data#>>'{planning,deliverable_version_id}'=version::text and data#>>'{version,preview_metadata}'='{}','Private planning linked to one exact canonical version without client preview leakage');
 perform pg_temp.check_true(data->>'planning_state'='original_current_engagement' and data->>'original_canonical_content_matches'='true' and data#>>'{version,review_status}'='in_production' and data#>>'{current_capabilities,state_version}'='1','Original private planning and current exact-version governance are separate');
 perform pg_temp.check_true(data->>'provider_request_made'='false' and data->>'ready_to_publish'='false' and data->>'external_write_authorized'='false','Metadata read cannot certify provider access or publishing');
 update public.deliverable_versions set title='Changed canonical unapproved title' where id=version;
 data:=public.get_project_campaign_deliverable_version(org,project,eng,deliverable,version);
 perform pg_temp.check_true(data->>'original_canonical_content_matches'='false' and data#>>'{planning,input,title}'=input->>'title' and data#>>'{version,title}'='Changed canonical unapproved title','Current content drift retains original private reviewed title');
 update public.deliverable_versions set title=input->>'title' where id=version;
 update public.engagement_services set status='on_hold' where id=service;
 data:=public.get_project_campaign_deliverable_version(org,project,eng,deliverable,version);
 perform pg_temp.check_true(data->>'current_service_available'='false' and data#>>'{planning,input,brief}'=input->>'brief','Current service withdrawal preserves original private planning');
 update public.engagement_services set status='active' where id=service;
 update public.projects set archived_at=clock_timestamp() where id=project;
 data:=public.get_project_campaign_deliverable_version(org,project,eng,deliverable,version);
 perform pg_temp.check_true(data->>'project_archived'='true' and data#>>'{planning,deliverable_version_id}'=version::text and data->'current_capabilities'='null' and data->>'capabilities_state'='archived_project','Archived project retains exact original planning read');
 update public.projects set archived_at=null where id=project;
 perform pg_temp.expect_error(format('select public.get_project_campaign_deliverable_version(%L,%L,%L,%L,%L)',org,project,eng,deliverable,plan),'42501','Foreign root/version identity rejected without latest fallback');
 perform pg_temp.expect_error(format('select public.list_project_campaign_deliverable_candidates(%L,%L,%L,%L,null)',org,project,eng,'versions'),'42501','Version selector needs one explicit existing deliverable');
 perform pg_temp.expect_error(format('select public.list_project_campaign_deliverable_candidates(%L,%L,%L,%L,null)',org,project,eng,'latest'),'22023','Unknown/unbounded selector kinds rejected');
 perform pg_temp.expect_error(format('select public.list_project_campaign_deliverable_candidates(%L,%L,%L,%L,null,%L,0,51)',org,project,eng,'deliverables',''),'22023','Selector limit above fifty rejected');
 data:=public.list_project_campaign_deliverable_candidates(org,project,eng,'versions',deliverable,'',1,1);perform pg_temp.check_true(data->'items'='[]' and data->>'total'='1','Offset does not substitute another latest version');
 update public.organization_memberships set status='revoked' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.get_project_campaign_deliverable_version(%L,%L,%L,%L,%L)',org,project,eng,deliverable,version),'42501','Revoked Team cannot read private planning');
 update public.organization_memberships set status='active' where organization_id=org and user_id=actor;
 select member_kind,role into oldkind,oldrole from public.organization_memberships where organization_id=org and user_id=actor;
 update public.organization_memberships set member_kind='client',role='client_viewer' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.get_project_campaign_deliverable_version(%L,%L,%L,%L,%L)',org,project,eng,deliverable,version),'42501','Client identities cannot read internal planning projection');
 update public.organization_memberships set member_kind=oldkind,role=oldrole where organization_id=org and user_id=actor;
 update public.deliverables set title=repeat('x',131073) where id=deliverable;
 perform pg_temp.expect_error(format('select public.list_project_campaign_deliverable_candidates(%L,%L,%L,%L,null,%L,0,1)',org,project,eng,'deliverables',repeat('x',30)),'22023','Whole selector response bound refuses complete oversized record');
 update public.deliverables set title='Synthetic campaign delivery' where id=deliverable;
 update public.deliverable_versions set preview_metadata=jsonb_build_object('legacy_metadata',repeat('x',131073)) where id=version;
 perform pg_temp.expect_error(format('select public.get_project_campaign_deliverable_version(%L,%L,%L,%L,%L)',org,project,eng,deliverable,version),'22023','Exact history whole response bound refuses truncation');
 update public.deliverable_versions set preview_metadata='{}' where id=version;
 perform pg_temp.check_true((select count(*) from public.deliverable_versions)=versions and (select count(*) from public.project_campaign_deliverable_plan_commands)=commands,'Explicit reads create no versions/actions/provider writes');
 perform pg_temp.check_true((select count(*) from public.deliverable_lifecycle_events where deliverable_version_id=version and event_type='created')=1,'Canonical original lifecycle audit remains untouched');
end $$;
set local role authenticated;
select pg_temp.check_true((public.list_project_campaign_deliverable_candidates('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999999975','deliverables',null,'',0,1)->>'provider_request_made')='false','Actual authenticated bounded read makes no provider request');
reset role;
set local role anon;
select pg_temp.expect_error('select public.get_project_campaign_deliverable_version(null,null,null,null,null)','42501','Anonymous internal planning read denied');
reset role;
set local role service_role;
select pg_temp.expect_error('select public.get_project_campaign_deliverable_version(null,null,null,null,null)','42501','Service-role internal planning read denied');
reset role;
rollback;
