-- Isolated local clone only; every fixture and behavioral mutation rolls back.
begin;
set local lock_timeout='5s';set local statement_timeout='30s';
\ir project_pipeline_groups.fixture.sql
select set_config('request.jwt.claims','{"sub":"99999999-9999-4999-8999-999999999902","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.group_check(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end;$$;
create function pg_temp.group_error(command text,wanted text,label text) returns void language plpgsql as $$ begin begin execute command;exception when others then if sqlstate<>wanted then raise exception 'FAIL % expected %, got %: %',label,wanted,sqlstate,sqlerrm;end if;raise notice 'PASS %',label;return;end;raise exception 'FAIL % unexpectedly succeeded',label;end;$$;
do $$
declare org uuid:='99999999-9999-4999-8999-999999999901';actor uuid:='99999999-9999-4999-8999-999999999902';eng uuid:='99999999-9999-4999-8999-999999999975';webpreset uuid:='99999999-9999-4999-8999-999999997012';mktpreset uuid:='99999999-9999-4999-8999-999999997022';webdef uuid:='99999999-9999-4999-8999-999999997014';mktdef uuid:='99999999-9999-4999-8999-999999997024';op uuid:=gen_random_uuid();wg uuid;mg uuid;wconfig uuid;mconfig uuid;legacy uuid;wa uuid;ma uuid;result jsonb;impact jsonb;legacy_before jsonb;original_intent jsonb;intent_id uuid;name text:='Website '||gen_random_uuid()::text;
wsteps jsonb:='[{"key":"website_brief","quantity":1}]';msteps jsonb:='[{"key":"marketing_plan","quantity":1}]';
begin
 perform pg_temp.group_check(has_function_privilege('authenticated','public.create_project_pipeline_group(uuid,uuid,uuid,text,text,uuid)','EXECUTE') and not has_function_privilege('service_role','public.create_project_pipeline_group(uuid,uuid,uuid,text,text,uuid)','EXECUTE') and not has_function_privilege('anon','public.start_project_pipeline_group_run(uuid,uuid,uuid,uuid,uuid[])','EXECUTE'),'authenticated-only management/run APIs');
 perform pg_temp.group_check(not has_table_privilege('authenticated','public.project_pipeline_groups','INSERT') and not has_table_privilege('service_role','public.project_pipeline_groups','INSERT'),'no direct group writes');
 result:=public.create_project_pipeline_configuration(org,eng,webdef,gen_random_uuid(),wsteps,0);legacy:=(result->>'configuration_id')::uuid;
 impact:=public.preview_project_pipeline_activation(org,legacy);perform public.activate_project_pipeline_configuration(org,legacy,gen_random_uuid(),impact->>'impact_token_sha256',true);
 select to_jsonb(c) into legacy_before from public.project_pipeline_configurations c where id=legacy;
 result:=public.start_pipeline_run_intent(org,eng,gen_random_uuid());intent_id:=(result->>'run_intent_id')::uuid;select to_jsonb(i) into original_intent from public.pipeline_run_intents i where id=intent_id;
 result:=public.create_project_pipeline_group(org,eng,webpreset,'website',name,op);wg:=(result->'group'->>'id')::uuid;
 perform pg_temp.group_check((result->'group'->>'project_id')::uuid='99999999-9999-4999-8999-999999999974','server derives exact project');
 result:=public.create_project_pipeline_group(org,eng,webpreset,'website',name,op);perform pg_temp.group_check((result->>'idempotent_replay')::boolean and (result->'group'->>'id')::uuid=wg,'exact group creation replays once');
 perform pg_temp.group_error(format('select public.create_project_pipeline_group(%L,%L,%L,%L,%L,%L)',org,eng,webpreset,'marketing',name,op),'23505','changed group identity denied');
 perform pg_temp.group_error(format('update public.project_pipeline_groups set name=%L where id=%L','Mutated',wg),'55000','group identity immutable');
 result:=public.create_project_pipeline_group(org,eng,mktpreset,'marketing','Marketing '||gen_random_uuid()::text,gen_random_uuid());mg:=(result->'group'->>'id')::uuid;
 perform pg_temp.group_error(format('select public.create_project_pipeline_configuration(%L,%L,%L,%L,%L,0)',org,eng,mktdef,gen_random_uuid(),msteps),'42501','Legacy origin cannot silently adopt Marketing preset');
 perform pg_temp.group_error(format('select public.create_project_pipeline_group_configuration(%L,%L,%L,%L,%L,%L,0)',org,eng,mktdef,wg,gen_random_uuid(),msteps),'42501','cross-group published preset denied');
 result:=public.create_project_pipeline_group_configuration(org,eng,webdef,wg,gen_random_uuid(),wsteps,0);wconfig:=(result->>'configuration_id')::uuid;perform pg_temp.group_check((result->>'group_revision')::integer=1,'Website starts at group revision one');
 result:=public.create_project_pipeline_group_configuration(org,eng,mktdef,mg,gen_random_uuid(),msteps,0);mconfig:=(result->>'configuration_id')::uuid;perform pg_temp.group_check((result->>'group_revision')::integer=1,'Marketing starts at independent group revision one');
 impact:=public.preview_project_pipeline_activation(org,wconfig);perform pg_temp.group_check(impact->>'previous_configuration_id' is null and (impact->>'pipeline_group_id')::uuid=wg,'Website impact has no Legacy predecessor');result:=public.activate_project_pipeline_configuration(org,wconfig,gen_random_uuid(),impact->>'impact_token_sha256',true);wa:=(result->>'activation_id')::uuid;
 impact:=public.preview_project_pipeline_activation(org,mconfig);perform pg_temp.group_check(impact->>'previous_configuration_id' is null,'Marketing impact has no Website predecessor');result:=public.activate_project_pipeline_configuration(org,mconfig,gen_random_uuid(),impact->>'impact_token_sha256',true);ma:=(result->>'activation_id')::uuid;
 perform pg_temp.group_check(not exists(select 1 from public.project_pipeline_activations newer join public.project_pipeline_activations pinned on pinned.id=wa where newer.engagement_id=pinned.engagement_id and newer.pipeline_group_id is not distinct from pinned.pipeline_group_id and newer.activation_number>pinned.activation_number),'Marketing activation never supersedes Website');
 result:=public.start_project_pipeline_group_run(org,eng,gen_random_uuid(),wg);select to_jsonb(i) into result from public.pipeline_run_intents i where id=(result->>'run_intent_id')::uuid;
 perform pg_temp.group_check((result->>'project_activation_id')::uuid=wa and (result->>'pipeline_group_id')::uuid=wg and jsonb_array_length(result->'input_manifest'->'services')=1 and result->'input_manifest'->'services'->0->>'service_id'='99999999-9999-4999-8999-999999999976','Website run pins only Website activation and selected service');
 result:=public.start_project_pipeline_group_run(org,eng,gen_random_uuid(),mg);select to_jsonb(i) into result from public.pipeline_run_intents i where id=(result->>'run_intent_id')::uuid;
 perform pg_temp.group_check((result->>'project_activation_id')::uuid=ma and result->'input_manifest'->'services'->0->>'service_id'='99999999-9999-4999-8999-999999997001','Marketing run pins its independent source/service');
 perform pg_temp.group_check((select to_jsonb(c)=legacy_before from public.project_pipeline_configurations c where id=legacy) and (select to_jsonb(i)=original_intent from public.pipeline_run_intents i where id=intent_id),'Legacy configuration and historical run unchanged');
 result:=public.start_pipeline_run_intent(org,eng,gen_random_uuid());perform pg_temp.group_check((select a.pipeline_group_id is null from public.pipeline_run_intents i join public.project_pipeline_activations a on a.id=i.project_activation_id where i.id=(result->>'run_intent_id')::uuid),'Legacy callers still pin only Legacy');
 update public.engagement_services set status='on_hold' where id='99999999-9999-4999-8999-999999997002';
 perform pg_temp.group_error(format('select public.start_project_pipeline_group_run(%L,%L,%L,%L)',org,eng,gen_random_uuid(),mg),'42501','on-hold selected service denies group run');
 result:=public.start_project_pipeline_group_run(org,eng,gen_random_uuid(),wg);perform pg_temp.group_check(result->>'run_intent_id' is not null,'unrelated service pause does not block Website');
 update public.organization_memberships set status='revoked' where organization_id=org and user_id=actor;
 perform pg_temp.group_error(format('select public.create_project_pipeline_group(%L,%L,%L,%L,%L,%L)',org,eng,webpreset,'website','Revoked',gen_random_uuid()),'42501','revoked team cannot create group');
 update public.organization_memberships set status='active' where organization_id=org and user_id=actor;
 update public.organization_memberships set member_kind='client',role='client_viewer' where organization_id=org and user_id=actor;
 set local role authenticated;
 perform pg_temp.group_check((select count(*)=0 from public.project_pipeline_groups where organization_id=org),'client cannot read team pipeline groups');
 perform pg_temp.group_error(format('select public.create_project_pipeline_group(%L,%L,%L,%L,%L,%L)',org,eng,webpreset,'website','Client write',gen_random_uuid()),'42501','client cannot manage pipeline groups');
 reset role;
 update public.organization_memberships set member_kind='team',role='operations_admin' where organization_id=org and user_id=actor;
 result:=private.build_living_project_snapshot_projection(org,'99999999-9999-4999-8999-999999999974','internal',1,now());
 select item into result from jsonb_array_elements(result->'supplemental'->'engagements') item where item->>'id'=eng::text;
 perform pg_temp.group_check(result->'active_configuration'->>'id'=legacy::text,'living Legacy projection never adopts a group activation');
 perform pg_temp.group_check(exists(select 1 from jsonb_array_elements(result->'pipeline_groups') g where g->>'id'=wg::text and g->'active_configuration'->>'id'=wconfig::text) and exists(select 1 from jsonb_array_elements(result->'pipeline_groups') g where g->>'id'=mg::text and g->'active_configuration'->>'id'=mconfig::text),'living projection records each exact independently active pipeline');
 result:=private.build_living_project_snapshot_projection(org,'99999999-9999-4999-8999-999999999974','client',1,now());
 perform pg_temp.group_check(not (result ? 'supplemental'),'client projection does not acquire internal pipeline source records');
 update public.projects set archived_at=now() where id='99999999-9999-4999-8999-999999999974';
 perform pg_temp.group_error(format('select public.start_project_pipeline_group_run(%L,%L,%L,%L)',org,eng,gen_random_uuid(),wg),'42501','archived project denies group run');
end;$$;
rollback;
