-- Rollback-only manual evidence; existing synthetic actor/page/source, no users/provider calls.
begin;set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';actor uuid:='99999999-9999-4999-8999-999999999902';version uuid:='99999999-9999-4999-8999-999999997141';page public.project_website_pages%rowtype;rev public.project_website_page_revisions%rowtype;link public.project_website_page_seo_links%rowtype;evidence jsonb:=jsonb_build_object('indexed',null,'schema_valid',false,'mobile_score',0,'desktop_score',null,'notes','Rollback-only manually inspected schema finding','evidence_url',null,'findings',jsonb_build_array(jsonb_build_object('category','schema','severity','warning','description','Missing structured data','evidence','Manual inspector note')));checked timestamptz:=clock_timestamp();review jsonb;saved jsonb;j jsonb;count_before bigint;count_after bigint;request uuid:='99999999-9999-4999-8999-999999997280';stale jsonb;begin
 select * into page from public.project_website_pages where organization_id=org and project_id=project and page_key='page:1';if not found then raise exception 'Verified AD1 synthetic page absent';end if;
 select count(*) into count_before from public.project_website_version_checks;
 review:=public.preview_project_website_version_check(org,project,page.id,version,checked,evidence);
 perform pg_temp.check_true((select count(*) from public.project_website_version_checks)=count_before and review->>'provider_request_made'='false','Manual review writes zero records and makes no provider request');
 perform pg_temp.check_true(review#>>'{scope_snapshot,page_id}'=page.id::text and review#>>'{scope_snapshot,architecture_version_id}'=version::text and review#>>'{scope_snapshot,reference,approval_id}' is not null,'Exact approved source/page/implementation/link snapshot is review-bound');
 saved:=public.confirm_project_website_version_check(org,project,page.id,version,checked,evidence,review->>'review_sha256',request);
 perform pg_temp.check_true((select count(*) from public.project_website_version_checks)=count_before+1 and saved#>>'{check,created_by}'=actor::text and saved->>'source_type'='manual','One immutable manual check records original actor and observation time');
 perform pg_temp.check_true(saved#>'{check,evidence,indexed}'='null'::jsonb and saved#>>'{check,evidence,schema_valid}'='false' and saved#>>'{check,evidence,mobile_score}'='0','Manual zero false and unknown retain distinct original values');
 j:=public.confirm_project_website_version_check(org,project,page.id,version,checked,evidence,review->>'review_sha256',request);
 perform pg_temp.check_true(j->>'idempotent_replay'='true' and j#>>'{check,id}'=saved#>>'{check,id}' and (select count(*) from public.project_website_version_checks)=count_before+1,'Same actor UUID and exact payload replays one original receipt');
 perform pg_temp.check_true(public.get_project_website_version_check_operation(org,project,request)=saved,'Original UUID recovery reads exact original receipt');
 perform pg_temp.check_true(public.get_project_website_version_check_operation(org,project,'99999999-9999-4999-8999-999999997289') is null,'Unknown UUID never guesses current history');
 perform pg_temp.expect_error(format('select public.confirm_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb,%L,%L)',org,project,page.id,version,checked,evidence||jsonb_build_object('notes','Changed'),review->>'review_sha256',request),'23505','UUID payload conflict rejected without another check');
 perform pg_temp.expect_error(format('select public.confirm_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb,%L,%L)',org,project,page.id,version,checked,evidence,repeat('a',64),'99999999-9999-4999-8999-999999997281'),'40001','Confirmation cannot bypass exact zero-write review');
 j:=public.list_project_website_version_checks(org,project,page.id,version,'Rollback-only',0,1);
 perform pg_temp.check_true(j->>'matching'='1' and jsonb_array_length(j->'items')=1 and j#>>'{items,0,provider_verified}'='false','Bounded filtered history exposes manual evidence without provider verification');
 perform pg_temp.check_true(j#>>'{items,0,state}'='current_manual_evidence','Matching current page snapshot has current manual evidence without automatic acceptance');
 j:=public.list_project_website_version_checks(org,project,page.id,'99999999-9999-4999-8999-999999997143');
 perform pg_temp.check_true(j#>'{items,0,recheck_reasons}' ? 'architecture_version_changed','Different approved architecture version requires recheck and retains old source');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,'99999999-9999-4999-8999-999999997145',checked,evidence),'42501','Unapproved exact architecture cannot create a check');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,'99999999-9999-4999-8999-999999997147',checked,evidence),'42501','Different source root cannot borrow page identity');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,clock_timestamp()+interval '1 day',evidence),'22023','Future observations rejected');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence||jsonb_build_object('provider_verified',true)),'22023','Unrecognized provider/approval claims rejected');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence||jsonb_build_object('mobile_score',101)),'22023','Out of range score rejected');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence||jsonb_build_object('evidence_url','javascript:bad')),'22023','Unsafe evidence URL rejected');
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence||jsonb_build_object('notes','','findings',jsonb_build_array())),'22023','Empty evidence cannot imply inspection');
 perform pg_temp.expect_error(format('select public.list_project_website_version_checks(%L,%L,%L,%L,%L,0,51)',org,project,page.id,version,''),'22023','Unbounded check history rejected');
 perform pg_temp.expect_error(format('update public.project_website_version_checks set checked_at=now() where id=%L',saved#>>'{check,id}'),'55000','Saved manual check cannot be rewritten even by native owner');
 perform pg_temp.expect_error(format('delete from public.project_website_check_commands where request_id=%L',request),'55000','Original immutable receipt cannot be removed');
 stale:=public.preview_project_website_version_check(org,project,page.id,version,checked,evidence);
 select * into rev from public.project_website_page_revisions where page_id=page.id order by revision_number desc limit 1;
 insert into public.project_website_page_revisions(organization_id,project_id,page_id,revision_number,architecture_artifact_id,architecture_version_id,architecture_approval_id,architecture_checksum,planned_path,planned_url,recorded_live_url,redirect_url,publication_state,template,work_item_id,implementation_notes,qa_evidence,created_by)
 values(rev.organization_id,rev.project_id,rev.page_id,rev.revision_number+1,rev.architecture_artifact_id,rev.architecture_version_id,rev.architecture_approval_id,rev.architecture_checksum,rev.planned_path,rev.planned_url,rev.recorded_live_url,rev.redirect_url,rev.publication_state,rev.template,rev.work_item_id,'Rollback-only later implementation',rev.qa_evidence,actor);
 perform pg_temp.expect_error(format('select public.confirm_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb,%L,%L)',org,project,page.id,version,checked,evidence,stale->>'review_sha256','99999999-9999-4999-8999-999999997282'),'40001','Implementation change invalidates a retained confirmation');
 j:=public.list_project_website_version_checks(org,project,page.id,version);
 perform pg_temp.check_true(j#>'{items,0,recheck_reasons}' ? 'implementation_changed','Later implementation marks old check for recheck without changing its evidence');
 review:=public.preview_project_website_version_check(org,project,page.id,version,'2000-01-01',evidence);
 j:=public.confirm_project_website_version_check(org,project,page.id,version,'2000-01-01',evidence,review->>'review_sha256','99999999-9999-4999-8999-999999997283');
 j:=public.list_project_website_version_checks(org,project,page.id,version);
 perform pg_temp.check_true(j#>'{items,0,recheck_reasons}' ? 'observation_predates_current_state','Backdated manual evidence remains stale for newer page state');
 select * into link from public.project_website_page_seo_links where page_id=page.id order by link_number desc limit 1;
 insert into public.project_website_page_seo_links(organization_id,project_id,brand_id,page_id,link_number,tracked_page_id,architecture_artifact_id,architecture_version_id,architecture_approval_id,architecture_checksum,created_by)
 select org,project,page.brand_id,page.id,coalesce(link.link_number,0)+1,'99999999-9999-4999-8999-999999997150',page.architecture_artifact_id,version,page.initial_approval_id,v.content_checksum,actor from public.artifact_versions v where v.id=version;
 j:=public.list_project_website_version_checks(org,project,page.id,version);
 perform pg_temp.check_true(j#>'{items,0,recheck_reasons}' ? 'seo_link_changed','Explicit SEO link event changes invalidate earlier check scope');
 update public.engagements set status='on_hold' where id=page.engagement_id;
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence),'42501','Withdrawn current source cannot authorize new evidence');
 j:=public.list_project_website_version_checks(org,project,page.id,version);
 perform pg_temp.check_true(j->>'source_state'='approved_source_unavailable' and j#>>'{items,0,state}'='recheck_required','Withdrawn source leaves immutable history readable with explicit recheck');
 update public.engagements set status='active' where id=page.engagement_id;
 update public.organization_memberships set role='contributor' where organization_id=org and user_id=actor;
 perform pg_temp.expect_error(format('select public.preview_project_website_version_check(%L,%L,%L,%L,%L,%L::jsonb)',org,project,page.id,version,checked,evidence),'42501','Current team contributor lacks project/operations check writer authority');
 perform pg_temp.check_true(public.get_project_website_version_check_operation(org,project,request)=saved,'Own historical receipt stays recoverable after writer authority removal');
 perform set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999997299',true);
 perform pg_temp.expect_error(format('select public.list_project_website_version_checks(%L,%L,%L,%L)',org,project,page.id,version),'42501','Unknown actor cannot read exact project checks');
end $$;
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
update public.organization_memberships set role='operations_admin' where organization_id='99999999-9999-4999-8999-999999999901' and user_id='99999999-9999-4999-8999-999999999902';
set local role authenticated;
do $$declare page uuid;review jsonb;saved jsonb;checked timestamptz:=clock_timestamp();evidence jsonb:=jsonb_build_object('indexed',null,'schema_valid',false,'mobile_score',0,'desktop_score',null,'notes','Authenticated manual transport evidence','evidence_url',null,'findings',jsonb_build_array());begin
select id into page from public.project_website_pages where organization_id='99999999-9999-4999-8999-999999999901' and project_id='99999999-9999-4999-8999-999999999974' and page_key='page:1';
review:=public.preview_project_website_version_check('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',page,'99999999-9999-4999-8999-999999997141',checked,evidence);
perform pg_temp.check_true(review->>'source_type'='manual','Authenticated project writer can review exact manual evidence');
saved:=public.confirm_project_website_version_check('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',page,'99999999-9999-4999-8999-999999997141',checked,evidence,review->>'review_sha256','99999999-9999-4999-8999-999999997287');
perform pg_temp.check_true(public.get_project_website_version_check_operation('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974','99999999-9999-4999-8999-999999997287')=saved,'Authenticated writer confirms and recovers one own immutable receipt through API');
end $$;

select pg_temp.expect_error('select * from public.project_website_version_checks','42501','Authenticated direct check table access denied');
select pg_temp.expect_error('select private.website_check_snapshot(null,null,null,null)','42501','Private snapshot helper inaccessible to authenticated');
reset role;
set local role anon;
select pg_temp.expect_error('select public.list_project_website_version_checks(null,null,null,null)','42501','Anonymous public check API inaccessible');
reset role;set local role service_role;
select pg_temp.expect_error('select * from public.project_website_check_commands','42501','Service-role direct receipt access denied');
select pg_temp.expect_error('select public.preview_project_website_version_check(null,null,null,null,null,null)','42501','Service-role public writer inaccessible');
reset role;
rollback;
