begin;
set local lock_timeout='5s';set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
insert into public.integration_connections(id,organization_id,provider,display_name,status,public_config,created_by) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','google_analytics','B6 synthetic local reporting','verified','{"property_id":"123456"}','99999999-9999-4999-8999-999999999902');
insert into public.integration_connection_engagements(connection_id,organization_id,engagement_id,department_id,created_by) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999975','marketing','99999999-9999-4999-8999-999999999902');
insert into public.integration_oauth_credentials(connection_id,organization_id,provider,access_token_ciphertext,access_token_iv,refresh_token_ciphertext,refresh_token_iv,granted_scopes,access_token_expires_at) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','google_analytics','local-metadata-only','local-metadata-only','local-metadata-only','local-metadata-only',array['https://www.googleapis.com/auth/analytics.readonly'],now()+interval '1 hour');
do $$declare input jsonb:='{"binding_id":null,"expected_revision":0,"engagement_id":"99999999-9999-4999-8999-999999999975","department_id":"marketing","connection_id":"99999999-9999-4999-8999-999999997610","resource_kind":"ga4_property","resource_key":"123456","permitted_operations":["reporting_read"],"state":"enabled"}';v jsonb;s jsonb;begin
 v:=public.preview_project_reporting_binding('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',input);
 s:=public.confirm_project_reporting_binding('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',input,v->>'review_sha256','99999999-9999-4999-8999-999999997611');
 perform set_config('anka.b6binding',s->>'binding_id',true);
end $$;

select set_config('request.jwt.claim.role','authenticated',true);
do $$declare r public.project_reporting_binding_revisions%rowtype;input jsonb;begin
 select * into r from public.project_reporting_binding_revisions where binding_id=current_setting('anka.b6binding')::uuid;
 input:=jsonb_build_object('source_contract','local-adapter-only','reporting_time_zone','UTC','limits','{"cadence_seconds":3600,"history_days":30,"stale_after_seconds":7200,"manual_min_interval_seconds":60,"daily_request_limit":2,"backoff_seconds":1,"max_backoff_seconds":2,"max_period_days":7,"max_observations":25,"lease_seconds":60}'::jsonb,'enabled',true,'binding_revision_number',r.revision_number,'context_checksum',r.context_checksum);
 perform set_config('anka.refreshinput',input::text,true);
end $$;

select set_config('anka.refreshpolicy',(public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,0,current_setting('anka.refreshinput')::jsonb,gen_random_uuid())->>'policy_id'),true);
select pg_temp.check_true(public.get_project_stored_reporting_status('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid)->>'current_authorized'='false','Policy alone never exposes metric values');
insert into private.reporting_refresh_adapters values('local-adapter-only','google_analytics','ga4_property',repeat('a',64),'[{"metric_key":"fixture_clicks","metric_label":"Fixture clicks","unit":"count","aggregation":"additive"}]',true);
select set_config('anka.challenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.challenge')::uuid);
select set_config('anka.claim',gen_random_uuid()::text,true);
create function pg_temp.claim() returns jsonb language sql as $$select public.claim_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)$$;
create function pg_temp.complete() returns jsonb language sql as $$select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('a',64),current_setting('anka.observed')::timestamptz,true,true,repeat('b',64))$$;
set local role authenticated;
select pg_temp.expect_error('select pg_temp.claim()','42501','Authenticated cannot claim provider verification');
select pg_temp.expect_error('select * from private.reporting_verification_attempts','42501','Authenticated has no direct attempt access');
select pg_temp.check_true(public.get_project_reporting_verification_operation('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.challenge')::uuid)->>'state'='unclaimed','Original actor can recover prepared challenge without dispatch');
reset role;
select set_config('request.jwt.claim.role','service_role',true);
set local role service_role;
select pg_temp.expect_error($q$select public.record_project_reporting_verification(current_setting('anka.challenge')::uuid,repeat('a',64),clock_timestamp(),true,true,repeat('b',64))$q$,'42501','Service cannot bypass one-use wrapper via old recorder');
select pg_temp.expect_error('select * from private.reporting_verification_attempts','42501','Service has no direct attempt write/read grant');
select set_config('anka.observed',clock_timestamp()::text,true);
select pg_temp.expect_error('select pg_temp.complete()','42501','Completion without an original claim denied');
reset role;
savepoint before_claim;
update public.organization_memberships set status='revoked' where organization_id='99999999-9999-4999-8999-999999999901' and user_id='99999999-9999-4999-8999-999999999902';
select pg_temp.expect_error('select pg_temp.claim()','42501','Original administrator revocation prevents dispatch');
rollback to before_claim;
update public.integration_connection_engagements set created_at=created_at+interval '1 second' where connection_id='99999999-9999-4999-8999-999999997610';
select pg_temp.expect_error('select pg_temp.claim()','42501','Mapping revision drift prevents dispatch');
rollback to before_claim;
update private.reporting_refresh_adapters set enabled=false where source_contract='local-adapter-only';
select pg_temp.expect_error('select pg_temp.claim()','42501','Disabled original adapter prevents dispatch');
rollback to before_claim;
select public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,1,current_setting('anka.refreshinput')::jsonb,gen_random_uuid());
select pg_temp.expect_error('select pg_temp.claim()','40001','Replaced policy prevents old challenge dispatch');
rollback to before_claim;
set local role service_role;
select pg_temp.check_true(pg_temp.claim()->>'dispatch_authorized'='true','First original claim grants one dispatch');
select pg_temp.check_true(pg_temp.claim()->>'dispatch_authorized'='false','Same claim replay grants no dispatch');
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.challenge')::uuid,gen_random_uuid())->>'dispatch_authorized'='false','Competing claim grants no second dispatch');
select pg_temp.check_true(public.get_project_reporting_verification_claim(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)->>'state'='claimed','Lost claim acknowledgement recovers state only');
select pg_temp.check_true(public.get_project_reporting_verification_claim(current_setting('anka.challenge')::uuid,gen_random_uuid())->>'state'='not_found','Different claim cannot recover original proof');
select pg_temp.expect_error('select pg_temp.complete()','22023','Observation predating original dispatch denied');
select set_config('anka.observed',clock_timestamp()::text,true);
select pg_temp.expect_error($q$select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('c',64),current_setting('anka.observed')::timestamptz,true,true,repeat('b',64))$q$,'22023','Changed manifest denied');
reset role;
savepoint claimed;
update public.organization_memberships set status='revoked' where organization_id='99999999-9999-4999-8999-999999999901' and user_id='99999999-9999-4999-8999-999999999902';
select pg_temp.expect_error('select pg_temp.complete()','42501','Administrator revoked during provider read blocks completion');
select pg_temp.check_true(public.get_project_reporting_verification_claim(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)->>'dispatch_authorized'='false','Worker audit recovery after revocation grants no redispatch');
rollback to claimed;
set local role service_role;
select pg_temp.check_true(pg_temp.complete()->>'resource_verified'='true','Exact original observed proof accepted');
select pg_temp.check_true(pg_temp.complete()->>'replayed'='true','Same original completion recovers exact receipt');
select pg_temp.expect_error($q$select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('a',64),current_setting('anka.observed')::timestamptz,false,true,repeat('b',64))$q$,'23505','Changed original proof denied');
select pg_temp.check_true(public.get_project_reporting_verification_claim(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)#>>'{original_result,resource_verified}'='true','Lost completion acknowledgement recovers original positive receipt');
reset role;
select pg_temp.expect_error($q$update private.reporting_verification_attempts set claimed_at=clock_timestamp() where challenge_id=current_setting('anka.challenge')::uuid$q$,'55000','Original dispatch audit immutable');
select set_config('anka.refreshjob',(public.request_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,timezone('UTC',clock_timestamp())::date,timezone('UTC',clock_timestamp())::date,gen_random_uuid())->>'job_id'),true);
select pg_temp.check_true(public.claim_project_reporting_refresh(current_setting('anka.refreshjob')::uuid,gen_random_uuid())->>'dispatch_authorized'='true','Refresh consumes second shared quota slot');
select set_config('anka.secondchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.secondchallenge')::uuid);
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.secondchallenge')::uuid,gen_random_uuid())->>'blocked_reason'='rolling_day_quota_exhausted','Verification includes refresh attempts in shared quota');
-- Alternate ordering: verification uses both slots, and queued refresh remains undispatched.
rollback to claimed;
select pg_temp.complete();
select set_config('anka.secondchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.secondchallenge')::uuid);
select set_config('anka.secondclaim',gen_random_uuid()::text,true);
select public.claim_project_reporting_verification(current_setting('anka.secondchallenge')::uuid,current_setting('anka.secondclaim')::uuid);
select public.complete_project_reporting_verification(current_setting('anka.secondchallenge')::uuid,current_setting('anka.secondclaim')::uuid,repeat('a',64),clock_timestamp(),true,true,repeat('b',64));
select set_config('anka.refreshjob',(public.request_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,timezone('UTC',clock_timestamp())::date,timezone('UTC',clock_timestamp())::date,gen_random_uuid())->>'job_id'),true);
select pg_temp.check_true(public.claim_project_reporting_refresh(current_setting('anka.refreshjob')::uuid,gen_random_uuid())->>'reason'='rolling_day_quota_exhausted','Refresh includes verification attempts in shared quota');
select pg_temp.check_true((select attempt_number=0 and next_attempt_at>clock_timestamp() from private.reporting_refresh_jobs where id=current_setting('anka.refreshjob')::uuid),'Quota denial creates no attempt and sets bounded next eligibility');
rollback to claimed;
select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('a',64),current_setting('anka.observed')::timestamptz,false,false,repeat('b',64));
select pg_temp.check_true(public.get_project_reporting_verification_claim(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)#>>'{original_result,resource_verified}'='false','Actual observed negative retained as negative proof');
select set_config('request.jwt.claim.role','authenticated',true);
set local role authenticated;
select pg_temp.check_true(public.get_project_reporting_verification_operation('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.challenge')::uuid)->>'state'='completed','Original actor recovers historical completion separately from current access');
reset role;
set local role anon;
select pg_temp.expect_error($q$select public.get_project_reporting_verification_operation(null,null,null)$q$,'42501','Anonymous recovery denied');
reset role;
select set_config('request.jwt.claim.role','service_role',true);
select set_config('anka.expired',gen_random_uuid()::text,true);
insert into private.reporting_verification_challenges select (jsonb_populate_record(null::private.reporting_verification_challenges,(select to_jsonb(q)||jsonb_build_object('id',current_setting('anka.expired'),'created_at',clock_timestamp()-interval '2 minutes','expires_at',clock_timestamp()-interval '1 minute') from private.reporting_verification_challenges q where q.id=current_setting('anka.challenge')::uuid))).*;
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.expired')::uuid,gen_random_uuid())->>'state'='expired','Expired original challenge cannot dispatch');
insert into private.reporting_verification_attempts(challenge_id,claim_id,binding_id,claimed_at,lease_expires_at) values(current_setting('anka.expired')::uuid,gen_random_uuid(),current_setting('anka.b6binding')::uuid,clock_timestamp()-interval '90 seconds',clock_timestamp()-interval '1 minute');
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.expired')::uuid,gen_random_uuid())->>'state'='uncertain','Expired original attempt remains uncertain and cannot be reclaimed');
rollback;
