begin;
set local lock_timeout='5s';set local statement_timeout='90s';
select set_config('request.jwt.claim.sub','99999999-9999-4999-8999-999999999902',true);
create function pg_temp.check_true(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL %',label;end if;raise notice 'PASS %',label;end $$;
create function pg_temp.expect_error(query text,code text,label text) returns void language plpgsql as $$begin begin execute query;exception when others then if sqlstate=code then raise notice 'PASS %',label;return;end if;raise exception 'FAIL % expected % got %: %',label,code,sqlstate,sqlerrm;end;raise exception 'FAIL % did not reject',label;end $$;
insert into public.integration_connections(id,organization_id,provider,display_name,status,public_config,created_by) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','google_analytics','B6 HTTP accounting rollback only','verified','{"property_id":"123456"}','99999999-9999-4999-8999-999999999902');
insert into public.integration_connection_engagements(connection_id,organization_id,engagement_id,department_id,created_by) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999975','marketing','99999999-9999-4999-8999-999999999902');
insert into public.integration_oauth_credentials(connection_id,organization_id,provider,access_token_ciphertext,access_token_iv,refresh_token_ciphertext,refresh_token_iv,granted_scopes,access_token_expires_at) values('99999999-9999-4999-8999-999999997610','99999999-9999-4999-8999-999999999901','google_analytics','local-metadata-only','local-metadata-only','local-metadata-only','local-metadata-only',array['https://www.googleapis.com/auth/analytics.readonly'],now()+interval '1 hour');
do $$declare input jsonb:='{"binding_id":null,"expected_revision":0,"engagement_id":"99999999-9999-4999-8999-999999999975","department_id":"marketing","connection_id":"99999999-9999-4999-8999-999999997610","resource_kind":"ga4_property","resource_key":"123456","permitted_operations":["reporting_read"],"state":"enabled"}';v jsonb;s jsonb;begin
 v:=public.preview_project_reporting_binding('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',input);
 s:=public.confirm_project_reporting_binding('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',input,v->>'review_sha256','99999999-9999-4999-8999-999999997611');
 perform set_config('anka.b6binding',s->>'binding_id',true);
end $$;

select set_config('request.jwt.claim.role','authenticated',true);
do $$declare r public.project_reporting_binding_revisions%rowtype;input jsonb;begin
 select * into r from public.project_reporting_binding_revisions where binding_id=current_setting('anka.b6binding')::uuid;
 input:=jsonb_build_object('source_contract','local-adapter-only','reporting_time_zone','UTC','limits','{"cadence_seconds":3600,"history_days":30,"stale_after_seconds":7200,"manual_min_interval_seconds":60,"daily_request_limit":2,"backoff_seconds":1,"max_backoff_seconds":2,"max_period_days":7,"max_observations":25,"lease_seconds":60}'::jsonb,'enabled',true,'binding_revision_number',r.revision_number,'context_checksum',r.context_checksum);
 perform set_config('anka.refreshinput',input::text,true);
end $$;

select set_config('anka.refreshpolicy',(public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,0,current_setting('anka.refreshinput')::jsonb,gen_random_uuid())->>'policy_id'),true);
select pg_temp.check_true(public.get_project_stored_reporting_status('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid)->>'current_authorized'='false','Policy alone never exposes metric values');
insert into private.reporting_refresh_adapters values('local-adapter-only','google_analytics','ga4_property',repeat('a',64),'[{"metric_key":"fixture_clicks","metric_label":"Fixture clicks","unit":"count","aggregation":"additive"}]',true);
select set_config('anka.challenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.challenge')::uuid);
select set_config('anka.claim',gen_random_uuid()::text,true);
create function pg_temp.claim() returns jsonb language sql as $$select public.claim_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)$$;
create function pg_temp.complete() returns jsonb language sql as $$select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('a',64),current_setting('anka.observed')::timestamptz,true,true,repeat('b',64))$$;

savepoint before_cost;
insert into private.reporting_http_costs values('local-adapter-only',repeat('a',64),2);
savepoint original;
select set_config('request.jwt.claim.role','authenticated',true);
set local role authenticated;
select pg_temp.expect_error('select * from private.reporting_http_reservations','42501','Authenticated cannot read reservations');
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,1,gen_random_uuid())$q$,'42501','Authenticated cannot issue HTTP permits');
reset role;
select set_config('request.jwt.claim.role','service_role',true);
set local role service_role;
select pg_temp.expect_error('select * from private.reporting_http_costs','42501','Service cannot read or supply adapter cost');
select pg_temp.expect_error('select * from private.reporting_http_permits','42501','Service cannot directly access permits');
select pg_temp.expect_error('select * from private.reporting_http_outcomes','42501','Service cannot directly access outcomes');
select pg_temp.check_true(pg_temp.claim()#>>'{context,provider_http_claim,request_budget}'='2','Original claim reserves exact two requests before any permit');
select pg_temp.check_true(pg_temp.claim()->>'dispatch_authorized'='false','Same original claim never redispatches');
select pg_temp.check_true(public.get_project_reporting_http_claim('verification',current_setting('anka.claim')::uuid)->>'dispatch_authorized'='false','Lost claim is recovered read-only');
select set_config('anka.observed',clock_timestamp()::text,true);
select pg_temp.expect_error('select pg_temp.complete()','42501','Positive receipt requires actual request evidence');
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Second call before validated first proof denied');
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,3,gen_random_uuid())$q$,'22023','Caller cannot expand request budget');
select set_config('anka.permit1',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,1,current_setting('anka.permit1')::uuid)->>'dispatch_authorized'='true','Original first permit dispatches once');
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,1,current_setting('anka.permit1')::uuid)->>'dispatch_authorized'='false','Repeated permit never redispatches');
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,1,gen_random_uuid())->>'dispatch_authorized'='false','Different UUID cannot repeat ordinal');
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,current_setting('anka.permit1')::uuid)$q$,'42501','Permit UUID cannot move to another ordinal');
reset role;
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,clock_timestamp())=2,'Both reserved units count even before first response');
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,(select claimed_at+interval '24 hours' from private.reporting_http_reservations where claim_id=current_setting('anka.claim')::uuid))=0,'Exact rolling-day boundary excludes original reservation');
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,(select claimed_at+interval '24 hours'-interval '1 microsecond' from private.reporting_http_reservations where claim_id=current_setting('anka.claim')::uuid))=2,'Immediately before rolling-day boundary counts both units');
savepoint first_permit;
select public.record_project_reporting_http_outcome(current_setting('anka.permit1')::uuid,'denied',repeat('b',64),null);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Observed call1 denial prevents call2');
select pg_temp.expect_error('select pg_temp.complete()','42501','Observed denial cannot become positive verification');
select pg_temp.check_true(public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,repeat('a',64),clock_timestamp(),false,false,repeat('b',64))->>'resource_verified'='false','Exact original denied proof completes negatively');
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,clock_timestamp())=2,'Known first denial does not speculate a quota refund');
rollback to first_permit;
select public.record_project_reporting_http_outcome(current_setting('anka.permit1')::uuid,'uncertain',repeat('b',64),null);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Uncertain first call prevents second and repeats');
select pg_temp.check_true(public.get_project_reporting_http_claim('verification',current_setting('anka.claim')::uuid)#>>'{requests,0,outcome}'='uncertain','Transport uncertainty retains original ordinal audit');
rollback to first_permit;
select public.record_project_reporting_http_outcome(current_setting('anka.permit1')::uuid,'validated',repeat('b',64),clock_timestamp()+interval '1 minute');
select pg_temp.check_true(public.record_project_reporting_http_outcome(current_setting('anka.permit1')::uuid,'validated',repeat('b',64),(select valid_until from private.reporting_http_outcomes where permit_id=current_setting('anka.permit1')::uuid))->>'dispatch_authorized'='false','Exact outcome replay is read-only');
select pg_temp.expect_error($q$select public.record_project_reporting_http_outcome(current_setting('anka.permit1')::uuid,'denied',repeat('c',64),null)$q$,'23505','Changed original outcome rejected');
savepoint validated;
update public.organization_memberships set status='revoked' where organization_id='99999999-9999-4999-8999-999999999901' and user_id='99999999-9999-4999-8999-999999999902';
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())$q$,'42501','Revocation between calls prevents second dispatch');
rollback to validated;
update public.integration_connection_engagements set created_at=created_at+interval '1 second' where connection_id='99999999-9999-4999-8999-999999997610';
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())$q$,'42501','Mapping change between calls prevents second dispatch');
rollback to validated;
update private.reporting_refresh_adapters set enabled=false where source_contract='local-adapter-only';
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())$q$,'42501','Disabled adapter prevents second dispatch');
rollback to validated;
select public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,1,current_setting('anka.refreshinput')::jsonb,gen_random_uuid());
select pg_temp.expect_error($q$select public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())$q$,'40001','Revised policy invalidates the pending second request');
rollback to validated;
select set_config('anka.permit2',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,current_setting('anka.permit2')::uuid)->>'dispatch_authorized'='true','Validated current proof allows original second permit');
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.claim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Second ordinal cannot repeat after unknown acknowledgement');
select public.record_project_reporting_http_outcome(current_setting('anka.permit2')::uuid,'validated',repeat('b',64),null);
select pg_temp.check_true(pg_temp.complete()->>'resource_verified'='true','Both exact validated request outcomes complete original verification');
select pg_temp.expect_error($q$update private.reporting_http_permits set permitted_at=clock_timestamp() where permit_id=current_setting('anka.permit1')::uuid$q$,'55000','HTTP permit audit immutable');
select pg_temp.expect_error($q$update private.reporting_http_outcomes set outcome='denied' where permit_id=current_setting('anka.permit1')::uuid$q$,'55000','HTTP outcome audit immutable');
select set_config('anka.nextchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.nextchallenge')::uuid);
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.nextchallenge')::uuid,gen_random_uuid())->>'blocked_reason'='rolling_day_quota_exhausted','Another two-call claim cannot overbook reserved allowance');
select set_config('anka.job',(public.request_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,timezone('UTC',clock_timestamp())::date,timezone('UTC',clock_timestamp())::date,gen_random_uuid())->>'job_id'),true);
select pg_temp.check_true(public.claim_project_reporting_refresh(current_setting('anka.job')::uuid,gen_random_uuid())->>'reason'='rolling_day_quota_exhausted','Refresh admission sees two reserved verification requests');
rollback to original;
select set_config('request.jwt.claim.role','service_role',true);
select set_config('anka.fourpolicy',(public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,1,jsonb_set(current_setting('anka.refreshinput')::jsonb,'{limits,daily_request_limit}','4'),gen_random_uuid())->>'policy_id'),true);
select set_config('anka.fourchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.fourpolicy')::uuid,current_setting('anka.fourchallenge')::uuid);
select set_config('anka.fourclaim',gen_random_uuid()::text,true);
select public.claim_project_reporting_verification(current_setting('anka.fourchallenge')::uuid,current_setting('anka.fourclaim')::uuid);
select set_config('anka.fourpermit1',gen_random_uuid()::text,true);
select public.claim_project_reporting_http_request('verification',current_setting('anka.fourclaim')::uuid,1,current_setting('anka.fourpermit1')::uuid);
select public.record_project_reporting_http_outcome(current_setting('anka.fourpermit1')::uuid,'validated',repeat('b',64),clock_timestamp()+interval '1 minute');
select set_config('anka.fourpermit2',gen_random_uuid()::text,true);
select public.claim_project_reporting_http_request('verification',current_setting('anka.fourclaim')::uuid,2,current_setting('anka.fourpermit2')::uuid);
select public.record_project_reporting_http_outcome(current_setting('anka.fourpermit2')::uuid,'validated',repeat('b',64),null);
select public.complete_project_reporting_verification(current_setting('anka.fourchallenge')::uuid,current_setting('anka.fourclaim')::uuid,repeat('a',64),clock_timestamp(),true,true,repeat('b',64));
select set_config('anka.fourjob',(public.request_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.fourpolicy')::uuid,timezone('UTC',clock_timestamp())::date,timezone('UTC',clock_timestamp())::date,gen_random_uuid())->>'job_id'),true);
select set_config('anka.refreshclaim',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_refresh(current_setting('anka.fourjob')::uuid,current_setting('anka.refreshclaim')::uuid)#>>'{context,provider_http_claim,request_budget}'='2','Refresh pins original challenge manifest and reserves remaining two slots');
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,clock_timestamp())=4,'Verification and refresh reserve four HTTP units for two jobs');
select set_config('anka.page',jsonb_build_object('source_contract','local-adapter-only','resource_key','123456','period_start',timezone('UTC',clock_timestamp())::date::text,'period_end',timezone('UTC',clock_timestamp())::date::text,'reporting_time_zone','UTC','cursor',null,'next_cursor',null,'complete',true,'retrieved_at',to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'observations','[]'::jsonb)::text,true);
select pg_temp.expect_error($q$select public.commit_project_reporting_refresh_page(current_setting('anka.fourjob')::uuid,current_setting('anka.refreshclaim')::uuid,current_setting('anka.page')::jsonb)$q$,'42501','Ingestion cannot bypass per-request evidence');
select set_config('anka.refreshpermit1',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_http_request('refresh',current_setting('anka.refreshclaim')::uuid,1,current_setting('anka.refreshpermit1')::uuid)->>'dispatch_authorized'='true','Refresh first HTTP permit uses the original claim');
select public.record_project_reporting_http_outcome(current_setting('anka.refreshpermit1')::uuid,'validated',repeat('b',64),clock_timestamp()+interval '1 minute');
savepoint refresh_first;
select public.fail_project_reporting_refresh(current_setting('anka.fourjob')::uuid,current_setting('anka.refreshclaim')::uuid,'uncertain',null);
select pg_temp.check_true(public.claim_project_reporting_http_request('refresh',current_setting('anka.refreshclaim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Uncertain original job cannot acquire another HTTP permit');
rollback to refresh_first;
select set_config('anka.refreshpermit2',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_http_request('refresh',current_setting('anka.refreshclaim')::uuid,2,current_setting('anka.refreshpermit2')::uuid)->>'dispatch_authorized'='true','Validated first refresh response permits second HTTP once');
select public.record_project_reporting_http_outcome(current_setting('anka.refreshpermit2')::uuid,'validated',repeat('c',64),null);
select set_config('anka.page',jsonb_set(current_setting('anka.page')::jsonb,'{retrieved_at}',to_jsonb(to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')))::text,true);
select pg_temp.check_true(public.commit_project_reporting_refresh_page(current_setting('anka.fourjob')::uuid,current_setting('anka.refreshclaim')::uuid,current_setting('anka.page')::jsonb)->>'result_state'='successful_empty','Two validated original responses allow atomic empty ingestion without invented metrics');
select pg_temp.check_true(public.commit_project_reporting_refresh_page(current_setting('anka.fourjob')::uuid,current_setting('anka.refreshclaim')::uuid,current_setting('anka.page')::jsonb)->>'replayed'='true','Original ingestion response recovery repeats no HTTP or observations');
rollback to original;
select set_config('request.jwt.claim.role','service_role',true);
select set_config('anka.shortpolicy',(public.configure_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,1,jsonb_set(current_setting('anka.refreshinput')::jsonb,'{limits,lease_seconds}','1'),gen_random_uuid())->>'policy_id'),true);
select set_config('anka.shortchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.shortpolicy')::uuid,current_setting('anka.shortchallenge')::uuid);
select set_config('anka.shortclaim',gen_random_uuid()::text,true);
select public.claim_project_reporting_verification(current_setting('anka.shortchallenge')::uuid,current_setting('anka.shortclaim')::uuid);
select set_config('anka.shortpermit',gen_random_uuid()::text,true);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.shortclaim')::uuid,1,current_setting('anka.shortpermit')::uuid)->>'dispatch_authorized'='true','Bounded short lease grants original first permit');
select pg_sleep(1.05);
select pg_temp.check_true(public.claim_project_reporting_http_request('verification',current_setting('anka.shortclaim')::uuid,2,gen_random_uuid())->>'dispatch_authorized'='false','Expired original lease never grants later call');
select pg_temp.expect_error($q$select public.record_project_reporting_http_outcome(current_setting('anka.shortpermit')::uuid,'validated',repeat('b',64),clock_timestamp()+interval '1 minute')$q$,'22023','Late response cannot fabricate current validated proof');
select pg_temp.check_true(public.record_project_reporting_http_outcome(current_setting('anka.shortpermit')::uuid,'uncertain',repeat('b',64),null)#>>'{requests,0,outcome}'='uncertain','Expired original request can retain uncertain outcome without redispatch');
select pg_temp.check_true(private.reporting_http_usage(current_setting('anka.b6binding')::uuid,clock_timestamp())=2,'Timeout retains both original reserved units');
rollback to before_cost;
-- One prior ordinary claim leaves one unit; newly reviewed two-call source cannot fit.
select set_config('request.jwt.claim.role','service_role',true);
select pg_temp.check_true(pg_temp.claim()->>'dispatch_authorized'='true','Unregistered cost preserves original one-call claim');
select pg_temp.check_true(not exists(select 1 from private.reporting_http_reservations where claim_id=current_setting('anka.claim')::uuid),'One-call claim creates no new reservation row');
select set_config('anka.observed',clock_timestamp()::text,true);
select pg_temp.complete();
insert into private.reporting_http_costs values('local-adapter-only',repeat('a',64),2);
select set_config('anka.nextchallenge',gen_random_uuid()::text,true);
select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.nextchallenge')::uuid);
select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.nextchallenge')::uuid,gen_random_uuid())->>'blocked_reason'='rolling_day_quota_exhausted','One remaining unit denies two-call admission before any request');
select pg_temp.check_true((select count(*)=0 from private.reporting_http_permits),'Insufficient capacity produced zero HTTP permits');
rollback;
