begin;
create function pg_temp.editor_assert(p_ok boolean,p_name text) returns void language plpgsql as $$begin if p_ok is distinct from true then raise exception 'FAIL %',p_name;end if;raise notice 'PASS %',p_name;end;$$;
create function pg_temp.editor_error(p_sql text,p_name text,p_state text) returns void language plpgsql as $$begin begin execute p_sql;exception when others then if sqlstate<>p_state then raise exception 'FAIL % expected % got %: %',p_name,p_state,sqlstate,sqlerrm;end if;raise notice 'PASS %',p_name;return;end;raise exception 'FAIL % did not reject',p_name;end;$$;
do $$declare org uuid:='99999999-9999-4999-8999-999999999901';project uuid:='99999999-9999-4999-8999-999999999974';version uuid:='99999999-9999-4999-8999-999999997143';page uuid;result jsonb;before_rows jsonb;large_content jsonb;large_version uuid:=gen_random_uuid();begin
 select id into page from public.project_website_pages where organization_id=org and project_id=project and page_key='page:1';
 if page is null then raise exception 'Owned AD1 native prerequisite registry missing';end if;
 select jsonb_build_array((select count(*) from public.project_website_pages),(select count(*) from public.project_website_page_revisions),(select count(*) from public.project_website_page_seo_links),(select count(*) from public.project_website_page_commands),(select count(*) from public.work_items)) into before_rows;
 result:=public.get_project_website_page_editor(org,project,page,version);
 perform pg_temp.editor_assert(result->'page'->>'initial_path'='home' and result->>'planned_path'='welcome','Editor retains original identity and exact approved rename');
 perform pg_temp.editor_assert(result->'source_page'=(select content->'pages'->0 from public.artifact_versions where id=version),'Full exact canonical page/sections/CTA/source fields preserved');
 perform pg_temp.editor_assert(result->'reference'->>'artifact_version_id'=version::text and result->'source_page'->>'slug'<>'unapproved-path','Later draft never replaces selected approved source');
 perform pg_temp.editor_assert((result->>'expected_revision')::bigint=(select max(revision_number) from public.project_website_page_revisions where page_id=page),'Editor pins current optimistic operational revision');
 perform pg_temp.editor_assert(jsonb_array_length(result->'work_candidates'->'items')=1 and result->'work_candidates'->'items'->0->>'id'='99999999-9999-4999-8999-999999997160' and result->'work_candidates'->'items'->0->>'linked_page_path'='home','Only existing canonical same-page Content work is offered');
 perform pg_temp.editor_assert(result->'work_candidates'->'items'->0->>'assignee_id'='99999999-9999-4999-8999-999999999902' and result->'work_candidates'->'items'->0->>'due_date'='2026-10-10','Owner/deadline read from unchanged canonical work');
 perform pg_temp.editor_assert(exists(select 1 from jsonb_array_elements(result->'seo_candidates'->'items') i where i->>'id'='99999999-9999-4999-8999-999999997150') and result->'seo_link'='null'::jsonb,'Same-brand target is only offered for explicit selection, never auto-linked');
 perform pg_temp.editor_assert(before_rows=jsonb_build_array((select count(*) from public.project_website_pages),(select count(*) from public.project_website_page_revisions),(select count(*) from public.project_website_page_seo_links),(select count(*) from public.project_website_page_commands),(select count(*) from public.work_items)),'Opening editor makes zero writes/work/assignment/links');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,gen_random_uuid(),version),'Foreign page rejected','42501');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,gen_random_uuid(),page,version),'Foreign project rejected','42501');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',gen_random_uuid(),project,page,version),'Foreign organization rejected','42501');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,page,'99999999-9999-4999-8999-999999997145'),'Unapproved newer architecture denied','42501');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L,%L,0,0,51)',org,project,page,version,''),'Lookup limits bounded','22023');
 result:=public.get_project_website_page_editor(org,project,page,version,'unrelated search');
 perform pg_temp.editor_assert(result->'work_candidates'->'items'='[]'::jsonb and result->'seo_candidates'->'items'='[]'::jsonb and result->'source_page'->>'slug'='welcome','Bounded search does not replace exact source or infer missing candidates');
 update public.work_items set deleted_at=now() where id='99999999-9999-4999-8999-999999997160';
 result:=public.get_project_website_page_editor(org,project,page,version);
 perform pg_temp.editor_assert(result->'work_candidates'->'items'='[]'::jsonb,'Unavailable canonical work excluded from handoff selection');
 -- Synthetic malformed-size authority fixture only; not a human approval journey.
 select jsonb_set(content,'{pages,0,sections,0,purpose}',to_jsonb(repeat('x',132000))) into large_content from public.artifact_versions where id=version;
 insert into public.artifact_versions(id,organization_id,artifact_id,version_number,content,content_checksum,created_by) values(large_version,org,'99999999-9999-4999-8999-999999997140',(select max(version_number)+1 from public.artifact_versions where artifact_id='99999999-9999-4999-8999-999999997140'),large_content,encode(sha256(convert_to(large_content::text,'UTF8')),'hex'),'99999999-9999-4999-8999-999999999902');
 insert into public.artifact_approvals(organization_id,artifact_id,artifact_version_id,engagement_id,approved_by,notes) values(org,'99999999-9999-4999-8999-999999997140',large_version,'99999999-9999-4999-8999-999999999975','99999999-9999-4999-8999-999999999902','Synthetic size negative; not human acceptance');
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,page,large_version),'Oversize exact page denied whole without truncation','22023');
 update public.organization_memberships set status='suspended' where organization_id=org and user_id='99999999-9999-4999-8999-999999999902';
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,page,version),'Current membership removal denies source bytes','42501');
 update public.organization_memberships set status='active',role='contributor' where organization_id=org and user_id='99999999-9999-4999-8999-999999999902';
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,page,version),'Unbound contributor cannot receive operational handoff candidates','42501');
 update public.organization_memberships set role='operations_admin' where organization_id=org and user_id='99999999-9999-4999-8999-999999999902';
 update public.projects set archived_at=now() where id=project;
 perform pg_temp.editor_error(format('select public.get_project_website_page_editor(%L,%L,%L,%L)',org,project,page,version),'Archived project denies editor context','42501');
end;$$;
select pg_temp.editor_assert(has_function_privilege('authenticated','public.get_project_website_page_editor(uuid,uuid,uuid,uuid,text,integer,integer,integer)','EXECUTE') and not has_function_privilege('anon','public.get_project_website_page_editor(uuid,uuid,uuid,uuid,text,integer,integer,integer)','EXECUTE') and not has_function_privilege('service_role','public.get_project_website_page_editor(uuid,uuid,uuid,uuid,text,integer,integer,integer)','EXECUTE'),'Only authenticated current authority has editor RPC grant');
rollback;
