
[functions.invite-user]
enabled = true
verify_jwt = true
import_map = "./functions/invite-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/invite-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/invite-user/*.html" ]

[functions.ai-chat]
enabled = true
verify_jwt = true
entrypoint = "./functions/ai-chat/index.ts"

[functions.invite-client-contact]
enabled = true
verify_jwt = true
entrypoint = "./functions/invite-client-contact/index.ts"

[functions.portal-file-url]
enabled = true
verify_jwt = true
entrypoint = "./functions/portal-file-url/index.ts"

[functions.integration-gateway]
enabled = true
verify_jwt = true
entrypoint = "./functions/integration-gateway/index.ts"
