import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { OUTPUT_FAMILIES, latestByVersion } from '../data/designWorkshop.js'
import { designWorkshop } from '../data/designWorkshopRepository.js'
import { composePageDesignPreview } from '../data/websitePageDesigns.js'
import { useAuth } from '../context/AuthContext.jsx'
import VersionProofingPanel from '../components/VersionProofingPanel.jsx'
import ArtifactRelationsPanel from '../components/ArtifactRelationsPanel.jsx'

const INPUT = 'w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 py-2.5 text-sm text-slate-100 outline-none focus:border-violet-500/60'
const BUTTON = 'rounded-xl bg-violet-500 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40'
const VARIANT_FORMATS = [
  ['square_1x1', 'Square 1:1 · 1080×1080'], ['portrait_4x5', 'Portrait 4:5 · 1080×1350'],
  ['story_9x16', 'Story / Reel 9:16 · 1080×1920'], ['landscape_1_91x1', 'Landscape 1.91:1 · 1200×628'],
  ['banner_728x90', 'Leaderboard · 728×90'], ['banner_300x250', 'Medium rectangle · 300×250'],
]

export default function DesignWorkshop() {
  const { user } = useAuth()
  const [searchParams] = useSearchParams()
  const requestedEngagementId = searchParams.get('engagement') || ''
  const requestedSessionId = searchParams.get('session') || ''
  const [engagements, setEngagements] = useState([])
  const [engagementId, setEngagementId] = useState('')
  const [workspace, setWorkspace] = useState(null)
  const [tab, setTab] = useState('artifacts')
  const [modal, setModal] = useState(null)
  const [busy, setBusy] = useState('')
  const [error, setError] = useState('')

  useEffect(() => { designWorkshop.listEngagements().then(items => {
    const designItems = items.filter(item => (item.engagement_services || []).some(service => {
      const catalog = Array.isArray(service.service_catalog) ? service.service_catalog[0] : service.service_catalog
      return catalog?.department_id === 'design'
    }))
    setEngagements(designItems)
    const requested = designItems.find(item => item.id === requestedEngagementId)
    if (requested || designItems[0]) setEngagementId((requested || designItems[0]).id)
  }).catch(capture) }, [])
  useEffect(() => { if (engagementId) refresh() }, [engagementId])

  function capture(reason) { setError(reason instanceof Error ? reason.message : String(reason)); setBusy('') }
  async function refresh() { setError(''); setBusy('load'); try { setWorkspace(await designWorkshop.load(engagementId)) } catch (reason) { capture(reason) } finally { setBusy('') } }
  async function act(key, action) { setBusy(key); setError(''); try { await action(); setModal(null); await refresh() } catch (reason) { capture(reason) } finally { setBusy('') } }

  if (!engagements.length && !error) return <Shell><Empty title="No Design engagement yet" text="Activate at least one Design service on an engagement before opening the Workshop." /></Shell>
  return <Shell>
    <div className="flex flex-col gap-4 border-b border-white/10 pb-5 lg:flex-row lg:items-end lg:justify-between">
      <div><p className="text-xs font-semibold uppercase tracking-[.24em] text-violet-400">Designer-controlled environment</p><h1 className="mt-2 text-3xl font-semibold">Design Workshop</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Approved human context becomes three traceable directions. Nothing is approved or released automatically.</p></div>
      <Field label="Engagement"><select className={`${INPUT} min-w-72`} value={engagementId} onChange={event => setEngagementId(event.target.value)}>{engagements.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
    </div>
    {error && <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}
    <div className="mt-5 flex gap-2">{[['artifacts', 'Approved Content context'], ['workshop', 'Direction workshop']].map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${tab === id ? 'bg-white text-slate-950' : 'bg-white/5 text-slate-300'}`}>{label}</button>)}</div>
    {busy === 'load' || !workspace ? <div className="py-20 text-center text-sm text-slate-500">Loading exact versions…</div>
      : tab === 'artifacts' ? <ArtifactWorkspace workspace={workspace} />
        : <WorkshopWorkspace workspace={workspace} focusedSessionId={requestedSessionId} currentUserId={user?.id} onCreate={() => setModal({ kind: 'session' })} onGenerate={session => act(`generate-${session.id}`, () => designWorkshop.generateDirections(session.id))} onGenerateImage={(version, modelId, prompt) => act(`image-${version.id}`, () => designWorkshop.generateImage(version.id, modelId, prompt))} onGenerateVariants={(versionId, modelId, formats) => act(`variants-${versionId}`, () => designWorkshop.generateVariants(versionId, modelId, formats))} onGenerateVideo={(version, prompt) => act(`video-${version.id}`, () => designWorkshop.createVideoPlaceholder(version.id, prompt))} onGeneratePage={(versionId, slug, modelId) => act('generate-page', () => designWorkshop.generatePageDesign(versionId, slug, modelId))} onSubmitPage={designId => act(`submit-page-${designId}`, () => designWorkshop.submitPageDesignReview(designId))} onApprovePage={designId => act(`approve-page-${designId}`, () => designWorkshop.approvePageDesign(designId))} onRefine={(direction, version) => setModal({ kind: 'refine', direction, version })} onPromote={version => act(`promote-${version.id}`, () => designWorkshop.promoteDirectionExperiment(version.id))} onSelect={(session, version) => act(`select-${version.id}`, () => designWorkshop.selectDirection(session.id, version.id))} onRelease={session => act(`release-${session.id}`, () => designWorkshop.releaseDirection(session.id, 'Released by the accountable human reviewer.'))} busy={busy} />}
    {modal?.kind === 'session' && <SessionModal workspace={workspace} busy={busy} onClose={() => setModal(null)} onSave={input => act('create-session', () => designWorkshop.createSession(input))} />}
    {modal?.kind === 'refine' && <RefineModal {...modal} reviewers={workspace.experimentReviewers || []} currentUserId={user?.id} busy={busy} onClose={() => setModal(null)} onSave={(content, experiment) => act('refine', () => designWorkshop.createDirectionRevision(modal.direction.id, modal.version.id, content, experiment))} />}
  </Shell>
}

function ArtifactWorkspace({ workspace }) {
  const types = [['discovery', 'Discovery'], ['vision', 'Vision'], ['audience', 'Audience']]
  return <div className="mt-6"><Panel><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-400">Read-only upstream context</p><h2 className="mt-2 text-xl font-semibold">Content Studio owns these artifacts</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Design compiles the exact approved versions below. Creation, revision, and approval now happen in Content Studio.</p></div><Link to="/sphere/content/studio" className={BUTTON}>Open Content Studio</Link></div></Panel><div className="mt-5 grid gap-5 xl:grid-cols-3">{types.map(([type, label]) => {
    const artifact = workspace.artifacts.find(item => item.artifact_type === type)
    const versions = workspace.versions.filter(item => item.artifact_id === artifact?.id)
    const approval = [...workspace.approvals].filter(item => item.artifact_id === artifact?.id).sort((a, b) => new Date(b.approved_at) - new Date(a.approved_at))[0]
    const approvedVersion = versions.find(item => item.id === approval?.artifact_version_id)
    return <Panel key={type}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-400">{label}</p><h2 className="mt-2 text-lg font-semibold">{artifact?.title || `${label} artifact`}</h2></div><Badge tone={approvedVersion ? 'green' : 'amber'}>{approvedVersion ? 'Approved' : 'Missing'}</Badge></div>
      {approvedVersion ? <><div className="mt-5 space-y-2 rounded-xl bg-white/[0.03] p-3 text-xs text-slate-400"><p>Exact approved version {approvedVersion.version_number} · {new Date(approval.approved_at).toLocaleString()}</p><p>{approvedVersion.ai_use_allowed ? 'Authorised for Design AI context' : 'Not authorised for Design AI context'} · {approvedVersion.data_classification}</p></div><ArtifactRelationsPanel artifact={artifact} /></> : <Empty title="No approved version" text="Complete and approve this artifact in Content Studio." compact />}
    </Panel>
  })}</div></div>
}

function WorkshopWorkspace({ workspace, focusedSessionId, currentUserId, onCreate, onGenerate, onGenerateImage, onGenerateVariants, onGenerateVideo, onGeneratePage, onSubmitPage, onApprovePage, onRefine, onPromote, onSelect, onRelease, busy }) {
  const approvedTypes = new Set(workspace.approvals.map(approval => workspace.artifacts.find(item => item.id === approval.artifact_id)?.artifact_type).filter(Boolean))
  const ready = ['discovery', 'vision', 'audience'].every(type => approvedTypes.has(type))
  const session = workspace.sessions.find(item => item.id === focusedSessionId) || workspace.sessions[0]
  const directions = session ? workspace.directions.filter(item => item.session_id === session.id) : []
  const selection = session && workspace.selections.find(item => item.session_id === session.id)
  const release = session && workspace.releases.find(item => item.session_id === session.id)
  const activeService = session && workspace.designServices.find(item => item.id === session.engagement_service_id)
  const variantEligible = ['social_assets', 'advertising_assets'].includes(serviceCatalog(activeService)?.slug)
  return <div className="mt-6 space-y-6">
    {!session ? <Panel><h2 className="text-xl font-semibold">Compile approved context</h2><p className="mt-2 text-sm text-slate-400">The session snapshots exact approved Discovery, Vision and Audience versions, then adds an output brief and designer-safe instructions.</p><div className="mt-4 flex items-center gap-3"><Badge tone={ready ? 'green' : 'amber'}>{approvedTypes.size}/3 approved</Badge><button disabled={!ready} className={BUTTON} onClick={onCreate}>Create Design Workshop session</button></div></Panel>
      : <Panel><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-400">Compiled session</p><h2 className="mt-2 text-xl font-semibold">{sessionServiceLabel(session, workspace.designServices)}</h2><p className="mt-2 text-sm text-slate-400">Context {session.context_checksum.slice(0, 12)}… · {Object.keys(session.context_manifest?.artifacts || {}).length} exact approved inputs</p></div><Badge tone={release ? 'green' : session.status === 'generation_failed' ? 'red' : 'violet'}>{release ? 'Released' : session.status.replaceAll('_', ' ')}</Badge></div><p className="mt-4 rounded-xl bg-white/[0.03] p-4 text-sm leading-6 text-slate-300">{session.designer_instructions}</p>{!directions.length && <button disabled={busy === `generate-${session.id}` || !['ready', 'generation_failed'].includes(session.status)} onClick={() => onGenerate(session)} className={`${BUTTON} mt-4`}>{busy === `generate-${session.id}` ? 'Generating three distinct directions…' : 'Generate three directions'}</button>}</Panel>}
    {!!directions.length && <div className="grid gap-5 xl:grid-cols-3">{directions.map(direction => { const versions = workspace.directionVersions.filter(item => item.direction_id === direction.id); const version = latestByVersion(versions); const selected = selection?.direction_version_id === version?.id; return <DirectionCard key={direction.id} direction={direction} versions={versions} version={version} models={workspace.models} mediaAssets={workspace.mediaAssets} selected={selected} released={release?.direction_version_id === version?.id} onGenerateImage={(modelId, prompt) => onGenerateImage(version, modelId, prompt)} onGenerateVideo={prompt => onGenerateVideo(version, prompt)} onRefine={() => onRefine(direction, version)} onSelect={() => onSelect(session, version)} canSelect={!selection} busy={busy} /> })}</div>}
    {release && variantEligible && <VariantWorkspace key={release.direction_version_id} workspace={workspace} release={release} onGenerate={onGenerateVariants} busy={busy} />}
    {!!workspace.experimentalDirectionVersions.length && <Panel><div><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Private experiments</p><h2 className="mt-2 text-xl font-semibold">Experimental versions</h2><p className="mt-2 text-sm text-slate-400">Visible only to each creator and invited reviewers. Experiments stay outside the main history until promoted.</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{workspace.experimentalDirectionVersions.map(version => { const direction = directions.find(item => item.id === version.direction_id); const canPromote = version.created_by === currentUserId || (version.experiment_visibility || []).includes(currentUserId); return <ExperimentCard key={version.id} direction={direction} version={version} models={workspace.models} mediaAssets={workspace.mediaAssets} canPromote={canPromote} onGenerateImage={(modelId, prompt) => onGenerateImage(version, modelId, prompt)} onGenerateVideo={prompt => onGenerateVideo(version, prompt)} onPromote={() => onPromote(version)} busy={busy} /> })}</div></Panel>}
    {!!directions.length && <PageDesignWorkspace workspace={workspace} onGenerate={onGeneratePage} onSubmit={onSubmitPage} onApprove={onApprovePage} busy={busy} />}
    {selection && !release && <Panel><h3 className="font-semibold">Human selection recorded</h3><p className="mt-2 text-sm text-slate-400">Selection does not equal release. The accountable Design manager must perform the separate release action.</p><button disabled={busy === `release-${session.id}`} onClick={() => onRelease(session)} className={`${BUTTON} mt-4`}>Release selected exact version</button></Panel>}
  </div>
}

function VariantWorkspace({ workspace, release, onGenerate, busy }) {
  const imageModels = workspace.models.filter(model => model.supported_output_types?.includes('image'))
  const sourceVersion = workspace.directionVersions.find(item => item.id === release.direction_version_id)
  const variants = (workspace.variants || []).filter(item => item.source_direction_version_id === sourceVersion?.id)
  const [modelId, setModelId] = useState(imageModels[0]?.id || '')
  const [formats, setFormats] = useState([])
  function toggle(format) { setFormats(current => current.includes(format) ? current.filter(item => item !== format) : [...current, format]) }
  if (!sourceVersion) return null
  return <Panel><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-300">DS2 · Released-format variants</p><h2 className="mt-2 text-xl font-semibold">Adapt the approved concept</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Create user-selected social and advertising formats from released version {sourceVersion.id.slice(0, 8)}. Each format is tracked independently and remains separate from direction comparison.</p></div><Badge tone="green">Released source</Badge></div>
    <div className="mt-5 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{VARIANT_FORMATS.map(([format, label]) => <label key={format} className="flex items-start gap-3 rounded-xl border border-white/10 p-3 text-sm"><input type="checkbox" checked={formats.includes(format)} onChange={() => toggle(format)} /><span>{label}</span></label>)}</div>
    {imageModels.length ? <Field label="Image model"><select className={`${INPUT} mt-4`} value={modelId} onChange={event => setModelId(event.target.value)}>{imageModels.map(model => <option key={model.id} value={model.id}>{model.display_name}</option>)}</select></Field> : <p className="mt-4 text-sm text-amber-300">No active image-capable Design model is available.</p>}
    <button className={`${BUTTON} mt-4`} disabled={!formats.length || !modelId || busy === `variants-${sourceVersion.id}`} onClick={() => onGenerate(sourceVersion.id, modelId, formats)}>{busy === `variants-${sourceVersion.id}` ? 'Generating selected variants…' : `Generate ${formats.length || ''} selected variant${formats.length === 1 ? '' : 's'}`}</button>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{variants.map(variant => { const asset = workspace.mediaAssets.find(item => item.id === variant.design_media_asset_id); const label = VARIANT_FORMATS.find(([format]) => format === variant.variant_format)?.[1] || variant.variant_format; return <section key={variant.id} className="rounded-2xl border border-white/10 bg-slate-950/50 p-3"><div className="mb-3 flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-[11px] text-slate-500">Derived from {sourceVersion.id.slice(0, 8)}</p></div><Badge tone={variant.status === 'ready' ? 'green' : variant.status === 'failed' ? 'red' : 'violet'}>{variant.status}</Badge></div>{asset ? <MediaAsset asset={asset} /> : <p className="rounded-xl bg-white/[0.03] p-3 text-xs text-slate-400">{variant.status === 'failed' ? 'This format failed before a media asset completed; sibling formats remain unaffected.' : 'Generation is queued or in progress.'}</p>}</section> })}</div>
    {!variants.length && <Empty title="No released variants yet" text="Choose only the formats needed for this approved Social or Advertising direction." compact />}
  </Panel>
}

function PageDesignWorkspace({ workspace, onGenerate, onSubmit, onApprove, busy }) {
  const versions = [...workspace.directionVersions, ...workspace.experimentalDirectionVersions]
  const models = workspace.models.filter(model => model.supported_output_types?.includes('html_css'))
  const [versionId, setVersionId] = useState(versions[0]?.id || '')
  const [slug, setSlug] = useState(workspace.architecturePages[0]?.slug || '')
  const [modelId, setModelId] = useState(models[0]?.id || '')
  const attempts = workspace.pageDesigns.filter(item => item.design_direction_version_id === versionId && item.slug === slug)
  return <Panel><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-400">RP4 · HTML/CSS page design</p><h2 className="mt-2 text-xl font-semibold">Generate and review a real webpage</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Each generation creates a new immutable attempt from one exact direction version and one architecture <code>slug</code>. The preview is sandboxed; CMS export remains a separate phase.</p></div><Badge tone="violet">{workspace.pageDesigns.length} attempts</Badge></div>
    <div className="mt-5 grid gap-3 lg:grid-cols-3"><Field label="Exact direction version"><select className={INPUT} value={versionId} onChange={event => setVersionId(event.target.value)}>{versions.map(version => <option key={version.id} value={version.id}>Direction {workspace.directions.find(item => item.id === version.direction_id)?.direction_slot || '?'} · v{version.version_number}{version.is_experimental ? ' · private experiment' : ''}</option>)}</select></Field><Field label="Architecture slug"><select className={INPUT} value={slug} onChange={event => setSlug(event.target.value)}>{workspace.architecturePages.map(page => <option key={page.slug} value={page.slug}>{page.title} · {page.slug}</option>)}</select></Field><Field label="HTML/CSS model"><select className={INPUT} value={modelId} onChange={event => setModelId(event.target.value)}>{models.map(model => <option key={model.id} value={model.id}>{model.display_name}</option>)}</select></Field></div>
    {!workspace.architecturePages.length && <p className="mt-3 text-sm text-amber-300">No website architecture pages are visible. Create a Content Studio architecture using the canonical <code>slug</code> field first.</p>}
    {!models.length && <p className="mt-3 text-sm text-amber-300">No active model currently supports HTML/CSS output. The RP4 migration registers this capability on the existing text model.</p>}
    <button className={`${BUTTON} mt-4`} disabled={!versionId || !slug || !modelId || busy === 'generate-page'} onClick={() => onGenerate(versionId, slug, modelId)}>{busy === 'generate-page' ? 'Generating page attempt…' : 'Generate new page attempt'}</button>
    <div className="mt-6 space-y-5">{attempts.map((attempt, index) => <section key={attempt.id} className="overflow-hidden rounded-2xl border border-white/10 bg-slate-950/60"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 p-4"><div><p className="text-sm font-semibold">Attempt {attempts.length - index} · <code>{attempt.slug}</code></p><p className="mt-1 text-xs text-slate-500">{new Date(attempt.created_at).toLocaleString()} · exact version {attempt.design_direction_version_id.slice(0, 8)}</p></div><div className="flex items-center gap-2"><Badge tone={attempt.status === 'approved' ? 'green' : attempt.status === 'in_review' ? 'amber' : 'slate'}>{attempt.status.replaceAll('_', ' ')}</Badge>{attempt.status === 'draft' && <button disabled={busy === `submit-page-${attempt.id}`} onClick={() => onSubmit(attempt.id)} className="rounded-xl border border-white/10 px-3 py-2 text-sm font-semibold">Submit for review</button>}{attempt.status === 'in_review' && <button disabled={busy === `approve-page-${attempt.id}`} onClick={() => onApprove(attempt.id)} className={BUTTON}>Approve exact attempt</button>}</div></div><iframe title={`Preview of ${attempt.slug} attempt ${attempt.id}`} sandbox="" srcDoc={composePageDesignPreview(attempt.html_content, attempt.css_content)} className="h-[640px] w-full bg-white" /><details className="border-t border-white/10 p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-300">Inspect generated HTML and CSS</summary><div className="mt-3 grid gap-3 xl:grid-cols-2"><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-black/30 p-3 text-xs text-slate-400">{attempt.html_content}</pre><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-xl bg-black/30 p-3 text-xs text-slate-400">{attempt.css_content}</pre></div></details></section>)}{!attempts.length && <Empty title="No attempt for this page yet" text="Generate the first standalone design; later attempts will remain alongside it for comparison." compact />}</div>
  </Panel>
}

function ExperimentCard({ direction, version, models, mediaAssets, canPromote, onGenerateImage, onGenerateVideo, onPromote, busy }) {
  const content = version.content || {}
  return <section className="rounded-2xl border border-amber-400/20 bg-amber-400/[0.04] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-amber-300">Direction {direction?.direction_slot} · experimental v{version.version_number}</p><h3 className="mt-2 text-lg font-semibold">{content.title}</h3></div><Badge tone="amber">Experiment</Badge></div><p className="mt-3 text-sm leading-6 text-slate-400">{content.rationale}</p><p className="mt-3 text-xs text-slate-500">Immutable version {version.id.slice(0, 8)} · {version.experiment_visibility?.length || 0} invited reviewer(s)</p><DesignMediaPanel key={version.id} version={version} models={models} assets={mediaAssets} onGenerateImage={onGenerateImage} onGenerateVideo={onGenerateVideo} busy={busy} />{canPromote && <button disabled={busy === `promote-${version.id}`} onClick={onPromote} className={`${BUTTON} mt-4`}>{busy === `promote-${version.id}` ? 'Promoting…' : 'Promote to main version'}</button>}<VersionProofingPanel targetKind="design_direction" versions={[version]} initialVersionId={version.id} department="design" theme="violet" /></section>
}

function DirectionCard({ direction, versions, version, models, mediaAssets, selected, released, onGenerateImage, onGenerateVideo, onRefine, onSelect, canSelect, busy }) {
  const content = version?.content || {}; const palette = Array.isArray(content.palette) ? content.palette : []
  const [anchor, setAnchor] = useState(null)
  function anchorAt(event) { const bounds = event.currentTarget.getBoundingClientRect(); setAnchor({ x: (event.clientX - bounds.left) / bounds.width, y: (event.clientY - bounds.top) / bounds.height }) }
  return <Panel><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-slate-500">Direction {direction.direction_slot} · v{version?.version_number}</p><h3 className="mt-2 text-xl font-semibold">{content.title}</h3></div>{(selected || released) && <Badge tone="green">{released ? 'Released' : 'Selected'}</Badge>}</div><div role="button" tabIndex="0" aria-label="Click to anchor a proofing comment" onClick={anchorAt} onKeyDown={event => { if (event.key === 'Enter') setAnchor({ x: 0.5, y: 0.5 }) }} className="relative mt-4 cursor-crosshair overflow-hidden rounded-2xl border border-white/10" style={{ background: content.preview_spec?.background || '#111827' }}><div className="p-5"><div className="h-2 w-16 rounded-full" style={{ background: content.preview_spec?.accent || '#8b5cf6' }} /><p className="mt-10 text-2xl font-bold text-white">{content.creative_thesis}</p><p className="mt-3 text-sm text-white/70">{content.preview_spec?.composition}</p></div><div className="flex">{palette.map((color, index) => <div key={index} title={`${color.name}: ${color.hex}`} className="h-10 flex-1" style={{ background: color.hex }} />)}</div>{anchor && <span className="pointer-events-none absolute h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-violet-500 shadow-lg" style={{ left: `${anchor.x * 100}%`, top: `${anchor.y * 100}%` }} />}</div><p className="mt-2 text-[11px] text-violet-300">Click the preview to anchor a positional comment.</p><DesignMediaPanel key={version.id} version={version} models={models} assets={mediaAssets} onGenerateImage={onGenerateImage} onGenerateVideo={onGenerateVideo} busy={busy} /><p className="mt-4 text-sm leading-6 text-slate-400">{content.rationale}</p><div className="mt-4 flex flex-wrap gap-2">{(content.visual_principles || []).map(item => <Badge key={item}>{item}</Badge>)}</div><p className="mt-4 text-xs text-slate-500">Model run {version?.generation_run_id?.slice(0, 8) || 'human refinement'} · immutable version {version?.id?.slice(0, 8)}</p><div className="mt-5 flex gap-2"><button onClick={onRefine} className="rounded-xl border border-white/10 px-3 py-2 text-sm font-semibold">Refine as new version</button>{canSelect && <button disabled={busy === `select-${version.id}`} onClick={onSelect} className={BUTTON}>Select this version</button>}</div><VersionProofingPanel targetKind="design_direction" versions={versions} initialVersionId={version?.id} department="design" theme="violet" visualAnchor={anchor} visualAnchorVersionId={version?.id} onClearVisualAnchor={() => setAnchor(null)} /></Panel>
}

function DesignMediaPanel({ version, models, assets, onGenerateImage, onGenerateVideo, busy }) {
  const imageModels = models.filter(model => model.supported_output_types?.includes('image'))
  const versionAssets = assets.filter(asset => asset.design_direction_version_id === version.id)
  const [prompt, setPrompt] = useState([version.content?.imagery_direction, version.content?.creative_thesis].filter(Boolean).join('\n\n'))
  const [modelId, setModelId] = useState(imageModels[0]?.id || '')
  return <section className="mt-4 rounded-2xl border border-violet-400/15 bg-slate-950/50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-300">Generated media</p><p className="mt-1 text-[11px] text-slate-500">Attached only to immutable version {version.id.slice(0, 8)}</p></div><Badge tone="violet">{versionAssets.length} outputs</Badge></div><textarea rows="3" className={`${INPUT} mt-3`} value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="Image or video generation prompt" />{imageModels.length ? <select className={`${INPUT} mt-2`} value={modelId} onChange={event => setModelId(event.target.value)}>{imageModels.map(model => <option key={model.id} value={model.id}>{model.display_name}</option>)}</select> : <p className="mt-2 text-xs text-amber-300">No active image model is registered yet.</p>}<div className="mt-2 flex flex-wrap gap-2"><button disabled={!prompt.trim() || !modelId || busy === `image-${version.id}`} onClick={() => onGenerateImage(modelId, prompt)} className={BUTTON}>{busy === `image-${version.id}` ? 'Generating image…' : 'Generate image'}</button><button disabled={!prompt.trim() || busy === `video-${version.id}`} onClick={() => onGenerateVideo(prompt)} className="rounded-xl border border-white/10 px-3 py-2 text-sm font-semibold disabled:opacity-40">Generate video</button></div><div className="mt-3 grid gap-3">{versionAssets.map(asset => <MediaAsset key={asset.id} asset={asset} />)}</div></section>
}

function MediaAsset({ asset }) {
  if (asset.media_type === 'image' && asset.status === 'ready') return <figure className="overflow-hidden rounded-xl border border-white/10 bg-black/30">{asset.signed_url ? <img src={asset.signed_url} alt={asset.prompt} className="w-full object-cover" /> : <div className="p-4 text-xs text-amber-300">The private image link expired. Refresh the Workshop to renew it.</div>}<figcaption className="p-3 text-xs text-slate-400">{asset.prompt}</figcaption></figure>
  const failed = asset.status === 'failed'
  return <div className={`rounded-xl border p-3 text-xs ${failed ? 'border-red-500/20 bg-red-500/5 text-red-200' : asset.status === 'unavailable' ? 'border-amber-500/20 bg-amber-500/5 text-amber-200' : 'border-violet-500/20 bg-violet-500/5 text-violet-200'}`}><p className="font-semibold capitalize">{asset.media_type} · {asset.status}</p><p className="mt-1 leading-5">{asset.failure_reason || (asset.status === 'generating' ? 'Generation is in progress. Refresh to check again.' : asset.prompt)}</p>{failed && <p className="mt-1 text-slate-400">Adjust the prompt or connector, then generate a new attempt. This failed record stays in the audit trail.</p>}</div>
}

function SessionModal({ workspace, onClose, onSave, busy }) {
  const directionModels = workspace.models.filter(model => model.supported_output_types?.includes('design_direction'))
  const [serviceId, setServiceId] = useState(workspace.designServices[0]?.id || ''); const [instructions, setInstructions] = useState('')
  const [goal, setGoal] = useState(''); const [format, setFormat] = useState('Concept direction and design system recommendation')
  const [modelIds, setModelIds] = useState(directionModels.slice(0, 2).map(item => item.id)); const [safe, setSafe] = useState(false)
  const [externalEventId, setExternalEventId] = useState('')
  function toggle(id) { setModelIds(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 3 ? [...current, id] : current) }
  function submit(event) { event.preventDefault(); onSave({ engagement_id: workspace.engagement.id, brand_id: workspace.engagement.brand_id, engagement_stage_instance_id: bestStage(workspace.stages, 'design')?.id || null, engagement_service_id: serviceId, output_brief: { goal, required_format: format }, designer_instructions: instructions, instructions_safe_for_ai: safe, model_registry_ids: modelIds, external_event_id: externalEventId || null }) }
  return <Modal title="Create Design Workshop session" onClose={onClose}><form onSubmit={submit} className="space-y-5"><Field label="Active Design service"><select required className={INPUT} value={serviceId} onChange={event => setServiceId(event.target.value)}>{workspace.designServices.map(service => <option key={service.id} value={service.id}>{serviceCatalog(service)?.name || 'Design service'}</option>)}</select></Field><Field label="External event (optional)"><select className={INPUT} value={externalEventId} onChange={event => setExternalEventId(event.target.value)}><option value="">No external event</option>{(workspace.externalEvents || []).map(item => <option key={item.id} value={item.id}>{item.start_date} · {item.event_name}</option>)}</select><span className="mt-2 block text-xs leading-5 text-slate-500">Selecting an event adds this session to its shared content plan as a Design asset. Sessions without an event work unchanged.</span></Field><Field label="Output goal"><textarea required rows="3" className={INPUT} value={goal} onChange={event => setGoal(event.target.value)} /></Field><Field label="Required format"><input required className={INPUT} value={format} onChange={event => setFormat(event.target.value)} /></Field><Field label="Designer instructions"><textarea required rows="5" className={INPUT} value={instructions} onChange={event => setInstructions(event.target.value)} placeholder="Desired direction, references, exclusions, dimensions and production constraints" /></Field><div><p className="text-sm font-medium">Model routing</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{directionModels.map(model => <label key={model.id} className="flex items-start gap-3 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={modelIds.includes(model.id)} onChange={() => toggle(model.id)} /><span><span className="block text-sm font-semibold">{model.display_name}</span><span className="mt-1 block text-xs text-slate-500">{model.speed_class} · {model.cost_class} cost · {model.limitations}</span></span></label>)}</div></div><label className="flex items-center gap-3 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-sm"><input required type="checkbox" checked={safe} onChange={event => setSafe(event.target.checked)} /><span>I confirm these designer instructions are safe to send to the selected models.</span></label><button disabled={busy === 'create-session' || !serviceId || !modelIds.length || !safe} className={`${BUTTON} w-full`}>Compile exact approved context</button></form></Modal>
}

function RefineModal({ version, reviewers, currentUserId, onClose, onSave, busy }) {
  const [content, setContent] = useState(version.content)
  const [isExperimental, setIsExperimental] = useState(false)
  const [reviewerIds, setReviewerIds] = useState([])
  const set = (key, value) => setContent(current => ({ ...current, [key]: value }))
  function toggleReviewer(id) { setReviewerIds(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]) }
  return <Modal title={`Refine “${version.content.title}” as a new version`} onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave(content, { isExperimental, reviewerIds }) }} className="space-y-4"><Field label="Concept title"><input required className={INPUT} value={content.title || ''} onChange={event => set('title', event.target.value)} /></Field><Field label="Rationale"><textarea required rows="4" className={INPUT} value={content.rationale || ''} onChange={event => set('rationale', event.target.value)} /></Field><Field label="Creative thesis"><textarea required rows="3" className={INPUT} value={content.creative_thesis || ''} onChange={event => set('creative_thesis', event.target.value)} /></Field><Field label="Imagery direction"><textarea rows="3" className={INPUT} value={content.imagery_direction || ''} onChange={event => set('imagery_direction', event.target.value)} /></Field><Field label="Layout direction"><textarea rows="3" className={INPUT} value={content.layout_direction || ''} onChange={event => set('layout_direction', event.target.value)} /></Field><label className="flex items-start gap-3 rounded-xl border border-amber-400/20 bg-amber-400/5 p-3"><input type="checkbox" checked={isExperimental} onChange={event => setIsExperimental(event.target.checked)} /><span><span className="block text-sm font-semibold text-amber-200">Mark as experimental</span><span className="mt-1 block text-xs text-slate-400">Keep this version outside main comparison and history until someone promotes it.</span></span></label>{isExperimental && <div><p className="text-sm font-medium">Invite reviewers</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{reviewers.filter(reviewer => reviewer.user_id !== currentUserId).map(reviewer => <label key={reviewer.user_id} className="flex gap-3 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={reviewerIds.includes(reviewer.user_id)} onChange={() => toggleReviewer(reviewer.user_id)} /><span><span className="block text-sm font-semibold">{reviewer.full_name}</span><span className="text-xs capitalize text-slate-500">{reviewer.department_id || 'cross-functional'} · {reviewer.role.replaceAll('_', ' ')}</span></span></label>)}</div></div>}<button disabled={busy === 'refine'} className={`${BUTTON} w-full`}>{isExperimental ? 'Create private experiment' : 'Create linked version'}</button></form></Modal>
}

function bestStage(stages, type) { const terms = type === 'discovery' ? ['discovery'] : type === 'vision' ? ['vision', 'identity'] : type === 'audience' ? ['audience'] : ['design']; return stages.find(stage => terms.some(term => stage.name.toLowerCase().includes(term))) }
function serviceCatalog(service) { return Array.isArray(service?.service_catalog) ? service.service_catalog[0] : service?.service_catalog }
function sessionServiceLabel(session, services) { const service = services.find(item => item.id === session.engagement_service_id); return serviceCatalog(service)?.name || familyLabel(session.output_family) }
function familyLabel(value) { return OUTPUT_FAMILIES.find(([id]) => id === value)?.[1] || value }
function Shell({ children }) { return <main className="min-h-full bg-slate-950 px-5 py-6 text-slate-100 lg:px-8">{children}</main> }
function Panel({ children }) { return <section className="rounded-2xl border border-white/[0.08] bg-slate-900/60 p-5 shadow-xl shadow-black/10">{children}</section> }
function Badge({ children, tone = 'slate' }) { const colors = { slate: 'bg-white/5 text-slate-300', green: 'bg-emerald-500/10 text-emerald-300', amber: 'bg-amber-500/10 text-amber-300', violet: 'bg-violet-500/10 text-violet-300', red: 'bg-red-500/10 text-red-300' }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ${colors[tone]}`}>{children}</span> }
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</span>{children}</label> }
function Empty({ title, text, compact = false }) { return <div className={`${compact ? 'mt-5 py-3' : 'py-24'} text-center`}><p className="font-semibold text-slate-300">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></div> }
function Modal({ title, onClose, children }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><button type="button" onClick={onClose} className="rounded-lg px-3 py-2 text-sm text-slate-400 hover:bg-white/5">Close</button></div>{children}</div></div> }
