import {useEffect,useRef,useState} from 'react'
import {serializeCampaignDeliverablePlan} from '../data/projectCampaignDeliverablePlansRepository.js'
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const empty=()=>({title:'',brief:'',format:'',content_pillar:'',topic:'',due_date:'',contributor_ids:[],change_summary:'',source_version_id:null,client_approval_required:false})
const status=v=>v?v.replaceAll('_',' '):'Unknown'
export default function ProjectCampaignDeliverablePlanEditor({repository,people,actorId,organizationId,projectId,engagementId,campaignId,planVersionId,marketingServiceId,disabled=false,signal,onBlockedChange}){
 const base={actorId,organizationId,projectId,engagementId},key=`anka:campaign-deliverable-operation:${actorId}:${organizationId}:${projectId}:${engagementId}:v1`
 const [form,setForm]=useState(empty),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[records,setRecords]=useState({}),[search,setSearch]=useState({deliverables:'',versions:'',contributors:''}),[root,setRoot]=useState(null),[selectedVersion,setSelectedVersion]=useState(''),[headLoaded,setHeadLoaded]=useState(false),[expected,setExpected]=useState(null),[headStale,setHeadStale]=useState(false),[review,setReview]=useState(null),[receipt,setReceipt]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(()=>{try{const p=JSON.parse(sessionStorage.getItem(key)||'null');return p===null?null:UUID.test(p.requestId||'')?{requestId:p.requestId}:{requestId:''}}catch{return {requestId:''}}})
 const alive=useRef(true),flight=useRef(false),current=useRef(null),block=useRef(onBlockedChange);block.current=onBlockedChange;current.current={form,dirty,busy,records,search,root,selectedVersion,headLoaded,expected,headStale,review,pending,disabled,signal}
 const active=()=>alive.current&&!current.current.signal?.aborted
 const locked=()=>!active()||flight.current||current.current.busy||Boolean(current.current.pending)||current.current.disabled
 const blocked=dirty||busy||Boolean(review)||Boolean(pending)
 useEffect(()=>{block.current?.(blocked)},[blocked]);useEffect(()=>()=>{alive.current=false;block.current?.(false)},[])
 const put=(name,value,setter)=>{current.current[name]=value;setter(value)},hold=()=>block.current?.(true)
 function change(name,value){if(locked())return;hold();put('form',{...current.current.form,[name]:value},setForm);put('dirty',true,setDirty);put('review',null,setReview);setNotice('')}
 function editSearch(kind,value){if(locked())return;put('search',{...current.current.search,[kind]:value},setSearch);put('review',null,setReview)}
 function chooseRoot(value){if(locked()||current.current.dirty||current.current.review)return;const row=current.current.records.deliverables?.items.find(r=>r.id===value)||null;put('root',row,setRoot);put('form',empty(),setForm);put('selectedVersion','',setSelectedVersion);put('expected',row?.current_version_id??null,setExpected);put('headLoaded',Boolean(row),setHeadLoaded);put('headStale',false,setHeadStale);put('records',{deliverables:current.current.records.deliverables},setRecords);setReceipt(null);setNotice('')}
 async function read(kind,offset=0){if(locked())return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const c=current.current,result=kind==='contributors'?await people.candidates({...base,kind:'owner',query:c.search.contributors,offset,limit:25},{signal}):await repository.candidates({...base,kind,deliverableId:c.root?.id,query:c.search[kind],offset,limit:25},{signal});if(active())put('records',{...current.current.records,[kind]:result},setRecords)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function reloadHead(){if(locked()||!current.current.root)return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const data=await repository.candidates({...base,kind:'deliverables',query:current.current.root.id,offset:0,limit:1},{signal}),row=data.items.find(r=>r.id===current.current.root.id);if(!row)throw Error('The exact current deliverable is unavailable.');if(active()){put('root',row,setRoot);put('expected',row.current_version_id,setExpected);put('headLoaded',true,setHeadLoaded);put('headStale',false,setHeadStale);setNotice('Current canonical deliverable head loaded. Your draft remains.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function inspect(edit=false){if(locked()||!current.current.root||!current.current.selectedVersion||edit&&current.current.dirty)return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const data=await repository.getVersion({...base,deliverableId:current.current.root.id,deliverableVersionId:current.current.selectedVersion},{signal});if(!active())return;put('records',{...current.current.records,history:data},setRecords);put('root',{...current.current.root,...data.deliverable,department_id:data.workstream.department_id,workstream_status:data.workstream.status,available:!data.project_archived&&data.deliverable.archived_at===null&&!['withdrawn','archived'].includes(data.deliverable.status)&&['planned','active'].includes(data.workstream.status)},setRoot);put('expected',data.deliverable.current_version_id,setExpected);put('headLoaded',true,setHeadLoaded);put('headStale',false,setHeadStale)
   if(edit){if(data.version.withdrawn_at)throw Error('The selected source version is withdrawn. Its original history remains readable.');put('form',{...(data.planning?.input||{...empty(),title:data.version.title,client_approval_required:data.version.client_approval_required}),source_version_id:data.version.id,due_date:data.planning?.input.due_date||''},setForm);put('dirty',true,setDirty);put('review',null,setReview);setReceipt(null);setNotice('Loaded the selected exact version as a source for a new unapproved plan. Existing approval is not inherited.')}
  }catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function preview(){if(locked()||!campaignId||!planVersionId||!marketingServiceId||!current.current.root||!current.current.headLoaded||current.current.headStale)return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const c=current.current,input=serializeCampaignDeliverablePlan({...c.form,due_date:c.form.due_date||null}),args={...base,campaignId,planVersionId,marketingServiceId,deliverableId:c.root.id,expectedCurrentVersionId:c.expected,input},data=await repository.preview(args,{signal});if(active())put('review',{args,data},setReview)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 const clearPending=()=>{sessionStorage.removeItem(key);put('pending',null,setPending)}
 function accepted(data,message){clearPending();setReceipt(data);put('review',null,setReview);put('dirty',false,setDirty);put('form',empty(),setForm);put('headStale',true,setHeadStale);setNotice(message)}
 async function confirm(){if(locked()||!current.current.review)return;flight.current=true;hold();put('busy',true,setBusy);setError('');const chosen=current.current.review,operation={requestId:crypto.randomUUID()}
  try{sessionStorage.setItem(key,JSON.stringify(operation))}catch{flight.current=false;put('busy',false,setBusy);setError('The original operation key could not be retained. No version was saved.');return}put('pending',operation,setPending)
  try{const data=await repository.confirm({...chosen.args,reviewChecksum:chosen.data.review_checksum,requestId:operation.requestId,confirmed:true},{signal});if(active())accepted(data,'New unapproved canonical version and private planning saved. Reload the current deliverable head before another draft.')}catch(cause){if(active()){if(cause.knownRollback){clearPending();put('review',null,setReview);put('headStale',true,setHeadStale);setNotice('The version was not saved. Your fields remain; reload the head and review changed references.')}setError(cause.message)}}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function recover(){if(!active()||flight.current||current.current.busy||current.current.disabled||!current.current.pending?.requestId)return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const data=await repository.recover({...base,requestId:current.current.pending.requestId},{signal});if(active()){if(data===null){setNotice('The original version is still unknown. New commands remain blocked.');return}accepted(data,'Recovered the original canonical version and private planning. No command was repeated.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function discard(){if(locked())return;put('form',empty(),setForm);put('dirty',false,setDirty);put('review',null,setReview);setNotice('Deliverable plan draft discarded.');setError('')}
 const off=disabled||busy||Boolean(pending),ready=Boolean(campaignId&&planVersionId&&marketingServiceId&&root?.available&&headLoaded&&!headStale),field=(label,name,max=120,type='text')=><label className="block text-xs">{label}<input aria-label={label} className={INPUT} type={type} maxLength={max} value={form[name]} onChange={e=>change(name,e.target.value)}/></label>
 const browse=(kind,label,allowed=true)=><section className="space-y-2"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find {label}<input aria-label={`Find ${label}`} className={INPUT} maxLength={120} value={search[kind]} onChange={e=>editSearch(kind,e.target.value)}/></label><button type="button" className="workspace-button self-end" disabled={!allowed} onClick={()=>read(kind)}>Load {label}</button></div>{records[kind]&&<div className="flex flex-wrap gap-2 text-xs text-[var(--anka-muted)]"><span>{records[kind].items.length} shown · {records[kind].matching} matches · {records[kind].total} total</span>{records[kind].offset>0&&<button type="button" className="workspace-button" onClick={()=>read(kind,Math.max(0,records[kind].offset-25))}>Previous {label}</button>}{records[kind].has_more&&<button type="button" className="workspace-button" onClick={()=>read(kind,records[kind].offset+25)}>Next {label}</button>}</div>}</section>
 const history=records.history
 return <section aria-label="Campaign deliverable planning" className="space-y-3 border-t border-[var(--anka-line)] pt-4 break-words"><h4 className="font-semibold">Deliverable planning</h4><p className="text-sm text-[var(--anka-muted)]">Select an existing Project deliverable and exact source version. Save a new unapproved canonical version with a private brief, topic and contributor references. Approval stays in its existing workflow; contributors do not change assignments.</p>
 {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status" className="text-sm text-[var(--anka-muted)]">{notice}</p>}
 {pending&&<section aria-label="Recover original deliverable operation" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm space-y-2"><p>{pending.requestId?'The original deliverable operation needs reconciliation. Draft and campaign changes remain blocked.':'The saved operation key is unreadable. Restore its exact UUID before saving a new version.'}</p><button type="button" className="workspace-button" disabled={busy||disabled||!pending.requestId} onClick={recover}>Check original deliverable operation</button></section>}
 <fieldset disabled={off} className="space-y-3">{browse('deliverables','existing Project deliverables')}<label className="block text-xs">Existing Project deliverable<select aria-label="Existing Project deliverable" className={INPUT} disabled={dirty||Boolean(review)} value={root?.id||''} onChange={e=>chooseRoot(e.target.value)}><option value="">Choose explicitly</option>{root&&!records.deliverables?.items.some(r=>r.id===root.id)&&<option value={root.id}>{root.title} · selected exact identity</option>}{(records.deliverables?.items||[]).map(r=><option key={r.id} value={r.id}>{r.title} · {status(r.status)}{r.available?'':' · read only'}</option>)}</select></label>
 {root&&<p className="text-xs">Canonical owner: {root.owner_id||'Unassigned'} · canonical due date: {root.due_date||'Unknown'} · {status(root.workstream_status)} {root.department_id} workstream</p>}
 {browse('versions','exact deliverable versions',Boolean(root))}<label className="block text-xs">Exact deliverable source version<select aria-label="Exact deliverable source version" className={INPUT} disabled={dirty||Boolean(review)} value={selectedVersion} onChange={e=>{if(locked()||dirty||review)return;put('selectedVersion',e.target.value,setSelectedVersion)}}><option value="">Choose explicitly</option>{selectedVersion&&!records.versions?.items.some(r=>r.id===selectedVersion)&&<option value={selectedVersion}>Selected exact identity · {selectedVersion}</option>}{(records.versions?.items||[]).map(r=><option key={r.id} value={r.id}>{r.title} · v{r.version_number} · {status(r.review_status)}{r.withdrawn_at?' · withdrawn':''}</option>)}</select></label>
 <div className="flex flex-wrap gap-2"><button type="button" className="workspace-button" disabled={!selectedVersion} onClick={()=>inspect()}>Read exact deliverable history</button><button type="button" className="workspace-button" disabled={!selectedVersion||dirty||!ready} onClick={()=>inspect(true)}>Load selected deliverable plan for editing</button><button type="button" className="workspace-button" disabled={!root} onClick={reloadHead}>Reload current deliverable head</button><button type="button" className="workspace-button" disabled={!dirty&&!review} onClick={discard}>Discard deliverable plan draft</button></div>
 <p className="text-xs">Canonical parent: {headLoaded?expected||'First version':'Select and load an existing deliverable'} · exact source: {form.source_version_id||'New plan'}</p>
 <fieldset disabled={!ready} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2">{field('Deliverable plan title','title',240)}{field('Deliverable format','format',240)}{field('Content pillar','content_pillar',500)}{field('Deliverable topic','topic',500)}{field('Planned version deadline','due_date',10,'date')}</div><label className="block text-xs">Private deliverable brief<textarea aria-label="Private deliverable brief" className={INPUT} maxLength={12000} value={form.brief} onChange={e=>change('brief',e.target.value)}/></label>
 {browse('contributors','existing delivery contributors')}<div className="space-y-2">{(records.contributors?.items||[]).map(r=><label key={r.id} className="flex items-start gap-2 text-xs"><input aria-label={`Delivery contributor ${r.name}`} type="checkbox" checked={form.contributor_ids.includes(r.id)} disabled={!form.contributor_ids.includes(r.id)&&form.contributor_ids.length>=20} onChange={e=>change('contributor_ids',e.target.checked?[...form.contributor_ids,r.id]:form.contributor_ids.filter(id=>id!==r.id))}/><span>{r.name} · {r.department_id||'Organization team'}</span></label>)}{form.contributor_ids.map(id=><div key={id} className="flex flex-wrap gap-2 text-xs"><span>Selected contributor · {id}</span><button type="button" className="workspace-button" onClick={()=>change('contributor_ids',form.contributor_ids.filter(v=>v!==id))}>Remove delivery contributor</button></div>)}</div>
 <label className="flex items-start gap-2 text-xs"><input aria-label="New version requires client approval" type="checkbox" checked={form.client_approval_required} onChange={e=>change('client_approval_required',e.target.checked)}/><span>Require client approval in the existing workflow. This does not record an approval.</span></label>{field('Deliverable planning change summary','change_summary',1000)}<button type="button" className="workspace-button" onClick={preview}>Review private deliverable plan</button></fieldset></fieldset>
 {history&&<section aria-label="Exact deliverable planning history" className="rounded-lg bg-[var(--anka-surface-raised)] p-3 text-sm space-y-2"><p className="font-semibold">{history.version.title} · v{history.version.version_number} · current workflow: {status(history.version.review_status)}</p><p className="text-xs">Exact version: {history.version.id} · governance {history.capabilities_state==='archived_project'?'unavailable for archived project':'checked in the canonical workflow'}</p>{history.planning?<><p>Original private brief: {history.planning.input.brief}</p><p>{history.planning.input.format} · pillar {history.planning.input.content_pillar||'Not recorded'} · topic {history.planning.input.topic||'Not recorded'} · planned deadline {history.planning.input.due_date||'Unknown'}</p><p className="text-xs">Original contributor references: {history.planning.input.contributor_ids.join(', ')||'Not recorded'}</p><p>Canonical content {history.original_canonical_content_matches?'unchanged':'changed'} · selected service {history.current_service_available?'available':'unavailable'} · project {history.project_archived?'archived':'active'}</p></>:<p>{history.planning_state==='other_engagement'?'Internal planning belongs to another engagement.':'Private planning not recorded for this exact version.'}</p>}<p>Publication and provider verification are unavailable here.</p></section>}
 {review&&<section aria-label="Review private deliverable plan" className="rounded-lg border border-[var(--anka-focus)] p-3 text-sm space-y-2"><h5 className="font-semibold">Review a new unapproved deliverable version</h5><p>{review.args.input.title} · {review.args.input.format}</p><p>{review.args.input.brief}</p><p>Pillar {review.args.input.content_pillar||'Not recorded'} · topic {review.args.input.topic||'Not recorded'} · planned deadline {review.args.input.due_date||'Unknown'}</p><p className="text-xs">Canonical owner/deadline stay {review.data.snapshot.deliverable.owner_id||'Unassigned'} / {review.data.snapshot.deliverable.due_date||'Unknown'}.</p><p className="text-xs">Selected service: {review.data.snapshot.context.service.name} · campaign plan: {review.args.planVersionId} · original source: {review.args.input.source_version_id||'New plan'}</p><p className="text-xs">Contributor references: {review.args.input.contributor_ids.join(', ')||'Not recorded'} · client approval requirement {review.args.input.client_approval_required?'enabled':'disabled'}; no approval recorded.</p><p>This review makes no changes. Confirmation saves one new canonical version and its private planning. Existing assignments, client preview, approvals and history remain in their existing workflows.</p><button type="button" className="workspace-button workspace-button-primary" disabled={off} onClick={confirm}>Confirm private deliverable plan</button></section>}
 {receipt&&<section aria-label="Original saved deliverable plan" className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><p className="font-semibold">{receipt.version.title} · v{receipt.version.version_number} · originally unapproved</p><p className="text-xs">Original canonical version: {receipt.version.id} · operation: {receipt.request_id} · actor: {receipt.actor_id}</p><p>Private planning retained by exact version. Read that exact version to check its current approval state. Assignments and publication remain unavailable here.</p></section>}
 </section>
}
