import {useEffect,useRef,useState} from 'react'
import {serializeMarketingOpportunity} from '../data/projectMarketingOpportunitiesRepository.js'
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const empty=()=>({serviceId:'',targetId:'',candidateKind:'publication',sourceUrl:'',observedOn:'',notes:'',candidateId:'',observationId:'',taskId:''})
const LABELS={canonical_targets:'targets',research_candidates:'candidates',project_tasks:'Tasks',observations:'observations',task_links:'commitments'}
const unknown=v=>v===null||v===undefined?'Unknown':String(v)
export default function ProjectMarketingOpportunitiesPanel({repository,lookup,actorId,organizationId,projectId,engagementId,signal,disabled=false,onBlockedChange}){
 const base={actorId,organizationId,projectId,engagementId},key=`anka:marketing-opportunity-operation:${actorId}:${organizationId}:${projectId}:${engagementId}:v1`
 const [form,setForm]=useState(empty),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[records,setRecords]=useState({}),[search,setSearch]=useState({canonical_targets:'',research_candidates:'',project_tasks:'',observations:'',task_links:''}),[limit,setLimit]=useState(10),[review,setReview]=useState(null),[receipt,setReceipt]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[pending,setPending]=useState(()=>{try{const p=JSON.parse(sessionStorage.getItem(key)||'null');return p===null?null:UUID.test(p.requestId||'')?{requestId:p.requestId}:{requestId:''}}catch{return {requestId:''}}})
 const alive=useRef(true),flight=useRef(false),current=useRef(null),block=useRef(onBlockedChange)
 block.current=onBlockedChange;current.current={form,dirty,busy,records,search,limit,review,pending,signal,disabled}
 const active=()=>alive.current&&!current.current.signal?.aborted
 const locked=()=>!active()||flight.current||current.current.busy||Boolean(current.current.pending)||current.current.disabled
 const blocked=dirty||busy||Boolean(review)||Boolean(pending)
 useEffect(()=>{block.current?.(blocked)},[blocked])
 useEffect(()=>()=>{alive.current=false;block.current?.(false)},[])
 const put=(name,value,setter)=>{current.current[name]=value;setter(value)}
 const hold=()=>block.current?.(true)
 function change(name,value){if(locked())return;hold();const f={...current.current.form,[name]:value};if(name==='candidateId'){f.observationId='';f.taskId='';put('records',{...current.current.records,observations:null,task_links:null},setRecords)}put('form',f,setForm);put('dirty',true,setDirty);put('review',null,setReview);setNotice('')}
 function editSearch(kind,value){if(locked())return;put('search',{...current.current.search,[kind]:value},setSearch);put('review',null,setReview)}
 async function read(kind,offset=0){if(locked())return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const c=current.current;const result=kind==='services'?await lookup.contexts({...base,campaignId:null,serviceOffset:offset,serviceLimit:25},{signal}):['observations','task_links'].includes(kind)?await repository.history({...base,candidateId:c.form.candidateId,kind,query:c.search[kind],offset,limit:c.limit},{signal}):await repository.candidates({...base,kind,query:c.search[kind],offset,limit:c.limit},{signal});if(active())put('records',{...current.current.records,[kind]:result},setRecords)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function input(kind){const f=current.current.form
  if(kind==='record_research'){if(!current.current.records.canonical_targets?.items.some(r=>r.id===f.targetId&&r.site_url))throw Error('Load and choose an existing canonical target with a safe site URL.');return serializeMarketingOpportunity({command_kind:kind,target_id:f.targetId,candidate_kind:f.candidateKind,source_url:f.sourceUrl,observed_on:f.observedOn,notes:f.notes})}
  if(!current.current.records.observations?.items.some(r=>r.id===f.observationId&&r.candidate_id===f.candidateId&&r.current_target_matches&&r.current_service_available&&!r.project_archived)||!current.current.records.project_tasks?.items.some(r=>r.id===f.taskId))throw Error('Choose an exact current research observation and an existing Marketing Project Task.');return serializeMarketingOpportunity({command_kind:kind,candidate_id:f.candidateId,observation_id:f.observationId,task_id:f.taskId})
 }
 async function preview(kind){if(locked())return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const args={...base,marketingServiceId:current.current.form.serviceId,input:input(kind)},data=await repository.preview(args,{signal});if(active())put('review',{args,data},setReview)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 const clearPending=()=>{sessionStorage.removeItem(key);put('pending',null,setPending)}
 function accept(result,message){clearPending();setReceipt(result);put('review',null,setReview);put('dirty',false,setDirty);put('form',empty(),setForm);put('records',{},setRecords);setNotice(message)}
 async function confirm(){if(locked()||!current.current.review)return;flight.current=true;hold();put('busy',true,setBusy);setError('');const chosen=current.current.review,operation={requestId:crypto.randomUUID()}
  try{sessionStorage.setItem(key,JSON.stringify(operation))}catch{flight.current=false;put('busy',false,setBusy);setError('The original operation key could not be retained. No research or Task link was saved.');return}
  put('pending',operation,setPending)
  try{const result=await repository.confirm({...chosen.args,reviewChecksum:chosen.data.review_checksum,requestId:operation.requestId,confirmed:true},{signal});if(active())accept(result,result.command_kind==='record_research'?'Research observation saved. It is not committed work.':'Existing Project Task linked. Its governance, owner and deadline remain in the Task workflow.')}catch(cause){if(active()){if(cause.knownRollback){clearPending();put('review',null,setReview);setNotice('The operation was not saved. Your fields remain; reload changed references and review again.')}setError(cause.message)}}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function recover(){if(!active()||flight.current||current.current.busy||current.current.disabled||!current.current.pending?.requestId)return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const result=await repository.recover({...base,marketingServiceId:null,requestId:current.current.pending.requestId},{signal});if(active()){if(result===null){setNotice('The original operation is still unknown. New commands remain blocked.');return}accept(result,'Recovered the original operation. No command was repeated.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function discard(){if(locked())return;put('form',empty(),setForm);put('dirty',false,setDirty);put('review',null,setReview);setError('');setNotice('Research/link draft discarded.')}
 const off=disabled||busy||Boolean(pending),services=records.services,field=(label,name,max=120,type='text')=><label className="block text-xs">{label}<input aria-label={label} className={INPUT} type={type} maxLength={max} value={form[name]} onChange={e=>change(name,e.target.value)}/></label>
 const select=(label,name,options)=><label className="block text-xs">{label}<select aria-label={label} className={INPUT} value={form[name]} onChange={e=>change(name,e.target.value)}><option value="">Choose explicitly</option>{form[name]&&!options.some(r=>r.id===form[name])&&<option value={form[name]}>Retained exact identity · {form[name]}</option>}{options.map(r=><option key={r.id} value={r.id} disabled={r.disabled}>{r.label}</option>)}</select></label>
 const paging=(kind)=><div className="flex flex-wrap gap-2 text-xs text-[var(--anka-muted)]"><span>{records[kind].items.length} shown · {records[kind].matching} matches · {records[kind].total} total</span>{records[kind].offset>0&&<button type="button" className="workspace-button" onClick={()=>read(kind,Math.max(0,records[kind].offset-limit))}>Previous {LABELS[kind]}</button>}{records[kind].has_more&&<button type="button" className="workspace-button" onClick={()=>read(kind,records[kind].offset+limit)}>Next {LABELS[kind]}</button>}</div>
 const browse=(kind,label,allowed=true)=><section className="space-y-2"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find {label}<input aria-label={`Find ${label}`} className={INPUT} value={search[kind]} maxLength={120} onChange={e=>editSearch(kind,e.target.value)}/></label><button type="button" className="workspace-button self-end" disabled={!allowed} onClick={()=>read(kind)}>Load {label}</button></div>{records[kind]&&paging(kind)}</section>
 const taskLine=task=>`${task.title||task.id} · ${task.status} · owner ${task.assignee_id||'Unassigned'} · due ${task.due_date||'Unknown'} · v${task.row_version}`
 return <section aria-label="Project marketing opportunities" className="space-y-3 border-t border-[var(--anka-line)] pt-4 break-words"><h4 className="font-semibold">Outreach research and committed work</h4><p className="text-sm text-[var(--anka-muted)]">Keep source observations separate from commitments. Link selected research to an existing governed Marketing Project Task; manage its assignment and status in the Task workflow. Provider access and submission are unavailable here.</p>
 {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status" className="text-sm text-[var(--anka-muted)]">{notice}</p>}
 {pending&&<section aria-label="Recover original outreach operation" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm space-y-2"><p>{pending.requestId?'The original outreach operation needs reconciliation. Draft and campaign changes remain blocked.':'The retained operation key is unreadable. Restore its exact UUID before confirming changes.'}</p><button type="button" className="workspace-button" disabled={busy||disabled||!pending.requestId} onClick={recover}>Check original outreach operation</button></section>}
 <fieldset disabled={off} className="space-y-4"><div className="flex flex-wrap gap-2"><button type="button" className="workspace-button" onClick={()=>read('services')}>Load outreach services</button><button type="button" className="workspace-button" disabled={!dirty&&!review} onClick={discard}>Discard outreach draft</button></div>
 {select('Outreach Marketing service','serviceId',(services?.services||[]).map(r=>({id:r.id,label:r.name})))}{services&&<div className="flex flex-wrap gap-2 text-xs"><span>{services.services.length} shown · {services.service_total} active services</span>{services.service_offset>0&&<button type="button" className="workspace-button" onClick={()=>read('services',Math.max(0,services.service_offset-25))}>Previous outreach services</button>}{services.services_has_more&&<button type="button" className="workspace-button" onClick={()=>read('services',services.service_offset+25)}>Next outreach services</button>}</div>}
 <label className="block text-xs">Opportunity page size<select aria-label="Opportunity page size" className={INPUT} value={limit} onChange={e=>{if(locked())return;put('limit',Number(e.target.value),setLimit);put('records',{services:current.current.records.services},setRecords);put('review',null,setReview)}}>{[1,5,10,25].map(n=><option key={n} value={n}>{n} complete records</option>)}</select></label><p className="text-xs text-[var(--anka-muted)]">For long source histories, choose a smaller page to retain complete records.</p>
 <section aria-label="Candidate research" className="space-y-3 rounded-lg border border-[var(--anka-line)] p-3"><h5 className="font-medium">Record research</h5>{browse('canonical_targets','canonical outreach targets')}{select('Canonical outreach target','targetId',(records.canonical_targets?.items||[]).map(r=>({id:r.id,label:r.site_name+' · '+(r.site_url||'Site URL missing'),disabled:!r.site_url})))}{records.canonical_targets?.items.filter(r=>r.id===form.targetId).map(r=><p key={r.id} className="text-xs">Manual target metadata · authority {unknown(r.domain_authority)} · estimated traffic {unknown(r.estimated_traffic)} · relevance {unknown(r.relevance_score)} · {r.cost_type} · {r.outreach_status.replaceAll('_',' ')}. Provider verification unknown.</p>)}
 <label className="block text-xs">Candidate category<select aria-label="Candidate category" className={INPUT} value={form.candidateKind} onChange={e=>change('candidateKind',e.target.value)}><option value="publication">Publication</option><option value="directory">Directory</option></select></label>{field('Research source URL','sourceUrl',2048)}{field('Research observation date UTC','observedOn',10,'date')}<label className="block text-xs">Research notes<textarea aria-label="Research notes" className={INPUT} value={form.notes} maxLength={4000} onChange={e=>change('notes',e.target.value)}/></label><button type="button" className="workspace-button" disabled={!form.serviceId||!form.targetId} onClick={()=>preview('record_research')}>Review research observation</button></section>
 <section aria-label="Existing governed Task commitment" className="space-y-3 rounded-lg border border-[var(--anka-line)] p-3"><h5 className="font-medium">Link selected research to a Project Task</h5>{browse('research_candidates','project research candidates')}{select('Exact research candidate','candidateId',(records.research_candidates?.items||[]).map(r=>({id:r.id,label:r.candidate_kind+' · '+r.normalized_site_url+' · '+r.observation_count+' observations · '+r.task_link_count+' Task links'})))}{browse('observations','original research observations',Boolean(form.candidateId))}{select('Exact research observation','observationId',(records.observations?.items||[]).map(r=>({id:r.id,label:r.observed_on+' · '+r.source_url+' · '+r.id,disabled:!r.current_target_matches||!r.current_service_available||r.project_archived})))}{browse('project_tasks','existing Marketing Project Tasks')}{select('Existing Marketing Project Task','taskId',(records.project_tasks?.items||[]).map(r=>({id:r.id,label:taskLine(r)})))}<button type="button" className="workspace-button" disabled={!form.serviceId||!form.observationId||!form.taskId} onClick={()=>preview('link_task')}>Review governed Task link</button>
 {browse('task_links','original Task commitments',Boolean(form.candidateId))}
 {records.observations?.items.map(r=><article key={r.id} className="rounded-lg bg-[var(--anka-surface-raised)] p-3 text-xs space-y-1"><p>Original research · {r.observed_on} · {r.source_url}</p><p>{r.notes||'No research notes'}</p><p>Target {r.current_target_matches?'unchanged':'changed or unavailable'} · service {r.current_service_available?'available':'unavailable'} · project {r.project_archived?'archived':'active'}</p><p>Recorded by {r.created_by} · {r.created_at} · observation {r.id}</p></article>)}
 {records.task_links?.items.map(r=><article key={r.id} className="rounded-lg bg-[var(--anka-surface-raised)] p-3 text-xs space-y-1"><p>Original commitment: {taskLine(r.reference_snapshot.task)}</p><p>Original research · {r.reference_snapshot.observation?.observed_on} · {r.reference_snapshot.observation?.source_url}</p><p>Current Task: {r.current_task?taskLine(r.current_task):'Unavailable'} · {r.current_task_matches?'unchanged':'changed or unavailable'}</p><p>Target {r.current_target_matches?'unchanged':'changed or unavailable'} · service {r.current_service_available?'available':'unavailable'} · project {r.project_archived?'archived':'active'}</p><p>Recorded by {r.created_by} · {r.created_at}. Submission unavailable.</p></article>)}
 </section></fieldset>
 {review&&<section aria-label="Review outreach operation" className="rounded-lg border border-[var(--anka-focus)] p-3 text-sm space-y-2"><h5 className="font-semibold">{review.args.input.command_kind==='record_research'?'Review research observation':'Review existing Task commitment'}</h5><p>{review.data.reference.target.site_name} · {review.data.reference.target.site_url}</p>{review.args.input.command_kind==='record_research'?<><p>Source: {review.args.input.source_url} · observed {review.args.input.observed_on} UTC</p><p>{review.args.input.notes}</p><p>{review.data.reference.existing_candidate_id?'Matches an existing research candidate; append one source observation.':'Record one research candidate and its source observation.'}</p></>:<><p>Selected original research: {review.data.reference.observation.source_url} · {review.data.reference.observation.observed_on}</p><p>Existing Task: {taskLine(review.data.reference.task)}</p>{review.data.reference.existing_task_link&&<div className="text-xs space-y-1"><p>This Task is already linked. Confirmation returns the original commitment.</p><p>Original Task: {taskLine(review.data.reference.existing_task_link.original_task)}</p><p>Original research: {review.data.reference.existing_task_link.original_research.source_url} · {review.data.reference.existing_task_link.original_research.observed_on}</p></div>}</>}<p className="text-xs">This review makes no changes. Confirmation saves research or links one existing Task. Task creation, contact, submission and provider verification are unavailable.</p><button type="button" className="workspace-button workspace-button-primary" disabled={off} onClick={confirm}>Confirm reviewed outreach operation</button></section>}
 {receipt&&<section aria-label="Original saved outreach operation" className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><p className="font-semibold">{receipt.command_kind==='record_research'?'Research recorded':'Existing Task commitment linked'}{receipt.deduplicated?' · original candidate/link retained':''}</p><p>{receipt.observation.source_url} · observed {receipt.observation.observed_on}</p>{receipt.task_link&&<p>Original Task: {taskLine(receipt.task_link.reference_snapshot.task)}</p>}<p className="text-xs">Original operation: {receipt.request_id} · actor: {receipt.actor_id}. Provider verification unknown; submission unavailable.</p></section>}
 </section>
}
