import {useEffect,useRef,useState} from 'react'
import {useAuth} from '../context/AuthContext.jsx'
import {projectCampaignPlanning as api} from '../data/projectCampaignPlanning.js'
import {serializeCampaignPlacement} from '../data/projectCampaignPlacementContracts.js'
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const REASONS={account_binding_missing:'No account is selected. External readiness remains blocked.',account_binding_unavailable:'The selected account binding is unavailable or has changed.',resource_access_verification_pending:'Selected account access still needs provider verification.'}
const initial=()=>({campaignId:'',planId:'',serviceId:'',sourceKind:'artifact_version',sourceId:'',registrationKind:'register_asset',variantLabel:'',assetId:'',variantId:'',channel:'Website',mode:'organic',accountId:'',scheduledAt:'',timeZone:'UTC',ctaLabel:'',ctaUrl:'',externalId:'',recordedUrl:'',state:'draft',contributionKind:'engagement_work_item',contributionId:'',placementId:null,revision:0})
const sourceLabel=source=>source?`${source.title} · v${source.version_number}`:'Unavailable canonical version'
const scheduleLabel=data=>{if(!data.scheduled_at)return 'Unscheduled';try{return new Intl.DateTimeFormat('en',{timeZone:data.time_zone,dateStyle:'medium',timeStyle:'short'}).format(new Date(data.scheduled_at))+' · '+data.time_zone}catch{return data.scheduled_at+' · timezone unavailable'}}
export default function ProjectCampaignPlanningPanel(props){
 const {user}=useAuth(),requestScope=useRef({signal:props.signal,revision:0})
 if(requestScope.current.signal!==props.signal)requestScope.current={signal:props.signal,revision:requestScope.current.revision+1}
 if(props.group?.kind!=='marketing'||!props.engagement?.project_id)return null
 return <ScopedCampaignPlanning key={[user?.id,props.organizationId,props.engagement.project_id,props.engagement.id,props.group.id,props.group.kind,props.membership?.role,props.membership?.departmentId,props.membership?.status,props.membership?.memberKind,requestScope.current.revision].join(':')} {...props} actorId={user?.id}/>
}
// eslint-disable-next-line no-unused-vars -- JSX consumes this scoped component.
function ScopedCampaignPlanning({organizationId,engagement,group,actorId,signal}){
 const scope={organizationId,projectId:engagement.project_id},lookupScope={...scope,engagementId:engagement.id},key=`anka:campaign-planning-operation:${actorId}:${organizationId}:${engagement.project_id}:v1`
 const [form,setForm]=useState(initial),[search,setSearch]=useState({campaign:'',source:'',work:'',asset:''}),[filter,setFilter]=useState({allCampaigns:false,channel:'',mode:'',state:'',accountId:'',query:'',startAt:'',endAt:''}),[records,setRecords]=useState({}),[review,setReview]=useState(null),[pending,setPending]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem(key)||'null');return !saved?null:UUID.test(saved.requestId||'')&&['assets','placements'].includes(saved.kind)?saved:{kind:'unreadable',requestId:''}}catch{return {kind:'unreadable',requestId:''}}}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[expanded,setExpanded]=useState(false)
 const alive=useRef(true),flight=useRef(false),current=useRef(null)
 current.current={form,search,filter,records,review,pending,busy,signal}
 const active=()=>alive.current&&!current.current.signal?.aborted
 const locked=()=>!active()||flight.current||current.current.busy||Boolean(current.current.pending)
 useEffect(()=>()=>{alive.current=false},[])
 const put=(field,value,setter)=>{current.current[field]=value;setter(value)}
 const clearReview=()=>{put('review',null,setReview);setNotice('')}
 function change(field,value){if(locked())return;clearReview();let next={...current.current.form,[field]:value};let data=current.current.records
  if(field==='campaignId'){next={...initial(),campaignId:value};data={campaigns:data.campaigns}}
  if(field==='planId'||field==='serviceId'){next={...next,assetId:'',variantId:'',placementId:null,revision:0};data={campaigns:data.campaigns,plans:data.plans,services:data.services}}
  if(field==='sourceKind'){next.sourceId='';data={...data,sources:null}}
  if(field==='assetId'){next.variantId='';data={...data,variants:null}}
  if(field==='contributionKind'){next.contributionId='';data={...data,work:null}}
  put('form',next,setForm);put('records',data,setRecords)
 }
 function editSearch(field,value){if(locked())return;clearReview();put('search',{...current.current.search,[field]:value},setSearch)}
 function editFilter(field,value){if(locked())return;clearReview();put('filter',{...current.current.filter,[field]:value},setFilter)}
 const context=f=>({...scope,campaignId:f.campaignId,planVersionId:f.planId,marketingServiceId:f.serviceId})
 async function read(kind,offset=0,row=null){
  if(locked())return;flight.current=true;put('busy',true,setBusy);setError('');clearReview();const c=current.current,f=c.form
  try{let result
   if(kind==='campaigns'||kind==='plans')result=await api.lookup.contexts({...lookupScope,campaignId:kind==='plans'?f.campaignId:null,query:kind==='campaigns'?c.search.campaign:'',offset,limit:25},{signal})
   else if(kind==='services')result=await api.lookup.contexts({...lookupScope,campaignId:f.campaignId||null,serviceOffset:offset,serviceLimit:25},{signal})
   else if(kind==='sources')result=await api.lookup.sources({...lookupScope,sourceKind:f.sourceKind,query:c.search.source,offset,limit:25},{signal})
   else if(kind==='work')result=await api.lookup.contributions({...lookupScope,kind:f.contributionKind,query:c.search.work,offset,limit:25},{signal})
   else if(kind==='assets'||kind==='variants')result=await api.assets.list({...context(f),assetId:kind==='variants'?f.assetId:null,query:kind==='assets'?c.search.asset:'',offset,limit:25},{signal})
   else if(kind==='resources')result=await api.resources.list({...scope,departmentId:'marketing',query:'',offset,limit:25},{signal})
   else if(kind==='calendar')result=await api.placements.list({...scope,campaignId:c.filter.allCampaigns?null:f.campaignId||null,channel:c.filter.channel,mode:c.filter.mode,publicationState:c.filter.state,accountBindingId:c.filter.accountId||null,query:c.filter.query,startAt:c.filter.startAt||null,endAt:c.filter.endAt||null,offset,limit:25},{signal})
   else if(kind==='history')result={row,result:await api.placements.history({...scope,placementId:row.placement_id,offset,limit:25},{signal})}
   else throw Error('Choose an explicit bounded campaign view.')
   if(active())put('records',{...current.current.records,[kind]:result},setRecords)
  }catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function registration(f){
  const chosen=current.current.records.sources?.items.find(row=>row.source_version_id===f.sourceId&&row.available)
  if(!chosen)throw Error('Find and choose an available exact approved source version.')
  return {command_kind:f.registrationKind,campaign_id:f.campaignId,plan_version_id:f.planId,marketing_service_id:f.serviceId,source_kind:f.sourceKind,source_version_id:f.sourceId,asset_id:f.registrationKind==='register_variant'?f.assetId:null,label:f.registrationKind==='register_variant'?f.variantLabel.trim():null}
 }
 function placement(f){return serializeCampaignPlacement({asset_id:f.assetId,variant_id:f.variantId||null,campaign_plan_version_id:f.planId,marketing_service_id:f.serviceId,channel:f.channel,account_binding_id:f.accountId||null,mode:f.mode,scheduled_at:f.scheduledAt||null,time_zone:f.scheduledAt?f.timeZone:null,cta:{label:f.ctaLabel,url:f.ctaUrl||null},external_id:f.externalId||null,recorded_url:f.recordedUrl||null,publication_state:f.state,contribution:f.contributionId?{kind:f.contributionKind,id:f.contributionId}:null})}
 async function preview(kind,stopRow=null,state=null){
  if(locked())return;flight.current=true;put('busy',true,setBusy);setError('');clearReview()
  try{const f=current.current.form,input=kind==='assets'?registration(f):stopRow?{...stopRow.data,publication_state:state}:placement(f),args=kind==='assets'?{...scope,input}:{...scope,campaignId:stopRow?stopRow.campaign_id:f.campaignId,placementId:stopRow?stopRow.placement_id:f.placementId,expectedRevision:stopRow?stopRow.revision_number:f.revision,input},signature=JSON.stringify(f),result=await api[kind].preview(args,{signal})
   if(kind==='assets'&&(!/^[a-f0-9]{64}$/.test(result?.review_sha256||'')||result.command_kind!==input.command_kind||result.context?.campaign_id!==input.campaign_id||result.context?.plan_version_id!==input.plan_version_id||result.context?.marketing_service_id!==input.marketing_service_id||result.source?.version_id!==input.source_version_id||result.source?.organization_id!==organizationId||result.source?.project_id!==engagement.project_id))throw Error('Exact native source review changed.')
   if(active()&&JSON.stringify(current.current.form)===signature){const snapshot={kind,args,input,result,signature,stopRow,originalSource:current.current.records.assets?.items.find(row=>row.record.id===input.asset_id)?.record.source_descriptor||current.current.records.editing?.original_reference.source};put('review',snapshot,setReview)}
  }catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function clearPending(){sessionStorage.removeItem(key);put('pending',null,setPending)}
 async function confirm(snapshot){
  if(locked()||!snapshot||current.current.review!==snapshot||JSON.stringify(current.current.form)!==snapshot.signature)return
  flight.current=true;put('busy',true,setBusy);setError('');const operation={kind:snapshot.kind,requestId:crypto.randomUUID()}
  try{sessionStorage.setItem(key,JSON.stringify(operation));put('pending',operation,setPending);await api[snapshot.kind].confirm({...snapshot.args,reviewSha256:snapshot.result.review_sha256,requestId:operation.requestId,confirmed:true},{signal})
   if(active()){clearPending();put('review',null,setReview);put('records',{...current.current.records,...(snapshot.kind==='assets'?{assets:null,variants:null}:{}),calendar:null,history:null,editing:null},setRecords);put('form',{...current.current.form,...(snapshot.kind==='assets'?{assetId:'',variantId:''}:{}),placementId:null,revision:0,state:'draft'},setForm);setNotice(snapshot.kind==='assets'?'Exact canonical source reference saved. Load shared assets to select it.':'Placement revision saved. No publication or advertising spend was performed.')}
  }catch(cause){if(active()){if(cause.knownRollback){clearPending();put('review',null,setReview)}setError(cause.message)}}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function recover(){
  const operation=current.current.pending;if(!active()||flight.current||!UUID.test(operation?.requestId||'')||!['assets','placements'].includes(operation.kind))return
  flight.current=true;put('busy',true,setBusy);setError('')
  try{const receipt=await api[operation.kind].recover({...scope,requestId:operation.requestId},{signal});if(active()){if(!receipt){setError('The original operation is not visible yet. Keep its key and check again.');return}if(!UUID.test(receipt.result?.asset_id||'')||(operation.kind==='placements'&&!UUID.test(receipt.result?.placement_id||'')))throw Error('Original campaign operation receipt changed.');clearPending();put('review',null,setReview);put('records',{},setRecords);put('form',initial(),setForm);setNotice('Recovered the original operation. No command was repeated.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function edit(row){if(locked()||!current.current.records.calendar?.items.includes(row)||row.current_reference?.context?.engagement_id!==engagement.id)return;clearReview();const d=row.data;put('form',{...current.current.form,campaignId:row.campaign_id,planId:d.campaign_plan_version_id,serviceId:d.marketing_service_id,assetId:d.asset_id,variantId:d.variant_id||'',channel:d.channel,mode:d.mode,accountId:d.account_binding_id||'',scheduledAt:d.scheduled_at||'',timeZone:d.time_zone||'UTC',ctaLabel:d.cta.label,ctaUrl:d.cta.url||'',externalId:d.external_id||'',recordedUrl:d.recorded_url||'',state:d.publication_state,contributionKind:d.contribution?.kind||'engagement_work_item',contributionId:d.contribution?.id||'',placementId:row.placement_id,revision:row.revision_number},setForm);put('records',{...current.current.records,editing:row,assets:null,variants:null,work:null},setRecords)}
 const disabled=busy||Boolean(pending),eligible=Boolean(records.campaigns?.can_write||records.plans?.can_write),ready=Boolean(form.campaignId&&form.planId&&form.serviceId),services=records.services||records.plans||records.campaigns,plan=records.plans?.items.find(row=>row.id===form.planId),editing=records.editing?.placement_id===form.placementId?records.editing:null
 const page=(data,kind,historyRow=null)=><div className="flex flex-wrap gap-2 text-xs text-[var(--anka-muted)]"><span>{data.items.length?`${data.offset+1}–${data.offset+data.items.length}`:'0'} of {data.matching??data.matching_total??data.total} matches · {data.total} total</span>{data.offset>0&&<button type="button" className="workspace-button" disabled={disabled} onClick={()=>read(kind,Math.max(0,data.offset-25),historyRow)}>Previous {kind}</button>}{data.has_more&&<button type="button" className="workspace-button" disabled={disabled} onClick={()=>read(kind,data.offset+25,historyRow)}>Next {kind}</button>}</div>
 const field=(label,name,max=120)=><label className="block text-xs">{label}<input aria-label={label} className={INPUT} maxLength={max} value={form[name]} onChange={event=>change(name,event.target.value)}/></label>
 const select=(label,name,options,placeholder='Choose explicitly')=><label className="block text-xs">{label}<select aria-label={label} className={INPUT} value={form[name]} onChange={event=>change(name,event.target.value)}><option value="">{placeholder}</option>{form[name]&&!options.some(row=>row.value===form[name])&&<option value={form[name]}>Selected exact identity · {form[name]}</option>}{options.map(row=><option key={row.value} value={row.value} disabled={row.disabled}>{row.label}</option>)}</select></label>
 const fallback=(options,value,label)=>value&&!options.some(row=>row.value===value)&&editing?[{value,label},...options]:options
 const campaigns=(records.campaigns?.items||[]).map(row=>({value:row.id,label:row.name+' · '+row.status})),plans=(records.plans?.items||[]).map(row=>({value:row.id,label:row.title+' · v'+row.version_number})),serviceOptions=(services?.services||[]).map(row=>({value:row.id,label:row.name})),assets=(records.assets?.items||[]).map(row=>({value:row.record.id,label:sourceLabel(row.record.source_descriptor)+' · '+row.source_state,disabled:row.source_state!=='available'})),variants=(records.variants?.items||[]).map(row=>({value:row.record.id,label:row.record.label+' · '+sourceLabel(row.record.source_descriptor)+' · '+row.source_state,disabled:row.source_state!=='available'||row.parent_source_state!=='available'})),accounts=(records.resources?.items||[]).map(row=>({value:row.binding.id,label:row.binding.resource_kind+' · '+row.binding.resource_key+' · '+row.state+(row.binding.engagement_id!==engagement.id?' · other engagement':' · access pending'),disabled:row.binding.engagement_id!==engagement.id}))
 return <details className="mt-5 rounded-xl border border-[var(--anka-line)] bg-[var(--anka-surface)] p-4 text-[var(--anka-ink)]" open={expanded||Boolean(pending)} onToggle={event=>setExpanded(event.currentTarget.open)}><summary className="cursor-pointer font-semibold">Campaign assets and calendar · {group.name}</summary><section aria-label="Campaign assets and calendar" className="mt-4 space-y-5">
  <p className="text-sm text-[var(--anka-muted)]">Use one existing approved source across channel placements. Each plan and variant is selected explicitly. Reporting accounts do not authorize publishing or advertising spend.</p>
  {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status" className="text-sm text-[var(--anka-success)]">{notice}</p>}{busy&&<p role="status" className="text-xs">Checking current canonical project references…</p>}
  {pending&&<section aria-label="Recover original campaign operation" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm"><p>{pending.requestId?'The original operation needs reconciliation. New commands stay blocked.':'The saved operation key is unreadable. Restore its exact kind and UUID before confirming changes.'}</p><button type="button" className="workspace-button mt-2" disabled={busy||!pending.requestId} onClick={recover}>Check original campaign operation</button></section>}
  <fieldset disabled={disabled} className="space-y-3"><h4 className="font-semibold">Choose the exact campaign plan</h4><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find campaigns<input aria-label="Campaign search" className={INPUT} maxLength={120} value={search.campaign} onChange={event=>editSearch('campaign',event.target.value)}/></label><button type="button" className="workspace-button self-end" onClick={()=>read('campaigns')}>Find campaigns</button></div>
   {select('Exact campaign','campaignId',fallback(campaigns,form.campaignId,'Current placement campaign · '+form.campaignId),'Choose an existing campaign')}{records.campaigns&&page(records.campaigns,'campaigns')}
   <button type="button" className="workspace-button" disabled={!form.campaignId} onClick={()=>read('plans')}>Load exact plan versions</button>{select('Exact campaign plan version','planId',fallback(plans,form.planId,'Current placement plan · '+form.planId),'Choose a version explicitly')}{records.plans&&page(records.plans,'plans')}
   {select('Marketing service','serviceId',fallback(serviceOptions,form.serviceId,'Current placement service · '+form.serviceId),'Choose an active service')}{services&&<div className="flex flex-wrap gap-2 text-xs"><span>{services.services.length?`${services.service_offset+1}–${services.service_offset+services.services.length}`:'0'} of {services.service_total} active services</span>{services.service_offset>0&&<button type="button" className="workspace-button" onClick={()=>read('services',Math.max(0,services.service_offset-25))}>Previous services</button>}{services.services_has_more&&<button type="button" className="workspace-button" onClick={()=>read('services',services.service_offset+25)}>Next services</button>}</div>}
   {plan&&<article aria-label="Exact campaign plan details" className="rounded-lg bg-[var(--anka-surface-raised)] p-3 text-sm space-y-1"><p className="font-medium">{plan.objective||'Objective not recorded'}</p><p>{plan.starts_on||'Start not recorded'} → {plan.ends_on||'End not recorded'} · {plan.channels?.join(', ')||'No planned channels'}</p><p>{typeof plan.audience==='string'?plan.audience:JSON.stringify(plan.audience||'Audience not recorded')}</p><p className="break-all text-xs">Message version: {plan.approved_message_version_id||'not linked'} · measurement version: {plan.measurement_plan_version_id||'not linked'}</p></article>}
  </fieldset>
  <fieldset disabled={disabled} className="space-y-3 border-t border-[var(--anka-line)] pt-4"><h4 className="font-semibold">Shared sources and variants</h4>{select('Canonical source category','sourceKind',[{value:'artifact_version',label:'Approved artifact versions'},{value:'deliverable_version',label:'Governed released file versions'}])}<div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find approved sources<input aria-label="Canonical source search" className={INPUT} maxLength={120} value={search.source} onChange={event=>editSearch('source',event.target.value)}/></label><button type="button" className="workspace-button self-end" onClick={()=>read('sources')}>Find approved sources</button></div>
   {select('Exact approved source version','sourceId',(records.sources?.items||[]).map(row=>({value:row.source_version_id,label:sourceLabel(row.source)+' · '+row.source_version_id+(row.available?'':' · unavailable'),disabled:!row.available})),'Choose an exact version')}{records.sources&&page(records.sources,'sources')}
   <div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find shared assets<input aria-label="Shared asset search" className={INPUT} maxLength={120} value={search.asset} onChange={event=>editSearch('asset',event.target.value)}/></label><button type="button" className="workspace-button self-end" disabled={!ready} onClick={()=>read('assets')}>Load shared assets</button></div>{select('Original shared asset','assetId',fallback(assets,form.assetId,sourceLabel(editing?.original_reference.source)+' · retained source'),'Choose a linked canonical source')}{records.assets&&page(records.assets,'assets')}
   {select('Source registration','registrationKind',[{value:'register_asset',label:'Link this approved version as a shared source'},{value:'register_variant',label:'Link this approved version as a variant of the selected source'}])}{form.registrationKind==='register_variant'&&field('Variant label','variantLabel',240)}<button type="button" className="workspace-button" disabled={!ready||!form.sourceId||!eligible||(form.registrationKind==='register_variant'&&!form.assetId)} onClick={()=>preview('assets')}>Review source registration</button>
   <button type="button" className="workspace-button" disabled={!ready||!form.assetId} onClick={()=>read('variants')}>Load exact variants</button>{select('Exact placement variant','variantId',fallback(variants,form.variantId,'Retained variant · '+form.variantId),'Use the original approved source')}{records.variants&&page(records.variants,'variants')}
  </fieldset>
  <fieldset disabled={disabled} className="space-y-3 border-t border-[var(--anka-line)] pt-4"><h4 className="font-semibold">{form.placementId?'Edit exact placement · revision '+form.revision:'Plan a channel placement'}</h4><div className="grid gap-3 sm:grid-cols-2">{field('Placement channel','channel')}{select('Placement mode','mode',[{value:'organic',label:'Organic'},{value:'paid',label:'Paid planning'}])}{field('Schedule UTC instant','scheduledAt',30)}{field('Schedule IANA timezone','timeZone')}<p className="text-xs text-[var(--anka-muted)] sm:col-span-2">Use an explicit UTC instant, for example 2026-10-10T09:00:00Z, and its display timezone. Blank schedule remains unscheduled.</p>{field('Call to action','ctaLabel',240)}{field('Call to action URL','ctaUrl',2048)}{field('Recorded external publication ID','externalId',500)}{field('Recorded publication URL','recordedUrl',2048)}</div>
   <button type="button" className="workspace-button" onClick={()=>read('resources')}>Load placement account bindings</button>{select('Placement account binding','accountId',fallback(accounts,form.accountId,'Retained account · '+form.accountId),'No account selected · planning remains blocked')}{records.resources&&page(records.resources,'resources')}
   {select('Contribution category','contributionKind',[{value:'engagement_work_item',label:'Existing Engagement Work Items'},{value:'project_task',label:'Existing Project Tasks'}])}<div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find existing contributions<input aria-label="Contribution search" className={INPUT} maxLength={120} value={search.work} onChange={event=>editSearch('work',event.target.value)}/></label><button type="button" className="workspace-button self-end" onClick={()=>read('work')}>Find existing contributions</button></div>{select('Existing canonical contribution','contributionId',fallback((records.work?.items||[]).map(row=>({value:row.id,label:row.title+' · due '+(row.due_date||'unset')+' · '+row.status})),form.contributionId,'Current contribution · '+form.contributionId),'No contribution linked')}{records.work&&page(records.work,'work')}<p className="text-xs text-[var(--anka-muted)]">Assignees and deadlines come from the existing canonical work record. This view creates no work or assignments.</p>
   {select('Placement record state','state',['draft','planned','paused','cancelled','recorded_published'].map(value=>({value,label:value==='recorded_published'?'Recorded published · manual evidence':value})))}<button type="button" className="workspace-button" disabled={!ready||!form.assetId||!eligible} onClick={()=>preview('placements')}>Review channel placement</button>
  </fieldset>
  {review&&<section aria-label="Review exact campaign operation" className="rounded-lg border border-[var(--anka-focus)] p-3 text-sm space-y-2"><h4 className="font-semibold">{review.kind==='assets'?'Review exact source reference':'Review exact channel placement'}</h4><p>{sourceLabel(review.result.source||review.result.reference?.source)} · {review.kind==='assets'?review.input.command_kind.replaceAll('_',' '):review.input.channel+' · '+review.input.mode+' · '+review.input.publication_state}</p>{review.kind==='assets'&&review.input.command_kind==='register_variant'&&<p>Original shared source: {sourceLabel(review.originalSource)} · variant label: {review.input.label}</p>}{review.kind==='placements'&&<><p>Variant: {review.result.reference?.variant?sourceLabel(review.result.reference.variant):'Original approved source'}</p><p>{scheduleLabel(review.input)}</p><p>Call to action: {review.input.cta.label||'none'} · existing contribution {review.result.reference?.contribution?.title||'none'}</p><p className="text-[var(--anka-warning)]">{review.result.reference?.blocking_reasons?.map(reason=>REASONS[reason]||'Current account readiness needs review.').join(' ')||'Account/provider acceptance remains separate.'}</p></>}<p>This review makes no changes. Confirmation records one exact canonical reference or placement revision. It performs no publishing, spending, generation or report fetch.</p><details className="text-xs text-[var(--anka-muted)]"><summary>Exact canonical identities</summary><p className="break-all">{JSON.stringify(review.input)}</p></details><button type="button" className="workspace-button workspace-button-primary" disabled={disabled} onClick={()=>confirm(review)}>Confirm campaign operation</button></section>}
  <fieldset disabled={disabled} className="space-y-3 border-t border-[var(--anka-line)] pt-4"><h4 className="font-semibold">Placement calendar</h4><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Calendar campaign scope<select aria-label="Calendar campaign scope" className={INPUT} value={filter.allCampaigns?'all':'selected'} onChange={event=>editFilter('allCampaigns',event.target.value==='all')}><option value="selected">Selected campaign</option><option value="all">All project campaigns</option></select></label>{['channel','query','startAt','endAt'].map(name=>{const label={channel:'Calendar channel',query:'Calendar search',startAt:'Window start UTC',endAt:'Window end UTC'}[name];return <label key={name} className="text-xs">{label}<input aria-label={label} className={INPUT} maxLength={name.endsWith('At')?30:120} value={filter[name]} onChange={event=>editFilter(name,event.target.value)}/></label>})}<label className="text-xs">Calendar mode<select aria-label="Calendar mode" className={INPUT} value={filter.mode} onChange={event=>editFilter('mode',event.target.value)}><option value="">All modes</option><option value="organic">Organic</option><option value="paid">Paid planning</option></select></label><label className="text-xs">Calendar state<select aria-label="Calendar state" className={INPUT} value={filter.state} onChange={event=>editFilter('state',event.target.value)}><option value="">All states</option>{['draft','planned','paused','cancelled','recorded_published'].map(state=><option key={state} value={state}>{state.replaceAll('_',' ')}</option>)}</select></label><label className="text-xs">Calendar account<select aria-label="Calendar account" className={INPUT} value={filter.accountId} onChange={event=>editFilter('accountId',event.target.value)}><option value="">All account bindings</option>{accounts.map(row=><option key={row.value} value={row.value}>{row.label}</option>)}</select></label></div><p className="text-xs text-[var(--anka-muted)]">Choose both UTC bounds for a window of at most 93 days. Results and history load 25 records at a time.</p><button type="button" className="workspace-button" disabled={!filter.allCampaigns&&!form.campaignId} onClick={()=>read('calendar')}>Load placement calendar</button></fieldset>
  {records.calendar&&<section aria-label="Current campaign placements" className="space-y-3">{records.calendar.items.map(row=><article key={row.placement_id} className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><p className="font-medium">{row.data.channel} · {row.data.mode} · {row.data.publication_state.replaceAll('_',' ')}</p><p>{scheduleLabel(row.data)}</p><p>{sourceLabel(row.original_reference.source)}{row.original_reference.variant?' · variant '+sourceLabel(row.original_reference.variant):''} · revision {row.revision_number}</p><p className="text-xs">{row.current_contribution?`${row.current_contribution.kind==='project_task'?'Project Task':'Engagement Work Item'}: ${row.current_contribution.title} · due ${row.current_contribution.due_date||'unset'} · ${row.current_contribution.assignee_id?'owner assigned in canonical work':'unassigned'}`:row.contribution_available?'No contribution linked.':'Original contribution is unavailable.'}</p><p className="text-xs text-[var(--anka-warning)]">{row.reason?'Current source or context unavailable. Historical placement retained.':'Account access and external acceptance remain pending.'}</p><div className="flex flex-wrap gap-2"><button type="button" className="workspace-button" disabled={disabled||!eligible||row.current_reference?.context?.engagement_id!==engagement.id} onClick={()=>edit(row)}>Edit placement</button>{['paused','cancelled'].map(state=><button key={state} type="button" className="workspace-button" disabled={disabled||!eligible||row.data.publication_state===state} onClick={()=>{if(current.current.records.calendar?.items.includes(row))preview('placements',row,state)}}>{state==='paused'?'Review pause':'Review cancellation'}</button>)}<button type="button" className="workspace-button" disabled={disabled} onClick={()=>read('history',0,row)}>Placement history</button></div></article>)}{records.calendar.items.length===0&&<p className="text-sm text-[var(--anka-muted)]">No placements match this calendar view.</p>}{page(records.calendar,'calendar')}</section>}
  {records.history&&<section aria-label="Exact placement history" className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><h4 className="font-semibold">Placement history · {records.history.result.total} revisions</h4>{records.history.result.items.map(row=><p key={row.id}>Revision {row.revision_number} · {row.publication_state.replaceAll('_',' ')} · {scheduleLabel(row.data)}</p>)}{page(records.history.result,'history',records.history.row)}</section>}
 </section></details>
}
