import _ProjectReportingControlsPanel from './ProjectReportingControlsPanel.jsx'
import _ProjectStoredReportingPanel from './ProjectStoredReportingPanel.jsx'
import {useCallback,useEffect,useRef,useState} from 'react'
import {useAuth} from '../context/AuthContext.jsx'
import {projectReportingBindings} from '../data/projectReportingBindings.js'
import {serializeProjectReportingBinding} from '../data/projectReportingBindingsContracts.js'
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const INPUT='w-full rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const LABELS={ga4_property:'GA4 property',gsc_site:'Search Console site',google_ads_customer:'Google Ads customer',meta_facebook_page:'Facebook page',meta_instagram_account:'Instagram account'}
const REASONS={verified_resource_access:'Current resource access is verified. Stored observations are available.',adapter_unavailable:'The reviewed reporting adapter is unavailable.',resource_verification_required:'Resource access needs a current provider verification.',resource_access_verification_pending:'Resource access needs provider verification.',observed_reporting_grant_missing:'Observed reporting permission is missing.',binding_context_changed:'The connector, resource or permission changed. Review the binding again.',binding_context_unavailable:'The original project or connector mapping is unavailable.',owning_context_changed:'The owning client or brand changed.',binding_paused:'Reporting is paused.',binding_revoked:'Reporting is revoked.',current_resource_unavailable:'The selected resource is unavailable.',credential_expired:'Authorization expired.',credential_expiry_unknown:'Authorization expiry is unknown.',credential_unavailable:'Authorization is unavailable.'}
const choiceKey=row=>JSON.stringify([row.connection_id,row.resource_kind,row.resource_key])
export default function ProjectReportingBindingsPanel(props){
 const {user}=useAuth(),requestScope=useRef({signal:props.signal,revision:0})
 if(requestScope.current.signal!==props.signal)requestScope.current={signal:props.signal,revision:requestScope.current.revision+1}
 if(!['website','marketing'].includes(props.group?.kind)||!props.engagement?.project_id)return null
 return <ScopedReportingBindings key={[user?.id,props.organizationId,props.engagement.project_id,props.engagement.id,props.group.id,props.group.kind,props.membership?.role,props.membership?.departmentId,props.membership?.status,props.membership?.memberKind,requestScope.current.revision].join(':')} {...props} actorId={user?.id} />
}
// eslint-disable-next-line no-unused-vars -- JSX component is consumed above.
function ScopedReportingBindings({organizationId,engagement,group,actorId,signal,onNavigationBusyChange}){
 const scope={organizationId,projectId:engagement.project_id},departmentId=group.kind,recoveryKey=`anka:reporting-binding-operation:${actorId}:${organizationId}:${engagement.project_id}:v1`
 const [pending,setPending]=useState(()=>{try{const v=JSON.parse(sessionStorage.getItem(recoveryKey)||'null');return v&&UUID.test(v.requestId||'')?v:v?{requestId:''}:null}catch{return {requestId:''}}})
 const [expanded,setExpanded]=useState(false),[query,setQuery]=useState(''),[candidateData,setCandidateData]=useState(null),[data,setData]=useState(null),[bindingQuery,setBindingQuery]=useState(''),[selection,setSelection]=useState(null),[desiredState,setDesiredState]=useState('enabled'),[review,setReview]=useState(null),[history,setHistory]=useState(null),[reportBinding,setReportBinding]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const [controlsBinding,setControlsBinding]=useState(null),[childBusy,setChildBusy]=useState(false)
 const controlsChanged=useCallback(()=>{setData(null);setCandidateData(null);setHistory(null);setReportBinding(null)},[])
 const controlsBusy=useCallback(value=>{latest.current.childBusy=value;setChildBusy(value)},[])
 const alive=useRef(true),flight=useRef(false),sequence=useRef(0),latest=useRef(null)
 latest.current={pending,signal,busy,childBusy,query,bindingQuery,candidateData,data,selection,desiredState,review}
 const active=()=>alive.current&&!latest.current.signal?.aborted
 const locked=()=>!active()||flight.current||latest.current.busy||latest.current.childBusy||Boolean(latest.current.pending)
 const working=value=>{latest.current.busy=value;setBusy(value)}
 useEffect(()=>()=>{alive.current=false;sequence.current+=1},[])
 function resetReview(){latest.current.review=null;setReview(null);setHistory(null);setNotice('')}
 async function load(kind='bindings',offset=0){
  if(locked())return;const seq=++sequence.current;working(true);setError('');resetReview()
  try{const result=await projectReportingBindings[kind==='candidates'?'candidates':'list']({...scope,engagementId:engagement.id,departmentId,query:kind==='candidates'?latest.current.query:latest.current.bindingQuery,offset,limit:25},{signal});if(active()&&seq===sequence.current){if(kind==='candidates')setCandidateData(result);else setData(result)}}catch(cause){if(active()&&seq===sequence.current){if(kind==='candidates')setCandidateData(null);else setData(null);setError(cause.message)}}finally{if(active()&&seq===sequence.current)working(false)}
 }
 function selectCandidate(key){
  if(locked())return;const row=latest.current.candidateData?.items.find(item=>choiceKey(item)===key);if(!row||!row.available_for_binding)return
  resetReview();const next={kind:'candidate',row};latest.current.selection=next;latest.current.desiredState='enabled';setSelection(next);setDesiredState('enabled')
 }
 function editBinding(row){
  if(locked()||!latest.current.data?.items.includes(row))return;resetReview();const next={kind:'binding',row};latest.current.selection=next;latest.current.desiredState=row.state;setSelection(next);setDesiredState(row.state)
 }
 function changeState(state){if(locked()||!latest.current.selection)return;resetReview();latest.current.desiredState=state;setDesiredState(state)}
 function inputOf(current){
  const selected=current.selection;if(!selected)throw Error('Choose an existing resource or binding first.')
  const b=selected.kind==='binding'?selected.row.binding:selected.row
  return serializeProjectReportingBinding({binding_id:selected.kind==='binding'?b.id:null,expected_revision:selected.kind==='binding'?selected.row.revision_number:0,engagement_id:selected.kind==='binding'?b.engagement_id:engagement.id,department_id:selected.kind==='binding'?b.department_id:departmentId,connection_id:b.connection_id,resource_kind:b.resource_kind,resource_key:b.resource_key,permitted_operations:['reporting_read'],state:current.desiredState})
 }
 const signature=current=>JSON.stringify(inputOf(current))
 async function preview(){
  if(locked())return;flight.current=true;working(true);setError('');const selected=latest.current.selection
  try{const input=inputOf(latest.current),expected=JSON.stringify(input),result=await projectReportingBindings.preview({...scope,input},{signal});if(active()&&latest.current.selection===selected&&signature(latest.current)===expected){const snapshot={input,signature:expected,result};latest.current.review=snapshot;setReview(snapshot)}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())working(false)}
 }
 async function confirm(snapshot){
  if(locked()||!snapshot||latest.current.review!==snapshot||signature(latest.current)!==snapshot.signature)return
  flight.current=true;working(true);setError('');const operation={requestId:crypto.randomUUID()}
  try{
   sessionStorage.setItem(recoveryKey,JSON.stringify(operation));latest.current.pending=operation;setPending(operation)
   await projectReportingBindings.confirm({...scope,input:snapshot.input,reviewSha256:snapshot.result.review_sha256,requestId:operation.requestId,confirmed:true},{signal})
   if(active()){sessionStorage.removeItem(recoveryKey);latest.current.pending=null;setPending(null);latest.current.review=null;setReview(null);latest.current.selection=null;setSelection(null);setCandidateData(null);setData(null);setNotice('Reporting binding revision saved. Provider verification is still required before reporting.')}
  }catch(cause){if(active()){if(cause.knownRollback){sessionStorage.removeItem(recoveryKey);latest.current.pending=null;setPending(null);latest.current.review=null;setReview(null);setCandidateData(null);setData(null)}setError(cause.message)}}finally{flight.current=false;if(active())working(false)}
 }
 async function recover(){
  if(!active()||flight.current||!UUID.test(latest.current.pending?.requestId||''))return;flight.current=true;working(true);setError('')
  try{const receipt=await projectReportingBindings.recover({...scope,requestId:latest.current.pending.requestId},{signal});if(active()){if(!receipt){setError('The original operation is not yet visible. Keep its saved key and check again.');return}sessionStorage.removeItem(recoveryKey);latest.current.pending=null;setPending(null);latest.current.review=null;setReview(null);latest.current.selection=null;setSelection(null);setData(null);setCandidateData(null);setNotice('Recovered the original binding revision. No command was repeated.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())working(false)}
 }
 async function inspect(row,offset=0){
  if(locked())return;const seq=++sequence.current;working(true);setError('');resetReview()
  try{const result=await projectReportingBindings.history({...scope,bindingId:row.binding.id,offset,limit:25},{signal});if(active()&&seq===sequence.current)setHistory({row,result})}catch(cause){if(active()&&seq===sequence.current)setError(cause.message)}finally{if(active()&&seq===sequence.current)working(false)}
 }
 useEffect(()=>{onNavigationBusyChange?.(childBusy||busy||Boolean(pending)||Boolean(review)||Boolean(selection&&(selection.kind==='binding'?desiredState!==selection.row.state:desiredState!=='enabled')));return()=>onNavigationBusyChange?.(false)},[childBusy,busy,pending,review,selection,desiredState,onNavigationBusyChange])
 const disabled=childBusy||busy||Boolean(pending),binding=selection?.kind==='binding'?selection.row.binding:selection?.row,context=selection?.kind==='binding'?selection.row.current_context:selection?.row.context
 const pagination=(result,previous,next)=><div className="flex flex-wrap gap-2"><span className="text-xs text-[var(--anka-muted)]">{result.items.length?`${result.offset+1}–${result.offset+result.items.length}`:'0'} of {result.matching??result.total} matches · {result.total} total</span>{result.offset>0&&<button type="button" className="workspace-button" disabled={disabled} onClick={previous}>Previous resources</button>}{result.has_more&&<button type="button" className="workspace-button" disabled={disabled} onClick={next}>Next resources</button>}</div>
 return <details className="mt-5 rounded-xl border border-[var(--anka-line)] bg-[var(--anka-surface)] p-4 text-[var(--anka-ink)]" open={expanded||Boolean(pending)||childBusy} onToggle={event=>setExpanded(event.currentTarget.open)}>
  <summary className="cursor-pointer font-semibold">Project reporting resources · {group.name}</summary>
  <section aria-label="Project reporting resources" className="mt-4 space-y-4">
   <p className="text-sm text-[var(--anka-muted)]">Choose a resource from an existing connector mapping for this project. Reporting permission is separate from publishing or advertising spend. Each saved resource shows its current verification and refresh state.</p>
   {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status" className="text-sm text-[var(--anka-success)]">{notice}</p>}
   {pending&&<section aria-label="Recover original reporting operation" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm"><p>{pending.requestId?'The original operation needs reconciliation. New commands stay blocked.':'The saved key is unreadable. Restore its exact operation UUID before confirming new changes.'}</p><button type="button" className="workspace-button mt-2" disabled={busy||!pending.requestId} onClick={recover}>Check original reporting operation</button></section>}
   <fieldset disabled={disabled} className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find mapped resources<input aria-label="Mapped reporting resource search" maxLength={120} className={INPUT} value={query} onChange={event=>{if(!locked()){resetReview();setQuery(event.target.value);latest.current.query=event.target.value}}}/></label><button type="button" className="workspace-button self-end" onClick={()=>load('candidates')}>Find mapped resources</button>
   {candidateData&&<><label className="text-xs sm:col-span-2">Exact existing resource<select aria-label="Mapped reporting resource" value={selection?.kind==='candidate'?choiceKey(selection.row):''} className={INPUT} onChange={event=>selectCandidate(event.target.value)}><option value="">Choose an existing mapped resource</option>{candidateData.items.map(row=><option key={choiceKey(row)} value={choiceKey(row)} disabled={!row.available_for_binding}>{row.display_name} · {LABELS[row.resource_kind]} · {row.resource_key||'No selected resource'}{row.available_for_binding?'':' · unavailable'}</option>)}</select></label><div className="sm:col-span-2">{pagination(candidateData,()=>load('candidates',Math.max(0,candidateData.offset-25)),()=>load('candidates',candidateData.offset+25))}</div></>}
   <label className="text-xs">Find project bindings<input aria-label="Project reporting binding search" maxLength={120} className={INPUT} value={bindingQuery} onChange={event=>{if(!locked()){resetReview();setBindingQuery(event.target.value);latest.current.bindingQuery=event.target.value}}}/></label><button type="button" className="workspace-button self-end" onClick={()=>load()}>Load project bindings</button></fieldset>
   {busy&&<p role="status" className="text-xs text-[var(--anka-muted)]">Checking current project mappings…</p>}
   {data&&<section aria-label="Saved project resource bindings" className="space-y-3">{data.items.map(row=><article key={row.binding.id} className="rounded-lg border border-[var(--anka-line)] p-3 text-sm"><p className="break-all font-medium">{LABELS[row.binding.resource_kind]} · {row.binding.resource_key}</p><p className="mt-1 text-xs">Revision {row.revision_number} · {row.state} · {row.binding.department_id==='website'?'Website':'Marketing'}</p><p className="mt-1 text-xs text-[var(--anka-muted)]">{REASONS[row.reason]||'Reporting acceptance is pending.'}</p>{row.reporting_status&&<p className="mt-1 text-xs text-[var(--anka-muted)]">{row.reporting_status.refresh.policy_id?`Refresh ${row.reporting_status.refresh.enabled?'enabled':'paused'} · Cadence ${row.reporting_status.refresh.cadence_seconds}s · History ${row.reporting_status.refresh.history_days} days`:'Refresh settings have not been configured.'}{row.reporting_status.refresh.queued?` · Original job: ${row.reporting_status.refresh.job.state}`:''}</p>}<div className="mt-2 flex flex-wrap gap-2"><button type="button" className="workspace-button" disabled={disabled} onClick={()=>editBinding(row)}>Review binding</button><button type="button" className="workspace-button" disabled={disabled} onClick={()=>inspect(row)}>Binding history</button><button type="button" className="workspace-button" disabled={disabled} onClick={()=>{if(locked())return;resetReview();setReportBinding(row.binding.id)}}>Stored report</button><button type="button" className="workspace-button" disabled={disabled||Boolean(review)} onClick={()=>{if(locked())return;resetReview();setControlsBinding(row.binding.id)}}>Refresh controls</button></div></article>)}{data.items.length===0&&<p className="text-sm text-[var(--anka-muted)]">No project resource bindings match this view.</p>}{pagination(data,()=>load('bindings',Math.max(0,data.offset-25)),()=>load('bindings',data.offset+25))}</section>}
   {selection&&<section aria-label="Selected reporting resource" className="rounded-lg bg-[var(--anka-surface-raised)] p-3 space-y-3"><h4 className="break-all font-medium">{LABELS[binding.resource_kind]} · {binding.resource_key}</h4><p className="text-xs">Reporting reads only · authorization {context?.credential_state?.replaceAll('_',' ')||'unavailable'} · {context?.grant_provenance==='observed'&&context?.reporting_scope_granted===true?'reporting permission observed':'observed reporting scope missing'}. Selected-resource access remains pending.</p><label className="block text-xs">Binding state<select aria-label="Reporting binding state" className={INPUT} value={desiredState} disabled={disabled} onChange={event=>changeState(event.target.value)}><option value="enabled">Enabled when access is verified</option><option value="paused">Paused</option><option value="revoked">Revoked</option></select></label><button type="button" className="workspace-button" disabled={disabled} onClick={preview}>Review reporting binding</button></section>}
   {(review||selection&&(selection.kind==='binding'?desiredState!==selection.row.state:desiredState!=='enabled'))&&<button type="button" className="workspace-button" disabled={disabled} onClick={()=>{if(locked())return;resetReview();latest.current.selection=null;setSelection(null);setDesiredState('enabled');latest.current.desiredState='enabled'}}>Discard binding review</button>}
   {review&&<section aria-label="Review exact reporting binding" className="rounded-lg border border-[var(--anka-focus)] p-3 text-sm space-y-2"><h4 className="font-semibold">Review exact reporting binding</h4><p className="break-all">{LABELS[review.input.resource_kind]} · {review.input.resource_key} · {review.input.state}</p><p>{review.result.context?.revocation_only?'References the original client, brand and mapping. Pausing or revoking remains possible when the current mapping is unavailable.':'Existing project client, brand, engagement and connector mapping checked.'} This review makes no changes.</p><p>Records one reporting-only binding revision. Provider verification remains pending; this command does not publish, spend or fetch reports.</p><details className="text-xs text-[var(--anka-muted)]"><summary>Exact mapping reference</summary><p className="break-all">Connector {review.input.connection_id} · engagement {review.input.engagement_id} · expected revision {review.input.expected_revision}</p></details><button type="button" className="workspace-button workspace-button-primary" disabled={disabled} onClick={()=>confirm(review)}>Confirm reporting binding</button></section>}
   <_ProjectReportingControlsPanel organizationId={organizationId} projectId={engagement.project_id} actorId={actorId} bindingId={controlsBinding} signal={signal} blocked={busy||Boolean(pending)||Boolean(review)||Boolean(selection&&(selection.kind==='binding'?desiredState!==selection.row.state:desiredState!=='enabled'))} onBusyChange={controlsBusy} onChanged={controlsChanged}/>
   {reportBinding&&<_ProjectStoredReportingPanel key={[organizationId,engagement.project_id,reportBinding].join(':')} organizationId={organizationId} projectId={engagement.project_id} bindingId={reportBinding} signal={signal} blocked={disabled} onOpenRefreshControls={()=>{if(locked())return;setControlsBinding(reportBinding);setReportBinding(null)}}/>}
   {history&&<section aria-label="Reporting binding history" className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><h4 className="font-semibold">Binding history · {history.result.total} revisions</h4>{history.result.items.map(row=><p key={row.id}>Revision {row.revision_number} · {row.state} · {row.changed_at}</p>)}{history.result.has_more&&<button type="button" className="workspace-button" disabled={disabled} onClick={()=>inspect(history.row,history.result.offset+25)}>More binding history</button>}</section>}
  </section>
 </details>
}
