import {useEffect,useRef,useState} from 'react'
import {serializeProjectCampaignPlan} from '../data/projectCampaignPlanCommandsRepository.js'
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const empty=service=>({title:'',objective:'',channels:'',starts_on:'',ends_on:'',audience:'',landing_page_url:'',planned_budget:'',currency_code:'',approved_message_version_id:'',measurement_plan_version_id:'',creative_requirements:[],change_summary:'',source_plan_version_id:'',marketing_service_id:service||'',owner_id:'',strategy_version_ids:[]})
const REASONS={campaign_owner_missing:'Campaign owner is missing.',approved_message_missing:'An approved message is not linked.',approved_measurement_plan_missing:'An approved measurement plan is not linked.',approved_audience_strategy_missing:'An approved audience strategy is not linked.',campaign_dates_incomplete:'Campaign dates are incomplete.'}
export default function ProjectCampaignPlanEditor({repository,actorId,organizationId,projectId,engagementId,campaignId,selectedPlanId,expectedLatestVersionId,headLoaded,serviceId,disabled=false,signal,onBlockedChange,refreshHead,onHeadLoaded}){
 const base={actorId,organizationId,projectId,engagementId,campaignId},key=`anka:campaign-plan-operation:${actorId}:${organizationId}:${projectId}:${engagementId}:v1`
 const [headStale,setHeadStale]=useState(false),[form,setForm]=useState(()=>empty(serviceId)),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[review,setReview]=useState(null),[receipt,setReceipt]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[records,setRecords]=useState({}),[search,setSearch]=useState({owner:'',strategy:'',message:'',measurement:''}),[pending,setPending]=useState(()=>{try{const v=JSON.parse(sessionStorage.getItem(key)||'null');return v===null?null:UUID.test(v.requestId||'')?v:{requestId:''}}catch{return {requestId:''}}})
 const alive=useRef(true),flight=useRef(false),current=useRef(null),block=useRef(onBlockedChange)
 block.current=onBlockedChange;current.current={form,dirty,busy,review,pending,signal,disabled,search,headStale}
 const active=()=>alive.current&&!current.current.signal?.aborted
 const locked=()=>!active()||flight.current||current.current.busy||Boolean(current.current.pending)||current.current.disabled
 const blocked=dirty||busy||Boolean(review)||Boolean(pending)
 useEffect(()=>{block.current?.(blocked)},[blocked])
 useEffect(()=>()=>{alive.current=false;block.current?.(false)},[])
 function put(name,value,setter){current.current[name]=value;setter(value)}
 function hold(){block.current?.(true)}
 function change(name,value){if(locked())return;hold();put('form',{...current.current.form,[name]:value},setForm);put('dirty',true,setDirty);put('review',null,setReview);setNotice('')}
 function input(){const f=current.current.form;return serializeProjectCampaignPlan({...f,channels:f.channels.split(',').map(v=>v.trim()).filter(Boolean),starts_on:f.starts_on||null,ends_on:f.ends_on||null,landing_page_url:f.landing_page_url||null,planned_budget:f.planned_budget===''?null:Number(f.planned_budget),currency_code:f.currency_code||null,approved_message_version_id:f.approved_message_version_id||null,measurement_plan_version_id:f.measurement_plan_version_id||null,source_plan_version_id:f.source_plan_version_id||null,owner_id:f.owner_id||null,creative_requirements:f.creative_requirements.map(r=>({...r,due_date:r.due_date||null,message_version_id:r.message_version_id||null}))})}
 async function read(kind,offset=0){if(locked())return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const data=await repository.candidates({...base,kind,query:current.current.search[kind],offset,limit:25},{signal});if(active())setRecords(v=>({...v,[kind]:data}))}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function loadSelected(){if(locked()||!selectedPlanId)return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const data=await repository.getVersion({...base,planVersionId:selectedPlanId},{signal});if(!active())return;const p=data.plan,l=data.links;put('form',{title:p.title,objective:p.objective,channels:p.channels.join(', '),starts_on:p.starts_on||'',ends_on:p.ends_on||'',audience:p.audience||'',landing_page_url:p.landing_page_url||'',planned_budget:data.budget?.planned_budget??'',currency_code:data.budget?.currency_code||'',approved_message_version_id:p.approved_message_version_id||'',measurement_plan_version_id:p.measurement_plan_version_id||'',creative_requirements:data.requirements.map(r=>({format:r.format,intended_placement:r.intended_placement,message_version_id:r.message_version_id||'',due_date:r.due_date||''})),change_summary:'',source_plan_version_id:p.id,marketing_service_id:serviceId||l?.marketing_service_id||'',owner_id:l?.owner_id||'',strategy_version_ids:l?.strategy_version_ids||[]},setForm);put('dirty',true,setDirty);put('review',null,setReview);setReceipt(null);setNotice(`Loaded exact version ${p.version_number} as the source of a new unapproved draft.`)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function preview(){if(locked()||!campaignId||!headLoaded||current.current.headStale)return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview)
  try{const value=input(),args={...base,expectedLatestVersionId,input:value},result=await repository.preview(args,{signal});if(active())put('review',{args,result},setReview)}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function reloadHead(){if(locked()||!campaignId)return;flight.current=true;hold();put('busy',true,setBusy);setError('');put('review',null,setReview);try{const result=await refreshHead();if(active()){onHeadLoaded(result);setHeadStale(false);setNotice('Current canonical plan head loaded. Your draft fields remain.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}}
 function clearPending(){sessionStorage.removeItem(key);put('pending',null,setPending)}
 async function confirm(){if(locked()||!current.current.review)return;flight.current=true;hold();put('busy',true,setBusy);setError('');const chosen=current.current.review;const operation={requestId:crypto.randomUUID()}
  try{sessionStorage.setItem(key,JSON.stringify(operation))}catch{flight.current=false;put('busy',false,setBusy);setError('The original operation key could not be retained. No draft was saved.');return}
  put('pending',operation,setPending)
  try{const result=await repository.confirm({...chosen.args,confirmed:true,reviewChecksum:chosen.result.review_checksum,requestId:operation.requestId},{signal});if(active()){clearPending();setReceipt(result);setHeadStale(true);put('review',null,setReview);put('dirty',false,setDirty);put('form',empty(serviceId),setForm);setNotice(`Saved unapproved canonical plan version ${result.plan.version_number}. Reload exact versions before another draft.`)}}catch(cause){if(active()){setError(cause.message);if(cause.knownRollback){setHeadStale(true);clearPending();put('review',null,setReview);setNotice('The draft was not saved. Your fields remain; reload the plan head and review again.')}}}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 async function recover(){if(flight.current||busy||disabled||!pending?.requestId||!active())return;flight.current=true;hold();put('busy',true,setBusy);setError('')
  try{const result=await repository.recover({...base,campaignId:null,requestId:pending.requestId},{signal});if(!active())return;if(result===null){setNotice('The original operation is still unknown. New commands remain blocked.');return}clearPending();setReceipt(result);setHeadStale(true);put('review',null,setReview);put('dirty',false,setDirty);put('form',empty(serviceId),setForm);setNotice('Recovered the original canonical version. No write was repeated.')}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())put('busy',false,setBusy)}
 }
 function discard(){if(locked())return;put('form',empty(serviceId),setForm);put('dirty',false,setDirty);put('review',null,setReview);setNotice('Draft discarded.');setError('')}
 function requirement(index,name,value){const rows=current.current.form.creative_requirements.map((r,i)=>i===index?{...r,[name]:value}:r);change('creative_requirements',rows)}
 const off=disabled||busy||Boolean(pending),ready=Boolean(campaignId&&headLoaded&&serviceId&&!headStale),field=(label,name,max=120,type='text')=><label className="block text-xs">{label}<input aria-label={label} type={type} className={INPUT} maxLength={max} value={form[name]} onChange={e=>change(name,e.target.value)}/></label>
 const select=(label,name,options,placeholder)=><label className="block text-xs">{label}<select aria-label={label} className={INPUT} value={form[name]} onChange={e=>change(name,e.target.value)}><option value="">{placeholder}</option>{form[name]&&!options.some(o=>o.value===form[name])&&<option value={form[name]}>Retained exact identity · {form[name]}</option>}{options.map(o=><option key={o.value} value={o.value} disabled={o.disabled}>{o.label}</option>)}</select></label>
 const sourceOptions=kind=>(records[kind]?.items||[]).map(row=>({value:row.id,label:row.source?`${row.source.title} · v${row.source.version_number}`:'Unavailable original source',disabled:!row.available}))
 const candidates=(kind,label)=><section className="space-y-2"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><label className="text-xs">Find {label}<input aria-label={`Find ${label}`} className={INPUT} maxLength={120} value={search[kind]} onChange={e=>{if(locked())return;setSearch(v=>({...v,[kind]:e.target.value}));put('review',null,setReview)}}/></label><button type="button" className="workspace-button self-end" onClick={()=>read(kind)}>Load {label}</button></div>{records[kind]&&<div className="flex flex-wrap gap-2 text-xs text-[var(--anka-muted)]"><span>{records[kind].items.length} shown · {records[kind].matching} matches · {records[kind].total} total</span>{records[kind].offset>0&&<button type="button" className="workspace-button" onClick={()=>read(kind,Math.max(0,records[kind].offset-25))}>Previous {label}</button>}{records[kind].has_more&&<button type="button" className="workspace-button" onClick={()=>read(kind,records[kind].offset+25)}>Next {label}</button>}</div>}</section>
 return <section aria-label="Canonical campaign plan editor" className="space-y-3 border-t border-[var(--anka-line)] pt-4"><h4 className="font-semibold">Campaign plan</h4><p className="text-sm text-[var(--anka-muted)]">Choose a campaign, load its exact versions and select a Marketing service. Save an unapproved draft after reviewing its source and owner. Incomplete plans remain unavailable for publication.</p>
 {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status" className="text-sm text-[var(--anka-muted)]">{notice}</p>}
 {pending&&<section aria-label="Recover original plan command" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm space-y-2"><p>{pending.requestId?'The original plan command needs reconciliation. Draft and campaign changes remain blocked.':'The retained operation key is unreadable. Restore its exact UUID before saving another plan.'}</p><button type="button" className="workspace-button" disabled={busy||disabled||!pending.requestId} onClick={recover}>Check original plan operation</button></section>}
 <fieldset disabled={off||!campaignId} className="space-y-3"><div className="flex flex-wrap gap-2"><button type="button" className="workspace-button" onClick={reloadHead}>Reload current canonical plan head</button><button type="button" className="workspace-button" disabled={!selectedPlanId} onClick={loadSelected}>Load selected plan for editing</button><button type="button" className="workspace-button" disabled={!dirty&&!review} onClick={discard}>Discard plan draft</button></div><p className="break-words text-xs text-[var(--anka-muted)]">Canonical parent: {headLoaded?expectedLatestVersionId||'First plan version':'Load exact plan versions first'} · source plan: {form.source_plan_version_id||'New draft'}</p>
 <div className="grid gap-3 sm:grid-cols-2">{field('Plan title','title',180)}{field('Plan channels · comma separated','channels',2400)}{field('Campaign start date','starts_on',10,'date')}{field('Campaign end date','ends_on',10,'date')}{field('Planning budget','planned_budget',40)}{field('Planning currency','currency_code',3)}{field('Campaign landing URL','landing_page_url',2000)}</div>
 <label className="block text-xs">Plan objective<textarea aria-label="Plan objective" className={INPUT} maxLength={4000} value={form.objective} onChange={e=>change('objective',e.target.value)}/></label><label className="block text-xs">Audience strategy notes<textarea aria-label="Audience strategy notes" className={INPUT} maxLength={4000} value={form.audience} onChange={e=>change('audience',e.target.value)}/></label>
 {candidates('owner','campaign owners')}{select('Campaign owner','owner_id',(records.owner?.items||[]).map(row=>({value:row.id,label:row.name})),'Owner not selected')}
 {candidates('strategy','audience strategies')}<div className="space-y-2">{sourceOptions('strategy').map(row=><label key={row.value} className="flex items-start gap-2 text-xs"><input aria-label={`Strategy ${row.label}`} type="checkbox" checked={form.strategy_version_ids.includes(row.value)} disabled={row.disabled||!form.strategy_version_ids.includes(row.value)&&form.strategy_version_ids.length>=20} onChange={e=>change('strategy_version_ids',e.target.checked?[...form.strategy_version_ids,row.value]:form.strategy_version_ids.filter(id=>id!==row.value))}/><span>{row.label}</span></label>)}{form.strategy_version_ids.map(id=><div key={id} className="flex flex-wrap gap-2 text-xs"><span className="break-words">Selected exact strategy · {id}</span><button type="button" className="workspace-button" onClick={()=>change('strategy_version_ids',form.strategy_version_ids.filter(v=>v!==id))}>Remove strategy</button></div>)}</div>
 {candidates('message','approved messages')}{select('Approved campaign message','approved_message_version_id',sourceOptions('message'),'Message not linked')}
 {candidates('measurement','measurement plans')}{select('Approved measurement plan','measurement_plan_version_id',sourceOptions('measurement'),'Measurement not linked')}
 <section className="space-y-3"><h5 className="font-medium text-sm">Creative requirements</h5>{form.creative_requirements.map((row,index)=><div key={index} className="grid gap-3 rounded-lg border border-[var(--anka-line)] p-3 sm:grid-cols-2">{['format','intended_placement','due_date'].map(name=>{const label={format:'Creative format',intended_placement:'Creative intended placement',due_date:'Creative deadline'}[name]+' '+(index+1);return <label key={name} className="text-xs">{label}<input aria-label={label} type={name==='due_date'?'date':'text'} className={INPUT} maxLength={name==='format'?240:name==='intended_placement'?500:10} value={row[name]} onChange={e=>requirement(index,name,e.target.value)}/></label>})}<label className="text-xs">Exact creative message<select aria-label={`Creative message ${index+1}`} className={INPUT} value={row.message_version_id} onChange={e=>requirement(index,'message_version_id',e.target.value)}><option value="">No approved message linked</option>{row.message_version_id&&!sourceOptions('message').some(o=>o.value===row.message_version_id)&&<option value={row.message_version_id}>Retained exact version · {row.message_version_id}</option>}{sourceOptions('message').map(o=><option key={o.value} value={o.value} disabled={o.disabled}>{o.label}</option>)}</select></label><button type="button" className="workspace-button" onClick={()=>change('creative_requirements',form.creative_requirements.filter((_,i)=>i!==index))}>Remove creative requirement {index+1}</button></div>)}<button type="button" className="workspace-button" disabled={form.creative_requirements.length>=100} onClick={()=>change('creative_requirements',[...form.creative_requirements,{format:'',intended_placement:'',message_version_id:'',due_date:''}])}>Add creative requirement</button></section>
 {field('Plan change summary','change_summary',1000)}<p className="break-words text-xs text-[var(--anka-muted)]">Selected Marketing service: {form.marketing_service_id||'Choose an active service above'}. Existing Tasks, Work Items and assignments are preserved.</p><button type="button" className="workspace-button" disabled={!ready} onClick={preview}>Review canonical plan draft</button></fieldset>
 {review&&<section aria-label="Review canonical plan draft" className="rounded-lg border border-[var(--anka-focus)] p-3 text-sm space-y-2 break-words"><h5 className="font-semibold">Review unapproved campaign draft</h5><p>{review.args.input.title} · {review.args.input.channels.join(', ')}</p><p>{review.args.input.objective}</p><p>{review.args.input.starts_on||'Start unknown'} → {review.args.input.ends_on||'End unknown'} · budget {review.args.input.planned_budget===null?'Unknown':review.args.input.planned_budget+' '+review.args.input.currency_code}</p><p className="break-words">Owner: {review.result.snapshot.owner?.user_id||'Not selected'} · service: {review.result.snapshot.service.name}</p><p>Audience: {review.args.input.audience||'Not recorded'}</p><p className="break-words">Landing URL: {review.args.input.landing_page_url||'Not linked'}</p>{review.args.input.creative_requirements.map((row,index)=><p key={index} className="break-words text-xs">Creative {index+1}: {row.format} · {row.intended_placement} · deadline {row.due_date||'Unknown'} · message {row.message_version_id||'Not linked'}</p>)}<p className="break-words text-xs">Parent version: {review.args.expectedLatestVersionId||'First version'} · source plan: {review.args.input.source_plan_version_id||'New draft'}</p>{review.result.snapshot.sources.map(source=><p key={source.usage+source.version_id} className="break-words text-xs">{source.usage}: {source.title} · v{source.version_number} · original approval {source.approval.approval_id}</p>)}{review.result.snapshot.blocking_reasons.map(reason=><p key={reason} className="text-[var(--anka-warning)]">{REASONS[reason]||reason}</p>)}<p>This review makes no changes. Confirmation saves one canonical unapproved version and its exact links. Publication and spend remain unavailable.</p><button type="button" className="workspace-button workspace-button-primary" disabled={off} onClick={confirm}>Confirm canonical plan draft</button></section>}
 {receipt&&<section aria-label="Original saved campaign plan" className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2"><p className="font-semibold">{receipt.plan.title} · v{receipt.plan.version_number} · unapproved draft</p><p className="break-words text-xs">Original operation: {receipt.request_id} · original actor: {receipt.actor_id}</p><p className="break-words text-xs">Canonical version: {receipt.plan.id} · parent: {receipt.plan.parent_version_id||'First version'} · campaign: {receipt.campaign_id}</p><p>Publication and spend are unavailable.</p></section>}
 </section>
}
