import _WebsitePageVersionChecksPanel from './WebsitePageVersionChecksPanel.jsx'
import {useEffect,useRef,useState} from 'react'
import {projectWebsiteSeoObservations as api} from '../data/projectWebsiteSeoObservations.js'
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const LABELS={page_audits:'Stored page checks',planned_targets:'Planned keyword targets',query_observations:'Observed query metadata'}
const REASONS={tracked_page_unlinked:'Link an existing tracked page before inspecting observations.',no_stored_page_observation:'No stored page check is available.',legacy_observation_not_version_bound:'Legacy evidence is not bound to this exact architecture and implementation version.',implementation_changed_after_observation:'Implementation changed after the stored check.',tracked_page_changed_after_observation:'The tracked page changed after the stored check.',recorded_live_url_differs_from_tracked_page:'The recorded live URL differs from the tracked page.',architecture_version_differs_from_seo_link:'The selected architecture version differs from the SEO link.',archived:'Archived project; retained history only.',page_absent_from_version:'This page is absent from the selected architecture version.',approved_source_unavailable:'The current approved architecture source is unavailable.',legacy_resource_provenance_unknown:'Legacy provider records do not identify an exact historical resource.',reporting_binding_missing:'Choose an existing project Search Console binding to inspect current access.',reporting_binding_context_unavailable:'The current resource mapping or authorization is unavailable.',reporting_binding_context_changed:'The current resource configuration has changed.',observed_reporting_grant_missing:'Observed Search Console reporting permission is missing.',resource_access_verification_pending:'Selected resource access still needs provider verification.',reporting_binding_stopped:'Reporting is paused or revoked.'}
const metric=value=>value===null||value===undefined?'Unknown':String(value)
export default function WebsitePageSeoObservationsPanel({organizationId,engagementId,projectId,pageId,architectureVersionId,pageTitle,actorId,signal,onClose,onNavigationBusyChange}){
 const [manualBlocked,setManualBlocked]=useState(false)
 const scope={organizationId,engagementId,projectId,pageId,architectureVersionId},[category,setCategory]=useState('page_audits'),[query,setQuery]=useState(''),[startDate,setStart]=useState(''),[endDate,setEnd]=useState(''),[bindingId,setBinding]=useState(''),[bindings,setBindings]=useState(null),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),alive=useRef(true),flight=useRef(false),current=useRef(null)
 current.current={category,query,startDate,endDate,bindingId,signal,busy};const active=()=>alive.current&&!current.current.signal?.aborted;const locked=()=>!active()||flight.current||current.current.busy
 useEffect(()=>()=>{alive.current=false},[])
 function change(setter,key,value){if(locked())return;current.current[key]=value;setter(value);setData(null);setError('')}
 async function load(kind='observations',offset=0){
  if(locked())return;flight.current=true;current.current.busy=true;setBusy(true);setError('');const c=current.current
  try{const result=kind==='bindings'?await api.bindings({organizationId,projectId,query:'',offset,limit:25},{signal}):await api.list({...scope,category:c.category,query:c.query,startDate:c.startDate||null,endDate:c.endDate||null,reportingBindingId:c.bindingId||null,offset,limit:25},{signal});if(active()){if(kind==='bindings')setBindings(result);else setData(result)}}catch(cause){if(active()){if(kind!=='bindings')setData(null);setError(cause.message)}}finally{flight.current=false;if(active()){current.current.busy=false;setBusy(false)}}
 }
 const c=data?.context
 return <section aria-label="Website page SEO observations" className="rounded-xl border border-[var(--anka-line)] bg-[var(--anka-surface)] p-4 text-[var(--anka-ink)] space-y-4"><header className="flex items-start justify-between gap-3"><div><h4 className="font-semibold">SEO observations · {pageTitle}</h4><p className="mt-1 text-xs text-[var(--anka-muted)]">Read existing project-linked evidence. Loading this view does not fetch provider reports or change page state.</p></div><button type="button" className="workspace-button" disabled={manualBlocked} onClick={()=>{if(!manualBlocked&&active())onClose()}}>Close SEO observations</button></header>
  {error&&<p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}{busy&&<p role="status" className="text-xs">Checking exact page, source and current project resource scope…</p>}
  <fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2"><label className="text-xs">SEO evidence category<select aria-label="SEO evidence category" className={INPUT} value={category} onChange={event=>{change(setCategory,'category',event.target.value);if(event.target.value==='planned_targets'){change(setStart,'startDate','');change(setEnd,'endDate','')}}}>{Object.entries(LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="text-xs">Find stored evidence<input aria-label="SEO evidence search" className={INPUT} maxLength={120} value={query} onChange={event=>change(setQuery,'query',event.target.value)}/></label>{category!=='planned_targets'&&<><label className="text-xs">Collection start date<input aria-label="SEO collection start date" type="date" className={INPUT} value={startDate} onChange={event=>change(setStart,'startDate',event.target.value)}/></label><label className="text-xs">Collection end date<input aria-label="SEO collection end date" type="date" className={INPUT} value={endDate} onChange={event=>change(setEnd,'endDate',event.target.value)}/></label></>}<p className="text-xs text-[var(--anka-muted)] sm:col-span-2">Date filters select stored collection records, up to 93 days. They do not establish the original provider reporting period.</p><button type="button" className="workspace-button" onClick={()=>load('bindings')}>Find existing GSC bindings</button><label className="text-xs">Exact project GSC binding<select aria-label="SEO project GSC binding" className={INPUT} value={bindingId} onChange={event=>change(setBinding,'bindingId',event.target.value)}><option value="">No binding selected · current provider access unknown</option>{bindingId&&!bindings?.items.some(row=>row.binding.id===bindingId)&&<option value={bindingId}>Selected exact binding · {bindingId}</option>}{bindings?.items.filter(row=>row.binding.resource_kind==='gsc_site'&&row.binding.engagement_id===engagementId).map(row=><option key={row.binding.id} value={row.binding.id}>{row.binding.resource_key} · {row.state} · {row.binding.department_id}</option>)}</select></label>{bindings&&<div className="sm:col-span-2 flex flex-wrap gap-2 text-xs"><span>{bindings.total} project bindings; this page selects same-engagement GSC resources.</span>{bindings.offset>0&&<button type="button" className="workspace-button" onClick={()=>load('bindings',Math.max(0,bindings.offset-25))}>Previous SEO bindings</button>}{bindings.has_more&&<button type="button" className="workspace-button" onClick={()=>load('bindings',bindings.offset+25)}>Next SEO bindings</button>}</div>}<button type="button" className="workspace-button workspace-button-primary" onClick={()=>load()}>Load stored SEO evidence</button></fieldset>
  {c&&<section aria-label="SEO page recheck state" className="rounded-lg border border-[var(--anka-warning)] p-3 text-sm space-y-2"><h5 className="font-semibold">Recheck required</h5><p className="break-all">Original path /{c.initial_path} · implementation revision {c.implementation?.revision_number??'unrecorded'} · {c.tracked_page?.page_url||'Tracked page unlinked'}</p><ul className="list-disc pl-5 space-y-1">{[...new Set([...c.recheck_reasons,c.reporting_reason])].filter(Boolean).map(reason=><li key={reason}>{REASONS[reason]||'Current evidence needs scope review.'}</li>)}</ul><p className="text-xs text-[var(--anka-muted)]">Stored evidence retains its original source, collection time and owner. A newer page version does not renew a legacy check. Provider-backed recheck acceptance remains pending.</p></section>}
  {data&&<section aria-label="Stored SEO records" className="space-y-3"><h5 className="font-semibold">{LABELS[data.category]}</h5>{data.items.map(row=><article key={row.id} className="rounded-lg border border-[var(--anka-line)] p-3 text-sm space-y-2">{data.category==='planned_targets'?<><p className="font-medium">{row.keyword}</p><p>Planned target: {row.target_rank_tier?.replaceAll('_',' ')||'Unset'} · {row.active?'active':'inactive'}</p><p className="text-xs text-[var(--anka-muted)]">Exact approved strategy version is unknown in this legacy link. This target is separate from observed queries.</p></>:data.category==='query_observations'?<><p className="font-medium">Query metadata: {row.query}</p><p>Collection date {row.snapshot_date} · retrieved {row.fetched_at}</p><p>Position: {metric(row.position)} · clicks: {metric(row.search_console_clicks)} · impressions: {metric(row.search_console_impressions)}</p><p className="text-xs text-[var(--anka-warning)]">Provider values are withheld because the historical resource is unknown. Provider period, timezone, device, country and data-through remain unknown.</p></>:<><p className="font-medium">{row.source_type==='manual'?'Manual page evidence':'Legacy provider page metadata'} · {row.audit_date}</p><p>Indexed: {metric(row.indexed)} · schema valid: {metric(row.schema_valid)}</p><p>Mobile score: {metric(row.core_web_vitals_mobile)} · desktop score: {metric(row.core_web_vitals_desktop)}</p>{row.issues===null?<p className="text-xs text-[var(--anka-warning)]">Provider findings withheld; exact historical resource is unknown.</p>:row.issues.length?<ul className="list-disc pl-5">{row.issues.map((issue,index)=><li key={index}>{issue}</li>)}</ul>:<p>No findings recorded in this evidence.</p>}{row.notes&&<p className="whitespace-pre-wrap break-words">{row.notes}</p>}<p className="text-xs text-[var(--anka-muted)]">Collected {row.created_at} · exact page/version check binding unknown.</p></>}</article>)}{data.items.length===0&&<p className="text-sm text-[var(--anka-muted)]">No stored records match this view. Missing measurements are unknown.</p>}<div className="flex flex-wrap gap-2 text-xs"><span>{data.items.length?`${data.offset+1}–${data.offset+data.items.length}`:'0'} of {data.matching} matches · {data.total} total</span>{data.offset>0&&<button type="button" className="workspace-button" disabled={busy} onClick={()=>load('observations',Math.max(0,data.offset-25))}>Previous SEO evidence</button>}{data.has_more&&<button type="button" className="workspace-button" disabled={busy} onClick={()=>load('observations',data.offset+25)}>Next SEO evidence</button>}</div></section>}
  <_WebsitePageVersionChecksPanel organizationId={organizationId} projectId={projectId} engagementId={engagementId} pageId={pageId} architectureVersionId={architectureVersionId} actorId={actorId} signal={signal} onNavigationBusyChange={value=>{setManualBlocked(value);onNavigationBusyChange?.(value)}}/>
 </section>
}
