import {useEffect,useRef,useState} from 'react'
import {projectWebsiteSiteFindings as api} from '../data/projectWebsiteSiteFindings.js'
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const number=value=>value===null||value===undefined?'Unknown':String(value)
export default function WebsiteSiteFindingsPanel({organizationId,projectId,engagementId,architectureVersionId,signal,disabled,onOpenPage}){
 const [query,setQuery]=useState(''),[severity,setSeverity]=useState(''),[category,setCategory]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),alive=useRef(true),flight=useRef(false),latest=useRef(null)
 latest.current={query,severity,category,data,signal,disabled,busy};const active=()=>alive.current&&!latest.current.signal?.aborted,locked=()=>!active()||flight.current||latest.current.busy||latest.current.disabled
 useEffect(()=>()=>{alive.current=false},[])
 function change(setter,key,v){if(locked())return;latest.current[key]=v;latest.current.data=null;setter(v);setData(null);setError('')}
 async function load(offset=0){if(locked())return;flight.current=true;latest.current.busy=true;setBusy(true);setError('');const c=latest.current
 try{const result=await api.list({organizationId,projectId,engagementId,architectureVersionId,query:c.query,severity:c.severity||null,category:c.category||null,offset,limit:25},{signal});if(active()){latest.current.data=result;setData(result)}}catch(cause){if(active()){latest.current.data=null;setData(null);setError(cause.message)}}finally{flight.current=false;if(active()){latest.current.busy=false;setBusy(false)}}}
 function open(row){if(locked()||!latest.current.data?.items.includes(row))return;onOpenPage(row,architectureVersionId)}
 return <section aria-label="Website site findings" className="rounded-xl border border-[var(--anka-line)] bg-[var(--anka-surface)] p-4 space-y-3 text-sm"><h4 className="font-semibold">Site findings · manual page evidence</h4><p className="text-xs text-[var(--anka-muted)]">Inspect findings from the latest saved manual check for each registered page in this architecture. Original checks stay in page history. Loading makes no provider request.</p>{error&&<p role="alert" className="text-[var(--anka-danger)]">{error}</p>}
 <fieldset disabled={busy||disabled} className="grid gap-3 sm:grid-cols-3"><label className="text-xs">Find page or finding<input aria-label="Site finding search" className={INPUT} maxLength={120} value={query} onChange={e=>change(setQuery,'query',e.target.value)}/></label><label className="text-xs">Severity<select aria-label="Site finding severity" className={INPUT} value={severity} onChange={e=>change(setSeverity,'severity',e.target.value)}><option value="">All severities</option>{['info','warning','critical'].map(v=><option key={v}>{v}</option>)}</select></label><label className="text-xs">Category<select aria-label="Site finding category" className={INPUT} value={category} onChange={e=>change(setCategory,'category',e.target.value)}><option value="">All categories</option>{['indexing','schema','performance','content','technical'].map(v=><option key={v}>{v}</option>)}</select></label><button className="workspace-button" type="button" onClick={()=>load()}>Load site findings</button></fieldset>
 {busy&&<p role="status" className="text-xs">Checking bounded findings and current page source state…</p>}
 {data&&<><dl className="grid grid-cols-2 gap-2 sm:grid-cols-4 text-xs">{[['Planned pages',data.source_total_pages],['Registered pages',data.registered_pages],['Pages with manual checks',data.pages_with_manual_checks],['Registered pages without checks',data.registered_pages_without_manual_checks]].map(([name,v])=><div key={name} className="rounded-lg bg-[var(--anka-surface-raised)] p-3"><dt>{name}</dt><dd className="mt-1 text-lg font-semibold">{number(v)}</dd></div>)}</dl><p className="text-xs text-[var(--anka-muted)]">These are coverage counts. A saved manual check does not establish automated, provider or human acceptance.</p>{data.source_state!=='available'&&<p className="text-xs text-[var(--anka-warning)]">The selected current source is unavailable or archived. Retained manual findings remain visible; the current planned-page total is unknown.</p>}
 {data.items.map(row=><article key={`${row.check_id}:${row.finding_number}`} className="rounded-lg border border-[var(--anka-line)] p-3 space-y-2"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><h5 className="font-semibold break-words">{row.page_title}</h5><p className="break-all text-xs text-[var(--anka-muted)]">Original /{row.initial_path}{row.planned_path?` · planned /${row.planned_path}`:''}</p></div><button className="workspace-button" type="button" disabled={busy||disabled} onClick={()=>open(row)}>Open page evidence</button></div><p className="break-words">{row.finding.severity} · {row.finding.category}: {row.finding.description}</p><p className="whitespace-pre-wrap break-words">{row.finding.evidence||'No separate finding evidence recorded.'}</p><p className={`text-xs ${row.recheck_required?'text-[var(--anka-warning)]':'text-[var(--anka-muted)]'}`}>{row.recheck_required?'Recheck required after page, source or observation-link changes.':'Current manual evidence; provider verification remains separate.'}</p><p className="text-xs text-[var(--anka-muted)]">Observed {row.checked_at} · recorded {row.created_at}</p><details className="text-xs text-[var(--anka-muted)]"><summary>Original owner and source receipt</summary><p className="break-all">Owner {row.created_by} · exact check {row.check_id} · source {row.original_architecture_version_id} · approval {row.original_approval_id}</p></details></article>)}{!data.items.length&&<p>No manual findings match this view. Missing provider measurements remain unknown.</p>}
 <div className="flex flex-wrap gap-2 text-xs"><span>{data.items.length?`${data.offset+1}–${data.offset+data.items.length}`:'0'} of {data.matching} findings · {data.total} total</span>{data.offset>0&&<button className="workspace-button" type="button" disabled={busy||disabled} onClick={()=>load(Math.max(0,data.offset-25))}>Previous site findings</button>}{data.has_more&&<button className="workspace-button" type="button" disabled={busy||disabled} onClick={()=>load(data.offset+25)}>Next site findings</button>}</div></>}
 </section>
}
