import {useEffect,useRef,useState} from 'react'
import {projectWebsiteVersionChecks as api} from '../data/projectWebsiteVersionChecks.js'
import {serializeWebsiteManualCheck} from '../data/projectWebsiteVersionChecksRepository.js'
const INPUT='w-full min-w-0 rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i
const empty=()=>({checkedAt:'',indexed:'',schema_valid:'',mobile_score:'',desktop_score:'',notes:'',evidence_url:'',findings:[]})
const value=v=>v===null||v===undefined?'Unknown':typeof v==='boolean'?v?'Yes':'No':String(v)
const REASONS={architecture_version_changed:'Architecture version changed.',implementation_changed:'Implementation changed.',seo_link_changed:'SEO observation link changed.',tracked_page_changed:'Tracked URL or page metadata changed.',approved_source_changed:'Approved source changed.',observation_predates_current_state:'The observation predates the current page state.',approved_source_unavailable:'Approved source is currently unavailable.',page_absent_from_version:'Page is absent from this version.',archived:'Archived project; retained evidence only.',scope_changed:'Current page scope changed.'}
export default function WebsitePageVersionChecksPanel({organizationId,projectId,engagementId,pageId,architectureVersionId,actorId,signal,onNavigationBusyChange}){
 const scope={organizationId,projectId,engagementId,pageId,architectureVersionId},key=`anka:website-check-operation:${actorId}:${organizationId}:${projectId}:${pageId}:${architectureVersionId}:v1`
 const [draft,setDraft]=useState(empty),[review,setReview]=useState(null),[history,setHistory]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[pending,setPending]=useState(()=>{try{const p=JSON.parse(sessionStorage.getItem(key)||'null');return p&&UUID.test(p.requestId||'')?{requestId:p.requestId}:p?{requestId:''}:null}catch{return {requestId:''}}})
 const alive=useRef(true),flight=useRef(false),latest=useRef(null),notify=useRef(onNavigationBusyChange);notify.current=onNavigationBusyChange
 latest.current={draft,review,busy,pending,signal,query};const active=()=>alive.current&&!latest.current.signal?.aborted,locked=()=>!active()||flight.current||latest.current.busy||Boolean(latest.current.pending),dirty=JSON.stringify(draft)!==JSON.stringify(empty()),blocked=busy||Boolean(pending)||dirty||Boolean(review)
 useEffect(()=>{notify.current?.(blocked)},[blocked]);useEffect(()=>()=>{alive.current=false;notify.current?.(false)},[])
 function working(v){latest.current.busy=v;setBusy(v)}
 function change(name,v){if(locked())return;const next={...latest.current.draft,[name]:v};latest.current.draft=next;latest.current.review=null;setDraft(next);setReview(null);setError('');setNotice('')}
 function evidence(d){return serializeWebsiteManualCheck({indexed:d.indexed===''?null:d.indexed==='true',schema_valid:d.schema_valid===''?null:d.schema_valid==='true',mobile_score:d.mobile_score===''?null:Number(d.mobile_score),desktop_score:d.desktop_score===''?null:Number(d.desktop_score),notes:d.notes,evidence_url:d.evidence_url||null,findings:d.findings})}
 async function preview(){if(locked())return;flight.current=true;working(true);setError('');latest.current.review=null;setReview(null);const d=latest.current.draft,signature=JSON.stringify(d)
 try{if(!d.checkedAt)throw Error('Choose the original observation date and time.');const checkedAt=new Date(d.checkedAt).toISOString(),input=evidence(d),result=await api.preview({...scope,checkedAt,evidence:input},{signal});if(active()&&JSON.stringify(latest.current.draft)===signature){const r={signature,checkedAt,evidence:input,result};latest.current.review=r;setReview(r)}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())working(false)}}
 async function confirm(){const r=latest.current.review;if(locked()||!r||r!==review||r.signature!==JSON.stringify(latest.current.draft))return;flight.current=true;working(true);setError('');const operation={requestId:crypto.randomUUID()}
 try{sessionStorage.setItem(key,JSON.stringify(operation));latest.current.pending=operation;setPending(operation);await api.confirm({...scope,checkedAt:r.checkedAt,evidence:r.evidence,reviewSha256:r.result.review_sha256,requestId:operation.requestId,confirmed:true},{signal});if(active()){sessionStorage.removeItem(key);latest.current.pending=null;latest.current.review=null;latest.current.draft=empty();setPending(null);setReview(null);setDraft(empty());setNotice('Manual check saved with its original evidence and exact page version.');setHistory(null)}}catch(cause){if(active()){if(cause.knownRollback){sessionStorage.removeItem(key);latest.current.pending=null;latest.current.review=null;setPending(null);setReview(null)}setError(cause.message)}}finally{flight.current=false;if(active())working(false)}}
 async function recover(){if(!active()||flight.current||!UUID.test(latest.current.pending?.requestId||''))return;flight.current=true;working(true);setError('');try{const result=await api.recover({...scope,requestId:latest.current.pending.requestId},{signal});if(active()){if(!result){setError('The original check is not yet visible. Keep its saved key and check again.');return}sessionStorage.removeItem(key);latest.current.pending=null;latest.current.review=null;latest.current.draft=empty();setPending(null);setReview(null);setDraft(empty());setHistory(null);setNotice('Recovered the original manual check. No repeated write.')}}catch(cause){if(active())setError(cause.message)}finally{flight.current=false;if(active())working(false)}}
 async function load(offset=0){if(!active()||flight.current||latest.current.busy)return;flight.current=true;working(true);setError('');try{const result=await api.list({...scope,query:latest.current.query,offset,limit:25},{signal});if(active())setHistory(result)}catch(cause){if(active()){setHistory(null);setError(cause.message)}}finally{flight.current=false;if(active())working(false)}}
 function discard(){if(locked())return;latest.current.draft=empty();latest.current.review=null;setDraft(empty());setReview(null);setError('');setNotice('')}
 return <section aria-label="Version-bound manual page checks" className="rounded-xl border border-[var(--anka-line)] p-4 space-y-3 text-sm"><h5 className="font-semibold">Manual check · exact page version</h5><p className="text-xs text-[var(--anka-muted)]">Record evidence you inspected. This does not run an automated SEO check or certify provider access. Save or discard your draft before leaving this page.</p>
 {error&&<p role="alert" className="text-[var(--anka-danger)]">{error}</p>}{notice&&<p role="status">{notice}</p>}{pending&&<div role="status" className="rounded-lg border border-[var(--anka-warning)] p-3"><p>The original check outcome is unresolved. New commands stay blocked.</p><button className="workspace-button" type="button" disabled={busy||!UUID.test(pending.requestId||'')} onClick={recover}>Check original manual operation</button></div>}
 <fieldset disabled={busy||Boolean(pending)} className="grid gap-3 sm:grid-cols-2"><label className="text-xs">Original observation date and time<input aria-label="Manual check observation time" type="datetime-local" className={INPUT} value={draft.checkedAt} onChange={e=>change('checkedAt',e.target.value)}/><span className="text-[var(--anka-muted)]">Local timezone: {Intl.DateTimeFormat().resolvedOptions().timeZone}</span></label>{[['indexed','Indexed'],['schema_valid','Schema valid']].map(([k,label])=><label key={k} className="text-xs">{label}<select className={INPUT} aria-label={`Manual check ${label}`} value={draft[k]} onChange={e=>change(k,e.target.value)}><option value="">Unknown / not inspected</option><option value="true">Yes</option><option value="false">No</option></select></label>)}{[['mobile_score','Mobile score'],['desktop_score','Desktop score']].map(([k,label])=><label key={k} className="text-xs">{label}<input className={INPUT} aria-label={`Manual check ${label}`} type="number" min="0" max="100" value={draft[k]} onChange={e=>change(k,e.target.value)} placeholder="Unknown"/></label>)}<label className="text-xs">Evidence URL<input aria-label="Manual check evidence URL" className={INPUT} maxLength={2048} value={draft.evidence_url} onChange={e=>change('evidence_url',e.target.value)}/></label><label className="text-xs sm:col-span-2">Evidence notes<textarea aria-label="Manual check evidence notes" className={INPUT} maxLength={4000} value={draft.notes} onChange={e=>change('notes',e.target.value)}/></label>
 {draft.findings.map((f,index)=><div key={index} className="sm:col-span-2 grid gap-2 sm:grid-cols-2 rounded-lg border border-[var(--anka-line)] p-3"><label className="text-xs">Finding category<select aria-label={`Manual finding ${index+1} category`} className={INPUT} value={f.category} onChange={e=>change('findings',latest.current.draft.findings.map((row,i)=>i===index?{...row,category:e.target.value}:row))}>{['indexing','schema','performance','content','technical'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs">Severity<select aria-label={`Manual finding ${index+1} severity`} className={INPUT} value={f.severity} onChange={e=>change('findings',latest.current.draft.findings.map((row,i)=>i===index?{...row,severity:e.target.value}:row))}>{['info','warning','critical'].map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs sm:col-span-2">Finding description<input aria-label={`Manual finding ${index+1} description`} className={INPUT} maxLength={1000} value={f.description} onChange={e=>change('findings',latest.current.draft.findings.map((row,i)=>i===index?{...row,description:e.target.value}:row))}/></label><label className="text-xs sm:col-span-2">Finding evidence<textarea aria-label={`Manual finding ${index+1} evidence`} className={INPUT} maxLength={2000} value={f.evidence} onChange={e=>change('findings',latest.current.draft.findings.map((row,i)=>i===index?{...row,evidence:e.target.value}:row))}/></label><button className="workspace-button" type="button" onClick={()=>change('findings',latest.current.draft.findings.filter((_,i)=>i!==index))}>Remove finding {index+1}</button></div>)}
 <button className="workspace-button" type="button" disabled={draft.findings.length>=25} onClick={()=>change('findings',[...latest.current.draft.findings,{category:'technical',severity:'warning',description:'',evidence:''}])}>Add manual finding</button><button className="workspace-button" type="button" onClick={preview}>Review manual check</button><button className="workspace-button" type="button" onClick={discard}>Discard manual draft</button></fieldset>
 {review&&<section aria-label="Exact manual check review" className="rounded-lg border border-[var(--anka-violet)] p-3 space-y-2"><h6 className="font-semibold">Review manual evidence</h6><p>Original /{review.result.scope_snapshot.initial_path} · approved architecture v{review.result.scope_snapshot.reference.version_number} · implementation revision {review.result.scope_snapshot.implementation?.revision_number??'unrecorded'}</p><p className="break-all">Recorded URL: {review.result.scope_snapshot.implementation?.recorded_live_url||'Unknown'} · tracked page: {review.result.scope_snapshot.tracked_page?.page_url||'Unlinked'}</p><p className="break-words">Observed {review.checkedAt} · indexed {value(review.evidence.indexed)} · schema valid {value(review.evidence.schema_valid)} · mobile {value(review.evidence.mobile_score)} · desktop {value(review.evidence.desktop_score)}</p><p className="whitespace-pre-wrap break-words">{review.evidence.notes}</p>{review.evidence.evidence_url&&<p className="break-all">Evidence URL: {review.evidence.evidence_url}</p>}{review.evidence.findings.map((f,i)=><p key={i} className="break-words">{f.severity} · {f.category}: {f.description} · {f.evidence}</p>)}<p className="text-xs text-[var(--anka-muted)]">Confirmation retains the exact source, page state and manual evidence. A later change requires recheck; this is not automated or human approval.</p><button className="workspace-button workspace-button-primary" type="button" disabled={busy||Boolean(pending)} onClick={confirm}>Confirm manual check</button></section>}
 <div className="flex flex-wrap gap-2"><label className="min-w-0 w-full sm:flex-1 text-xs">Find manual check history<input aria-label="Manual check history search" className={INPUT} maxLength={120} disabled={busy} value={query} onChange={e=>{if(!active()||flight.current)return;latest.current.query=e.target.value;setQuery(e.target.value);setHistory(null)}}/></label><button className="workspace-button w-full sm:w-auto" type="button" disabled={busy} onClick={()=>load()}>Load manual check history</button></div>
 {history&&<section aria-label="Manual page check history" className="space-y-2">{history.items.map(row=><article key={row.check.id} className="rounded-lg border border-[var(--anka-line)] p-3 space-y-2"><p className="font-semibold">{row.recheck_required?'Recheck required':'Current manual evidence'} · observed {row.check.checked_at}</p><p>Indexed {value(row.check.evidence.indexed)} · schema valid {value(row.check.evidence.schema_valid)} · mobile {value(row.check.evidence.mobile_score)} · desktop {value(row.check.evidence.desktop_score)}</p><p className="whitespace-pre-wrap break-words">{row.check.evidence.notes}</p>{row.check.evidence.evidence_url&&<p className="break-all">Evidence URL: {row.check.evidence.evidence_url}</p>}{row.check.evidence.findings.map((f,i)=><p key={i} className="break-words">{f.severity} · {f.category}: {f.description} · {f.evidence}</p>)}{row.recheck_reasons.map(reason=><p key={reason} className="text-xs text-[var(--anka-warning)]">{REASONS[reason]||'Current evidence needs scope review.'}</p>)}<details className="text-xs text-[var(--anka-muted)]"><summary>Original owner and source receipt</summary><p className="break-all">Owner {row.check.created_by} · recorded {row.check.created_at} · exact source {row.check.architecture_version_id} · approval {row.check.architecture_approval_id}</p></details></article>)}{!history.items.length&&<p>No manual checks match this view.</p>}<div className="flex flex-wrap gap-2 text-xs"><span>{history.items.length?`${history.offset+1}–${history.offset+history.items.length}`:'0'} of {history.matching} manual checks · {history.total} total</span>{history.offset>0&&<button className="workspace-button" type="button" disabled={busy} onClick={()=>load(Math.max(0,history.offset-25))}>Previous manual checks</button>}{history.has_more&&<button className="workspace-button" type="button" disabled={busy} onClick={()=>load(history.offset+25)}>Next manual checks</button>}</div></section>}
 </section>
}
