import {useRef,useState} from 'react'
import {serializeWebsitePageOperations,WEBSITE_PUBLICATION_STATES} from '../data/projectWebsitePageContracts.js'
const INPUT='w-full rounded-lg border border-[var(--anka-line)] bg-[var(--anka-surface)] px-3 py-2 text-sm text-[var(--anka-ink)]'
const fields=['planned_url','recorded_live_url','redirect_url','publication_state','template','work_item_id','implementation_notes','qa_evidence']
const labels={planned_url:'Planned URL',recorded_live_url:'Recorded live URL',redirect_url:'Redirect destination',publication_state:'Publication state',template:'Template',work_item_id:'Content work',implementation_notes:'Implementation notes',qa_evidence:'QA evidence',cta:'Call to action',conversion_action:'Conversion action',source_artifact_version_ids:'Exact source versions',source_version_ids:'Exact source versions',keyword_strategy_version_id:'Keyword strategy version'}
const label=key=>labels[key] || key.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase())
function display(value){if(value===null || value===undefined)return <span className="text-[var(--anka-muted)]">Not set</span>;if(Array.isArray(value))return <ol className="space-y-2">{value.map((item,i)=><li key={i} className="border-l border-[var(--anka-line)] pl-3">{display(item)}</li>)}</ol>;if(typeof value==='object')return <dl className="space-y-2">{Object.entries(value).map(([key,item])=><div key={key}><dt className="font-medium text-[var(--anka-muted)]">{label(key)}</dt><dd className="whitespace-pre-wrap break-all">{display(item)}</dd></div>)}</dl>;return String(value)}
const initial=context=>Object.fromEntries(fields.map(key=>[key,context.operations?.[key] ?? (key==='publication_state' ? 'planned' : key==='implementation_notes' || key==='qa_evidence' ? '' : null)]))
export default function WebsitePageEditor({context,disabled,isActive,onConfirm,onLookup,onClose}){
 const [draft,setDraft]=useState(()=>initial(context)),[target,setTarget]=useState(context.seo_link?.tracked_page_id || ''),[mode,setMode]=useState('operations'),[review,setReview]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState('')
 const latest=useRef(null);latest.current={context,draft,target,mode,review,disabled,query}
 const signature=()=>JSON.stringify([latest.current.mode,latest.current.draft,latest.current.target])
 const opsDirty=JSON.stringify(draft)!==JSON.stringify(initial(context)),seoDirty=target!==(context.seo_link?.tracked_page_id || '')
 const active=()=>isActive(context) && !latest.current.disabled
 function change(key,value){if(!active())return;setReview(null);setError('');setDraft(current=>({...current,[key]:value}))}
 function preview(){if(!active())return;try{const current=latest.current,operations=current.mode==='operations' ? serializeWebsitePageOperations(current.draft) : null;setError('');setReview({kind:current.mode==='operations' ? 'saveOperations' : 'linkSeo',context,signature:signature(),operations,trackedPageId:current.target || null})}catch(cause){setReview(null);setError(cause.message)}}
 function confirm(){if(!active() || !review || latest.current.review!==review || latest.current.context!==review.context || signature()!==review.signature)return;setReview(null);return onConfirm(review)}
 const work=context.work_candidates.items.find(row=>row.id===draft.work_item_id),seo=context.seo_candidates.items.find(row=>row.id===target)
 const reviewed=review && review.context===context && review.signature===signature()
 return <section aria-label="Website page editor" className="space-y-3 rounded-xl border border-[var(--anka-violet)] bg-[var(--anka-surface)] p-4">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-semibold">Edit page · {context.source_page.title}</h4><p className="break-all text-xs text-[var(--anka-muted)]">/{context.planned_path} · original /{context.page.initial_path} · {context.page.page_key}</p></div><button type="button" className="workspace-button" disabled={disabled} onClick={()=>{if(active())onClose()}}>Close page editor</button></div>
  <details><summary className="cursor-pointer text-xs">Approved structure · exact v{context.reference.version_number}</summary><p className="break-all text-xs">Version {context.reference.artifact_version_id} · approval {context.reference.approval_id}</p><div aria-label="Exact approved page structure" className="mt-2 max-h-64 overflow-auto rounded-lg bg-[var(--anka-surface-raised)] p-3 text-xs">{display(context.source_page)}</div></details>
  {error && <p role="alert" className="text-sm text-[var(--anka-danger)]">{error}</p>}
  <fieldset disabled={disabled} className="space-y-3">
   <label className="block text-xs">Change to review<select aria-label="Website edit category" className={INPUT} value={mode} onChange={event=>{if(!active() || (event.target.value==='seo' ? JSON.stringify(latest.current.draft)!==JSON.stringify(initial(latest.current.context)) : latest.current.target!==(latest.current.context.seo_link?.tracked_page_id || '')))return;setMode(event.target.value);setReview(null)}}><option value="operations" disabled={seoDirty}>Page implementation</option><option value="seo" disabled={opsDirty}>SEO observation link</option></select></label>
   {(opsDirty || seoDirty) && <p className="text-xs text-[var(--anka-muted)]">Save this change or close the editor before switching categories.</p>}
   <details><summary className="cursor-pointer text-xs">Find existing Content work or SEO observations</summary><div className="mt-2 flex flex-wrap gap-2"><label className="min-w-0 flex-1 text-xs">Search<input aria-label="Website editor lookup search" className={INPUT} maxLength={120} value={query} onChange={event=>{if(active())setQuery(event.target.value)}} /></label><button type="button" className="workspace-button self-end" onClick={()=>{if(active()){setReview(null);onLookup({query:latest.current.query,workOffset:0,seoOffset:0})}}}>Find eligible records</button></div></details>
   {mode==='operations' ? <>
    <div className="grid gap-3 sm:grid-cols-2">{[['planned_url','Planned URL'],['recorded_live_url','Recorded live URL'],['redirect_url','Redirect destination URL'],['template','Implementation template']].map(([key,label])=><label key={key} className="text-xs">{label}<input aria-label={label} className={INPUT} maxLength={key==='template' ? 160 : 2048} value={draft[key] || ''} onChange={event=>change(key,event.target.value || null)} /></label>)}
     <label className="text-xs">Manually recorded publication state<select aria-label="Website page publication state" className={INPUT} value={draft.publication_state} onChange={event=>change('publication_state',event.target.value)}>{WEBSITE_PUBLICATION_STATES.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label>
     <label className="text-xs">Existing canonical Content work<select aria-label="Website canonical Work Item" className={INPUT} value={draft.work_item_id || ''} onChange={event=>change('work_item_id',event.target.value || null)}><option value="">Unlinked</option>{draft.work_item_id && !work && <option value={draft.work_item_id}>Selected work · {draft.work_item_id} · outside current results or unavailable</option>}{context.work_candidates.items.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></label>
    </div>
    <p className="break-all text-xs text-[var(--anka-muted)]">{work ? `Canonical owner: ${work.assignee_id || 'unassigned'} · deadline: ${work.due_date || 'unset'}` : 'Owner and deadline come from the linked canonical Work Item. Find its current record to inspect them.'}</p>
    {context.work_candidates.has_more && <button type="button" className="workspace-button" onClick={()=>{if(active()){setReview(null);onLookup({query:latest.current.query,workOffset:context.work_candidates.offset+25,seoOffset:context.seo_candidates.offset})}}}>More Content work</button>}
    {context.work_candidates.offset>0 && <button type="button" className="workspace-button" onClick={()=>{if(active()){setReview(null);onLookup({query:latest.current.query,workOffset:Math.max(0,context.work_candidates.offset-25),seoOffset:context.seo_candidates.offset})}}}>Previous Content work</button>}
    {['implementation_notes','qa_evidence'].map(key=><label key={key} className="block text-xs">{key==='implementation_notes' ? 'Implementation notes' : 'QA evidence'}<textarea aria-label={key==='implementation_notes' ? 'Implementation notes' : 'QA evidence'} className={INPUT} rows={3} maxLength={4000} value={draft[key]} onChange={event=>change(key,event.target.value)} /></label>)}
    <p className="text-xs text-[var(--anka-muted)]">This records implementation and URLs. Publishing and assignments remain separate actions.</p>
   </> : <>
    <label className="block text-xs">Explicit SEO observation page<select aria-label="Website SEO observation page" className={INPUT} value={target} onChange={event=>{if(active()){setTarget(event.target.value);setReview(null)}}}><option value="">Unlink current observation</option>{target && !seo && <option value={target}>Selected observation · {target} · outside current results</option>}{context.seo_candidates.items.map(row=><option key={row.id} value={row.id}>{row.page_url} · {row.page_type}</option>)}</select></label>
    <p className="break-all text-xs text-[var(--anka-muted)]">Current link: {context.seo_link?.tracked_page_id || 'unlinked'}. This links existing same-brand observations; it fetches no analytics or provider data.</p>
    {context.seo_candidates.has_more && <button type="button" className="workspace-button" onClick={()=>{if(active()){setReview(null);onLookup({query:latest.current.query,workOffset:context.work_candidates.offset,seoOffset:context.seo_candidates.offset+25})}}}>More SEO observations</button>}
    {context.seo_candidates.offset>0 && <button type="button" className="workspace-button" onClick={()=>{if(active()){setReview(null);onLookup({query:latest.current.query,workOffset:context.work_candidates.offset,seoOffset:Math.max(0,context.seo_candidates.offset-25)})}}}>Previous SEO observations</button>}
   </>}
   <button type="button" className="workspace-button" onClick={preview}>Review page change</button>
  </fieldset>
  {reviewed && <section aria-label="Review Website page change" className="space-y-2 rounded-lg bg-[var(--anka-surface-raised)] p-3 text-xs"><h5 className="font-semibold">Review exact {mode==='operations' ? 'implementation' : 'SEO link'} change</h5><p className="break-all">Page {context.page.page_key} · source v{context.reference.version_number} · current {mode==='operations' ? 'revision '+context.expected_revision : 'link event '+context.expected_link_number}</p><div className="max-h-64 overflow-auto">{display(review.operations ? {...review.operations,work_item_id:work?.title || review.operations.work_item_id} : {seo_observation:review.trackedPageId ? seo?.page_url || review.trackedPageId : 'Unlink current observation'})}</div><p>Current authority, approved source and revision are rechecked at confirmation. This review makes no changes.</p><button type="button" className="workspace-button workspace-button-primary" disabled={disabled} onClick={confirm}>Confirm page change</button></section>}
 </section>
}
