"""Authorized isolated AD2 placement reporting binding QA; no users/provider/production calls."""
import argparse,hashlib,json,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);p.add_argument('--install-empty-candidate',action='store_true');a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf-8',capture_output=True,timeout=100)
 if r.returncode:raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip();assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data',identity
names=['project_campaign_placement_revisions','project_campaign_placement_commands','project_campaign_placements']
functions=['public.list_project_campaign_planning_contexts(uuid,uuid,uuid,uuid,text,integer,integer,integer,integer)','public.list_project_campaign_source_candidates(uuid,uuid,uuid,text,text,integer,integer)','public.list_project_campaign_contribution_candidates(uuid,uuid,uuid,text,text,integer,integer)','private.campaign_lookup_scope(uuid,uuid,uuid,text,integer,integer)']
state="select json_build_object('functions',(select json_agg(json_build_object('name',n.nspname||'.'||p.proname,'body',md5(pg_get_functiondef(p.oid)),'acl',p.proacl::text,'definer',p.prosecdef,'searchPath',p.proconfig) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('campaign_lookup_scope','list_project_campaign_planning_contexts','list_project_campaign_source_candidates','list_project_campaign_contribution_candidates')),'history',json_build_array((select count(*) from auth.users),(select count(*) from public.artifact_versions),(select count(*) from public.artifact_approvals),(select count(*) from public.work_items),(select count(*) from public.tasks),(select count(*) from public.marketing_campaigns),(select count(*) from public.marketing_campaign_plan_versions)),'authority',(select md5(jsonb_agg(to_jsonb(m) order by id)::text) from public.organization_memberships m),'services',(select md5(jsonb_agg(to_jsonb(s) order by id)::text) from public.engagement_services s),'projects',(select md5(jsonb_agg(to_jsonb(p) order by id)::text) from public.projects p),'placementAudit',json_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from public."+n+" t)" for n in names)+"));"
migration=repo/'supabase/migrations/20261001018000_project_campaign_planning_lookups.sql';source=migration.read_text(encoding='utf-8');body=re.sub(r'(?im)^begin;\s*','',source,count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
drop=''.join('drop function '+f+';' for f in functions)
if a.install_empty_candidate:
 assert run("select count(*) from pg_proc where proname in ('campaign_lookup_scope','list_project_campaign_planning_contexts','list_project_campaign_source_candidates','list_project_campaign_contribution_candidates');").stdout.strip()=='0','Only install previously absent read-only candidate functions'
 run(source);print('Read-only campaign selectors installed in identity-checked isolated clone',flush=True)
prior=json.loads(run(state).stdout)
replay=json.loads(run('begin;'+drop+body+state+'rollback;').stdout.strip());assert replay==prior,'Final source/ACL catalog replay differs';assert json.loads(run(state).stdout)==prior;print('Complete selector function/security replay PASS',flush=True)
behavior=run((repo/'supabase/tests/project_campaign_planning_lookups.behavior.sql').read_text(encoding='utf-8'));count=behavior.stderr.count('PASS ');print(behavior.stderr,flush=True);assert count>=24,count;assert json.loads(run(state).stdout)==prior,'Selectors leaked canonical history, authority or users';print('Selector rollback behavior PASS',count,flush=True)
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf-8'));n=e.setdefault('campaignPlacements',{}).setdefault('planningLookups',{});n.update({'migration':migration.name,'migrationSha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'completeMigrationReplay':True,'catalogSecurityMatches':True,'behaviorPassCount':count,'historyAndAuthorityRestored':True,'scope':'Bounded existing exact campaign/plan/services/source/Tasks/Work Items metadata; no provider/Storage calls or new fixtures','remaining':'Actual shared-source/variant/placement/calendar UI and production release remain pending.'});packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
