"""Authorized isolated AD2 source registry QA; no users/provider/production calls."""
import argparse,hashlib,json,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);p.add_argument('--install-empty-candidate',action='store_true');a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf-8',capture_output=True,timeout=100)
 if r.returncode:raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip();assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data',identity
names=['project_campaign_asset_variants','project_campaign_asset_links','project_campaign_asset_commands','project_campaign_assets']
functions=['public.list_project_campaign_assets(uuid,uuid,uuid,uuid,uuid,uuid,text,integer,integer)','public.preview_project_campaign_asset(uuid,uuid,jsonb)','public.confirm_project_campaign_asset(uuid,uuid,jsonb,text,uuid)','public.get_project_campaign_asset_operation(uuid,uuid,uuid)','private.campaign_asset_preview(uuid,uuid,jsonb)','private.campaign_asset_source(uuid,uuid,uuid,text,uuid)','private.campaign_asset_context(uuid,uuid,uuid,uuid,uuid)','private.campaign_asset_write_authorized(uuid,uuid)']
quoted=','.join("'"+n+"'" for n in names)
state="""select json_build_object('functions',(select json_agg(json_build_object('name',n.nspname||'.'||p.proname,'body',md5(pg_get_functiondef(p.oid)),'acl',p.proacl::text) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('list_project_campaign_assets','preview_project_campaign_asset','confirm_project_campaign_asset','get_project_campaign_asset_operation','campaign_asset_preview','campaign_asset_source','campaign_asset_context','campaign_asset_write_authorized')),'columns',(select json_agg(json_build_object('table',table_name,'name',column_name,'type',udt_name,'nullable',is_nullable,'default',column_default) order by table_name,ordinal_position) from information_schema.columns where table_schema='public' and table_name in (TABLES)),'constraints',(select json_agg(json_build_object('table',r.relname,'name',c.conname,'definition',pg_get_constraintdef(c.oid)) order by r.relname,c.conname) from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname in (TABLES)),'indexes',(select json_agg(json_build_object('table',tablename,'name',indexname,'definition',indexdef) order by tablename,indexname) from pg_indexes where schemaname='public' and tablename in (TABLES)),'policies',(select json_agg(p order by tablename,policyname) from pg_policies p where schemaname='public' and tablename in (TABLES)),'tableSecurity',(select json_agg(json_build_object('table',r.relname,'rls',r.relrowsecurity,'acl',r.relacl::text) order by r.relname) from pg_class r join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname in (TABLES)),'history',json_build_array((select count(*) from public.artifact_versions),(select count(*) from public.artifact_approvals),(select count(*) from public.work_items),(select count(*) from public.marketing_campaigns),(select count(*) from public.marketing_campaign_plan_versions),(select count(*) from public.auth_users_placeholder)));""".replace('TABLES',quoted).replace('(select count(*) from public.auth_users_placeholder)','(select count(*) from auth.users)')
# Compare current authority records and all retained candidate receipts as well.
state=state.replace("'history',json_build_array", "'organization',(select settings from public.organizations where id='99999999-9999-4999-8999-999999999901'),'authority',(select json_agg(m order by id) from public.organization_memberships m where organization_id='99999999-9999-4999-8999-999999999901'),'projectArchive',(select archived_at from public.projects where id='99999999-9999-4999-8999-999999999974'),'candidateRows',json_build_array("+','.join('(select count(*) from public.'+n+')' for n in names)+"),'history',json_build_array")
state=state.replace("'candidateRows',","'candidateAudit',json_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from public."+n+" t)" for n in names)+"),'candidateRows',")
state=state.replace("'candidateRows',","'legacyActivityDefault',(select column_default from information_schema.columns where table_schema='public' and table_name='activity_events' and column_name='organization_id'),'governedHistory',json_build_array((select count(*) from public.files),(select count(*) from public.deliverables),(select count(*) from public.deliverable_versions),(select count(*) from public.deliverable_pm_confirmations),(select count(*) from public.deliverable_lifecycle_events),(select count(*) from public.approvals)),'candidateRows',")
migration=repo/'supabase/migrations/20261001015000_project_campaign_asset_registry.sql';source=migration.read_text(encoding='utf-8');body=re.sub(r'(?im)^begin;\s*','',source,count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
drop=''.join('drop function '+f+';' for f in functions)+''.join('drop table public.'+n+';' for n in names)
if a.install_empty_candidate:
 counts=run('select '+','.join('(select count(*) from public.'+n+')' for n in names)+';').stdout.strip();assert counts=='0|0|0|0','Never rebuild retained candidate history: '+counts
 run('begin;'+drop+body+'commit;');print('AD2 complete final candidate installed over verified empty owned candidate only',flush=True)
prior=json.loads(run(state).stdout)
replay=json.loads(run('begin;'+drop+body+state+'rollback;').stdout.strip());assert {k:v for k,v in replay.items() if k not in ('candidateRows','candidateAudit')}=={k:v for k,v in prior.items() if k not in ('candidateRows','candidateAudit')},'Complete final native source/catalog/grants differ';assert json.loads(run(state).stdout)==prior;print('AD2 complete migration source/catalog/security replay PASS',flush=True)
behavior=run((repo/'supabase/tests/project_campaign_assets.behavior.sql').read_text(encoding='utf-8'));count=behavior.stderr.count('PASS ');print(behavior.stderr,flush=True);assert count>=24,count;assert json.loads(run(state).stdout)==prior,'Native behavior leaked canonical history, authority or users';print('AD2 rollback behavior PASS',count,flush=True)
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf-8'));n=e.setdefault('campaignPlacements',{}).setdefault('nativeAssets',{});n.update({'migration':migration.name,'migrationSha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'completeMigrationReplay':True,'catalogSecurityMatches':True,'behaviorPassCount':count,'historyAndAuthorityRestored':True,'scope':'Local exact canonical source/variant registration and UUID receipts; existing synthetic actor and approval fixtures only, not human acceptance','remaining':'Bounded registry reads, native placements/resource linkage, actual UI and installed production release remain pending.'});packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
