"""Identity-checked, rollback-only native refresh authority QA; no users or live calls."""
import argparse, hashlib, json, re, subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf8',capture_output=True,timeout=120)
 if r.returncode: raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip()
assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data',identity
names=['reporting_refresh_adapters','reporting_refresh_policies','reporting_verification_challenges','reporting_resource_verifications','reporting_refresh_jobs','reporting_refresh_requests','reporting_refresh_attempts','reporting_refresh_results','reporting_refresh_pages']
assert run("select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relname in ("+','.join("'"+x+"'" for x in names)+");").stdout.strip()=='0','Candidate must be absent; never overwrite retained candidate state'
related=['project_reporting_bindings','project_reporting_binding_revisions','project_reporting_binding_commands','integration_connections','integration_connection_engagements','integration_oauth_credentials','projects','engagements','organization_memberships','project_reporting_observations','project_reporting_sync_events']
snapshot="select jsonb_build_object('users',(select count(*) from auth.users),'rows',jsonb_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from public."+x+' t)' for x in related)+"));"
prior=run(snapshot).stdout
migration=repo/'supabase/migrations/20261002000000_reporting_refresh_authority.sql';source=migration.read_text(encoding='utf8')
body=re.sub(r'(?im)^begin;\s*','',source,count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
queue_migration=repo/'supabase/migrations/20261002001000_reporting_refresh_queue.sql'
queue_source=queue_migration.read_text(encoding='utf8');queue_body=re.sub(r'(?im)^begin;\s*','',queue_source,count=1);queue_body=re.sub(r'(?im)^commit;\s*$','',queue_body)
body+=queue_body
ingestion_migration=repo/'supabase/migrations/20261002002000_reporting_refresh_ingestion.sql';ingestion_source=ingestion_migration.read_text(encoding='utf8');ingestion_body=re.sub(r'(?im)^begin;\s*','',ingestion_source,count=1);ingestion_body=re.sub(r'(?im)^commit;\s*$','',ingestion_body);body+=ingestion_body
cadence_migration=repo/'supabase/migrations/20261002003000_reporting_refresh_cadence.sql';cadence_source=cadence_migration.read_text(encoding='utf8');cadence_body=re.sub(r'(?im)^begin;\s*','',cadence_source,count=1);cadence_body=re.sub(r'(?im)^commit;\s*$','',cadence_body);body+=cadence_body
behavior=(repo/'supabase/tests/reporting_refresh_authority.behavior.sql').read_text(encoding='utf8');behavior=re.sub(r'(?im)^begin;\s*','',behavior,count=1)
result=run('begin;'+body+behavior);print(result.stderr,flush=True);count=result.stderr.count('PASS ');assert count>=30,count
assert run(snapshot).stdout==prior,'Rollback leaked history, authority, credentials or users'
# Capture the complete installed candidate definitions/security in the same rollback envelope.
catalog="select jsonb_build_object('functions',(select jsonb_agg(jsonb_build_object('name',n.nspname||'.'||p.proname,'definition',md5(replace(pg_get_functiondef(p.oid),chr(13),'')),'acl',p.proacl::text,'definer',p.prosecdef,'config',p.proconfig) order by p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('valid_reporting_refresh_limits','reporting_refresh_admin','reporting_refresh_binding','configure_project_reporting_refresh','begin_project_reporting_verification','record_project_reporting_verification','get_project_reporting_refresh_configuration','reporting_refresh_ready','reporting_refresh_job_receipt','enqueue_reporting_refresh','request_project_reporting_refresh','get_project_reporting_refresh_operation','claim_project_reporting_refresh','fail_project_reporting_refresh','commit_project_reporting_refresh_page','get_project_reporting_refresh_claim','schedule_project_reporting_refresh','list_due_project_reporting_refreshes')),'tables',(select jsonb_agg(jsonb_build_object('name',c.relname,'rls',c.relrowsecurity,'acl',c.relacl::text,'constraints',(select string_agg(pg_get_constraintdef(x.oid),'|' order by x.conname) from pg_constraint x where x.conrelid=c.oid),'indexes',(select string_agg(pg_get_indexdef(i.indexrelid),'|' order by i.indexrelid::regclass::text) from pg_index i where i.indrelid=c.oid)) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relname in ("+','.join("'"+x+"'" for x in names)+")));"
cat=json.loads(run('begin;'+body+catalog+'rollback;').stdout);assert len(cat['functions'])==18 and len(cat['tables'])==9;assert all(t['rls'] for t in cat['tables']);assert run(snapshot).stdout==prior
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf8'));e.setdefault('storedReporting',{})['nativeRefreshAuthority']={'migration':migration.name,'sha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'queueMigration':queue_migration.name,'queueSha256':hashlib.sha256(queue_migration.read_bytes()).hexdigest(),'ingestionMigration':ingestion_migration.name,'ingestionSha256':hashlib.sha256(ingestion_migration.read_bytes()).hexdigest(),'cadenceMigration':cadence_migration.name,'cadenceSha256':hashlib.sha256(cadence_migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'behaviorPassCount':count,'catalog':cat,'allChangesRolledBack':True,'noUsersOrProviders':True,'status':'Local native policy/verification boundary tested; candidate not installed or deployed. Registry empty; no dispatch authority. Atomic native queue/claim/backoff tested; Atomic ingestion/cursor/original-response recovery tested; Bounded native cadence and provider-free RPC worker implemented; observed concurrent races, runnable worker endpoint/schedule wiring, read/UI integration, real adapters and activation still pending.'};packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf8',newline='\n');print('Native refresh authority PASS',count,'catalog18 functions/9 closed RLS tables; rollback restored',flush=True)
