"""Rollback-only actual adapter page/native ingestion checks, exact existing isolated clone."""
import argparse,hashlib,json,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf8',capture_output=True,timeout=90)
 if r.returncode:raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip();assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data'
manifest=json.loads((repo/'supabase/functions/_shared/reportingGoogleManifests.json').read_text(encoding='utf8'))
for name,digest in manifest['implementationFiles'].items():assert hashlib.sha256((repo/name).read_text(encoding='utf8').replace('\r\n','\n').encode()).hexdigest()==digest,name
migration=repo/'supabase/migrations/20261002006000_reporting_google_adapter_registry.sql';body=re.sub(r'(?im)^begin;\s*','',migration.read_text(encoding='utf8'),count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
# Synthetic original-provider responses only. No fetch/global network path is used.
js="""import {readFileSync} from 'node:fs';import {createGoogleReportingAdapters} from './supabase/functions/_shared/reportingGoogleAdapters.js';
const manifest=JSON.parse(readFileSync('./supabase/functions/_shared/reportingGoogleManifests.json','utf8'));const id='99999999-9999-4999-8999-999999999901',out=[];
for(let index=0;index<2;index++){
 const entry=manifest.adapters[index],zone=index?'America/Los_Angeles':'UTC',day=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const context={organization_id:id,project_id:id,binding_id:id,connection_id:id,binding_revision_number:1,context_checksum:'a'.repeat(64),provider:entry.provider,resource_kind:entry.resourceKind,resource_key:index?'sc-domain:example.com':'123456'};
 const identity={organization_id:id,project_id:id,binding_id:id,binding_revision_number:1,context_checksum:context.context_checksum,provider:entry.provider,resource_kind:entry.resourceKind,resource_key:context.resource_key,source_contract:entry.sourceContract,period_start:day,period_end:day,reporting_time_zone:zone};
 const response=index?{responseAggregationType:'byPage',rows:[{keys:[day,'https://example.com/a','native-fixture'],clicks:0,impressions:5,ctr:0,position:null}]}:{dimensionHeaders:[{name:'date'},{name:'pageLocation'}],metricHeaders:['screenPageViews','sessions','totalUsers'].map(name=>({name,type:'TYPE_INTEGER'})),rowCount:1,metadata:{timeZone:'UTC'},rows:[{dimensionValues:[{value:day.replaceAll('-','')},{value:'https://example.com/a'}],metricValues:[{value:'0'},{value:'2'},{}]}]};
 const adapters=createGoogleReportingAdapters({getToken:async()=> 'local-fixture-only',manifests:Object.fromEntries(manifest.adapters.map(x=>[x.sourceContract,x.manifestSha256])),fetcher:async()=>new Response(JSON.stringify(response))});
 out.push(await adapters[index].fetchPage({identity,context,limits:{max_observations:12},cursor:null,signal:new AbortController().signal}));
}console.log(JSON.stringify(out));"""
pages=json.loads(subprocess.check_output(['wsl','-d','Ubuntu-24.04','-u','soban','--cd','/home/soban/code/anka-os-ui-recovery','--','/home/soban/.local/bin/node','--input-type=module','-e',js],text=True,encoding='utf8'))
base=(repo/'supabase/tests/reporting_verified_reads.behavior.sql').read_text(encoding='utf8');base=base[:base.index("select pg_temp.check_true(public.get_project_stored_reporting_status")];base=re.sub(r'(?im)^begin;\s*','',base,count=1)
setup=base[:base.index('insert into public.integration_connections')];fixture=base[base.index('insert into public.integration_connections'):]
def lit(value):return "'"+str(value).replace("'","''")+"'"
checks=[]
for index,entry in enumerate(manifest['adapters']):
 f=fixture.replace('B6 synthetic local reporting','B6 rollback Google module').replace('local-adapter-only',entry['sourceContract']).replace('"lease_seconds":1','"lease_seconds":60').replace('"max_observations":25','"max_observations":12')
 if index:f=f.replace('999999997610','999999997620').replace('999999997611','999999997621').replace('google_analytics','google_search_console').replace('ga4_property','gsc_site').replace('https://www.googleapis.com/auth/analytics.readonly','https://www.googleapis.com/auth/webmasters.readonly').replace('"property_id":"123456"','"site_url":"sc-domain:example.com"').replace('"resource_key":"123456"','"resource_key":"sc-domain:example.com"').replace("'reporting_time_zone','UTC'","'reporting_time_zone','America/Los_Angeles'")
 checks.append(f+"select set_config('anka.challenge',gen_random_uuid()::text,true);select set_config('anka.claim',gen_random_uuid()::text,true);\n")
 begin="select public.begin_project_reporting_verification('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,current_setting('anka.challenge')::uuid)"
 checks.append('select pg_temp.expect_error('+lit(begin)+",'55000','Disabled reviewed adapter cannot dispatch');\n")
 checks.append('update private.reporting_refresh_adapters set enabled=true where source_contract='+lit(entry['sourceContract'])+';'+begin+';')
 checks.append("select set_config('request.jwt.claim.role','service_role',true);set local role service_role;select pg_temp.check_true(public.claim_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid)->>'dispatch_authorized'='true','Enabled clone-only manifest receives one native verification claim');")
 checks.append("select public.complete_project_reporting_verification(current_setting('anka.challenge')::uuid,current_setting('anka.claim')::uuid,"+lit(entry['manifestSha256'])+",clock_timestamp(),true,true,repeat('b',64));reset role;")
 checks.append("select set_config('anka.job',(public.request_project_reporting_refresh('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid,current_setting('anka.refreshpolicy')::uuid,"+lit(pages[index]['period_start'])+'::date,'+lit(pages[index]['period_end'])+"::date,gen_random_uuid())->>'job_id'),true);select set_config('anka.pageclaim',gen_random_uuid()::text,true);set local role service_role;select public.claim_project_reporting_refresh(current_setting('anka.job')::uuid,current_setting('anka.pageclaim')::uuid);")
 # The static synthetic normalized response predates this SQL claim; only its transport
 # retrieval timestamp is adapted to this transaction. Provider values/semantics remain exact.
 page=lit(json.dumps(pages[index],separators=(',',':')))+"::jsonb||jsonb_build_object('retrieved_at',to_char(clock_timestamp() at time zone 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))"
 checks.append("select set_config('anka.originalpage',("+page+")::text,true);select pg_temp.check_true(public.commit_project_reporting_refresh_page(current_setting('anka.job')::uuid,current_setting('anka.pageclaim')::uuid,current_setting('anka.originalpage')::jsonb)->>'inserted'="+lit(len(pages[index]['observations']))+",'Actual normalized adapter metrics ingest atomically');")
 checks.append("select pg_temp.check_true(public.commit_project_reporting_refresh_page(current_setting('anka.job')::uuid,current_setting('anka.pageclaim')::uuid,current_setting('anka.originalpage')::jsonb)->>'replayed'='true','Exact original adapter page recovery adds no observations');reset role;select set_config('request.jwt.claim.role','authenticated',true);")
 checks.append("select pg_temp.check_true((select count(*)="+str(len(pages[index]['observations']))+" from public.project_reporting_observations where binding_id=current_setting('anka.b6binding')::uuid),'Exact native normalized observation count');")
 checks.append("select pg_temp.check_true((select count(*)>0 from public.project_reporting_observations where binding_id=current_setting('anka.b6binding')::uuid and metric_value=0 and value_state='available'),'Original zero preserved natively');select pg_temp.check_true((select count(*)=1 from public.project_reporting_observations where binding_id=current_setting('anka.b6binding')::uuid and metric_value is null and value_state='unknown'),'Original missing metric remains unknown natively');")
 checks.append("select pg_temp.check_true((select bool_and(data_through is null and completeness="+lit('partial' if index else 'unknown')+") from public.project_reporting_observations where binding_id=current_setting('anka.b6binding')::uuid),'Source coverage and unknown data-through preserved');")
 checks.append("select pg_temp.check_true(public.get_project_stored_reporting_status('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid)->>'current_authorized'='true','Native proof permits current exact Google resource read');")
 checks.append("update private.reporting_refresh_adapters set enabled=false where source_contract="+lit(entry['sourceContract'])+";select pg_temp.check_true(public.get_project_stored_reporting_status('99999999-9999-4999-8999-999999999901','99999999-9999-4999-8999-999999999974',current_setting('anka.b6binding')::uuid)->>'current_authorized'='false','Disabling reviewed adapter immediately withholds current values');")
tables=['public.project_reporting_observations','public.project_reporting_sync_events','public.project_reporting_bindings','public.project_reporting_binding_revisions','public.project_reporting_binding_commands','public.integration_connections','public.integration_connection_engagements','public.integration_oauth_credentials','public.organization_memberships','private.reporting_refresh_policies','private.reporting_refresh_adapters','private.reporting_verification_challenges','private.reporting_verification_attempts','private.reporting_resource_verifications','private.reporting_refresh_jobs','private.reporting_refresh_requests','private.reporting_refresh_attempts','private.reporting_refresh_results','private.reporting_refresh_pages']
snapshot="select jsonb_build_object('users',(select count(*) from auth.users),'rows',jsonb_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from "+x+' t)' for x in tables)+"));"
prior=run(snapshot).stdout
r=run('begin;'+body+setup+'\n'.join(checks)+'rollback;');print(r.stderr);count=r.stderr.count('PASS ');assert count==20,count;assert run(snapshot).stdout==prior,'Google adapter native tests changed original audit/authority/users'
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf8'));e['storedReporting']['googleAdapters']={'migration':migration.name,'migrationSha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'nativePassCount':count,'manifest':manifest,'originalAuditAuthorityUsersRestored':True,'scope':'Synthetic normalized GA4/GSC pages into real native one-use verification/ingestion/reader. Only retrieval timestamp adapted to the rollback claim; no real provider call.','status':'Locally tested compiled adapters, disabled registry migration; no production install or resource activation.'};packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf8',newline='\n');print('Google adapter native PASS',count,'original audit/authority/users restored')
