"""Identity checked B6 closed stored reporting QA. No users, production writes or providers."""
import argparse,hashlib,json,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);p.add_argument('--install-empty-candidate',action='store_true');a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf-8',capture_output=True,timeout=100)
 if r.returncode:raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip();assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data',identity
names=['project_reporting_observations','project_reporting_sync_events'];functions=['public.list_project_stored_reporting_observations(uuid,uuid,uuid,date,date,text,integer,integer)','public.get_project_stored_reporting_status(uuid,uuid,uuid)','private.stored_reporting_context(uuid,uuid,uuid)','private.validate_stored_reporting_observation()']
related=names+['project_reporting_bindings','project_reporting_binding_revisions','project_reporting_binding_commands','integration_connections','integration_connection_engagements','integration_oauth_credentials','meta_connections','projects','engagements','organization_memberships','activity_events']
state="select json_build_object('functions',(select json_agg(json_build_object('name',n.nspname||'.'||p.proname,'body',md5(replace(pg_get_functiondef(p.oid),chr(13),'')),'acl',p.proacl::text,'definer',p.prosecdef,'searchPath',p.proconfig) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('list_project_stored_reporting_observations','get_project_stored_reporting_status','stored_reporting_context','validate_stored_reporting_observation')),'tables',(select json_agg(json_build_object('name',c.relname,'rls',c.relrowsecurity,'acl',c.relacl::text,'constraints',(select string_agg(pg_get_constraintdef(x.oid),'|' order by x.conname) from pg_constraint x where x.conrelid=c.oid),'indexes',(select string_agg(pg_get_indexdef(i.indexrelid),'|' order by i.indexrelid::regclass::text) from pg_index i where i.indrelid=c.oid)) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('project_reporting_observations','project_reporting_sync_events')),'users',(select count(*) from auth.users),'rows',json_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from public."+n+" t)" for n in related)+"));"
migration=repo/'supabase/migrations/20261001028000_project_stored_reporting.sql';source=migration.read_text(encoding='utf-8');body=re.sub(r'(?im)^begin;\s*','',source,count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
if a.install_empty_candidate:
 assert run("select count(*) from pg_class where relname in ('project_reporting_observations','project_reporting_sync_events');").stdout.strip()=='0','Only install absent candidate tables'
 run(source);print('Closed stored reporting installed in exact isolated clone',flush=True)
prior=json.loads(run(state).stdout)
copy=''.join('create temp table saved_'+n+' as table public.'+n+';' for n in names)
drop=''.join('drop function '+f+';' for f in functions[:-1])+''.join('drop table public.'+n+';' for n in names)+'drop function '+functions[-1]+';'
restore=''.join('insert into public.'+n+' select * from saved_'+n+';' for n in names)
replay=json.loads(run('begin;'+copy+drop+body+restore+state+'rollback;').stdout.strip());assert replay==prior,'Complete stored reporting source/ACL catalog replay differs';assert json.loads(run(state).stdout)==prior;print('Complete stored reporting migration/security replay PASS',flush=True)
behavior=run((repo/'supabase/tests/project_stored_reporting.behavior.sql').read_text(encoding='utf-8'));count=behavior.stderr.count('PASS ');print(behavior.stderr,flush=True);assert count>=20,count;assert json.loads(run(state).stdout)==prior,'Stored reporting leaked history, current authority, credentials or users';print('Stored reporting rollback behavior PASS',count,flush=True)
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf-8'));n=e.setdefault('storedReporting',{});n.update({'migration':migration.name,'migrationSha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'completeMigrationReplay':True,'catalogSecurityMatches':True,'behaviorPassCount':count,'historyAndAuthorityRestored':True,'scope':'Closed immutable exact-resource stored observations and sync history. No ingestion grant, adapter or provider calls; all native metric values/dimensions withheld pending current resource access verification. Cadence/history/manual refresh remain null and disabled.','remaining':'Actual report UI, provider resource verification/cadence integration and wider B2-B7 production/human acceptance pending.'});packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8')
