"""Identity-checked canonical campaign deliverable planning QA; no production/provider/users."""
import argparse,hashlib,json,re,subprocess
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--psql',required=True);p.add_argument('--repo',required=True);p.add_argument('--evidence',required=True);p.add_argument('--install-empty-candidate',action='store_true');a=p.parse_args();repo=Path(a.repo)
cmd=[a.psql,'-X','-w','-h','127.0.0.1','-p','55462','-U','postgres','-d','anka_b1_firstsend_20260930','-qAt','-v','ON_ERROR_STOP=1']
def run(sql):
 r=subprocess.run(cmd,input=sql,text=True,encoding='utf-8',capture_output=True,timeout=100)
 if r.returncode:raise RuntimeError(r.stderr)
 return r
identity=run("select current_database()||'|'||current_user||'|'||current_setting('data_directory');").stdout.strip();assert identity=='anka_b1_firstsend_20260930|postgres|G:/AnkaSphereN1LocalChecks/anka-schema-4453dd840a1a4131820f3d529a5378b9/data',identity
new=['project_campaign_deliverable_plan_commands','project_campaign_deliverable_plans'];names=['workstreams','deliverables','deliverable_versions','deliverable_action_requests','deliverable_lifecycle_events','deliverable_review_assignments','deliverable_pm_confirmations','activity_events','notifications','living_project_documents','marketing_campaigns','marketing_campaign_plan_versions','engagement_services','service_catalog','tasks','work_items']+new
funcs=['public.confirm_project_campaign_deliverable_plan(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,jsonb,text,uuid)','public.preview_project_campaign_deliverable_plan(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,jsonb)','public.get_project_campaign_deliverable_plan_operation(uuid,uuid,uuid)','private.campaign_deliverable_plan_review(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,jsonb)','private.campaign_deliverable_plan_input(jsonb)'];fnames=['confirm_project_campaign_deliverable_plan','preview_project_campaign_deliverable_plan','get_project_campaign_deliverable_plan_operation','campaign_deliverable_plan_review','campaign_deliverable_plan_input']

literal=lambda v:"'"+v+"'"
state="select json_build_object('functions',(select json_agg(json_build_object('name',n.nspname||'.'||p.proname,'body',md5(pg_get_functiondef(p.oid)),'acl',p.proacl::text,'definer',p.prosecdef,'searchPath',p.proconfig) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ("+','.join(map(literal,fnames))+")),'tables',(select json_agg(json_build_object('name',c.relname,'acl',c.relacl::text,'rls',c.relrowsecurity,'constraints',(select json_agg(pg_get_constraintdef(k.oid) order by k.conname) from pg_constraint k where k.conrelid=c.oid),'indexes',(select json_agg(pg_get_indexdef(i.indexrelid) order by i.indexrelid::regclass::text) from pg_index i where i.indrelid=c.oid),'triggers',(select json_agg(pg_get_triggerdef(t.oid) order by t.tgname) from pg_trigger t where t.tgrelid=c.oid and not t.tgisinternal),'policies',(select json_agg(json_build_object('name',p.polname,'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid))) from pg_policy p where p.polrelid=c.oid)) order by c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ("+','.join(map(literal,new))+")),'activityDefault',(select pg_get_expr(d.adbin,d.adrelid) from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum where d.adrelid='public.activity_events'::regclass and a.attname='organization_id'),'users',(select count(*) from auth.users),'authority',(select md5(jsonb_agg(to_jsonb(m) order by id)::text) from public.organization_memberships m),'projects',(select md5(jsonb_agg(to_jsonb(p) order by id)::text) from public.projects p),'engagements',(select md5(jsonb_agg(to_jsonb(p) order by id)::text) from public.engagements p),'sourceAudit',json_build_array((select md5(jsonb_agg(to_jsonb(v) order by id)::text) from public.artifact_versions v),(select md5(jsonb_agg(to_jsonb(v) order by id)::text) from public.artifact_approvals v)),'pageAudit',json_build_array("+','.join("(select md5(coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text)::text,'[]')) from public."+n+" t)" for n in names)+"));"
migration=repo/'supabase/migrations/20261001026000_project_campaign_deliverable_plans.sql';source=migration.read_text(encoding='utf-8');body=re.sub(r'(?im)^begin;\s*','',source,count=1);body=re.sub(r'(?im)^commit;\s*$','',body)
if a.install_empty_candidate:
 assert run("select count(*) from pg_class where relname in ('project_campaign_deliverable_plan_commands','project_campaign_deliverable_plans');").stdout.strip()=='0','Install absent candidate tables only'
 run(source);print('Campaign-deliverable candidate installed only in verified isolated clone',flush=True)
prior=json.loads(run(state).stdout)
drop=''.join('drop function '+f+';' for f in funcs)+''.join('drop table public.'+n+';' for n in reversed(new))
preserve=''.join('create temporary table replay_'+n+' on commit drop as select * from public.'+n+';' for n in new)
restore=''.join('insert into public.'+n+' select * from replay_'+n+';' for n in new)
assert json.loads(run('begin;'+preserve+drop+body+restore+state+'rollback;').stdout)==prior,'Exact complete source/schema/ACL replay differs'
assert json.loads(run(state).stdout)==prior;print('Complete campaign-deliverable schema/function/security replay PASS',flush=True)
r=run((repo/'supabase/tests/project_campaign_deliverable_plans.behavior.sql').read_text(encoding='utf-8'));print(r.stderr,flush=True);count=r.stderr.count('PASS ');assert count>=25,count
assert json.loads(run(state).stdout)==prior,'Deliverable planning leaked history/authority/users'
packet=Path(a.evidence);e=json.loads(packet.read_text(encoding='utf-8'));v=e.setdefault('campaignPlanning',{}).setdefault('deliverablePlans',{});v.update({'migration':migration.name,'migrationSha256':hashlib.sha256(migration.read_bytes()).hexdigest(),'databaseIdentity':identity,'completeMigrationReplay':True,'catalogSecurityMatches':True,'behaviorPassCount':count,'historyAndAuthorityRestored':True,'scope':'Unchanged canonical deliverable version writer with private exact-version campaign/service/plan/brief/topic/pillar/contributor references and original reviewed receipt. No assignment, approval, provider acceptance or users.','remaining':'Observed concurrency, actual plan UI and integrated production/provider/human acceptance pending.'});packet.write_text(json.dumps(e,indent=2)+'\n',encoding='utf-8');print('Campaign deliverable rollback behavior PASS',count,flush=True)
