-- Bounded site projection of latest immutable manual check per original page/root.
-- Source versions stay explicit; legacy provider findings are not copied or certified.
begin;set local lock_timeout='5s';set local statement_timeout='120s';
do $$begin
 if md5(replace(pg_get_functiondef('private.website_read_authorized(uuid,uuid)'::regprocedure),chr(13),''))<>'339ae8372edf7afa3115655da7a2255f'
 or md5(replace(pg_get_functiondef('private.website_approved_source(uuid,uuid,uuid)'::regprocedure),chr(13),''))<>'8fbd479e8c1a8ab7b665196d1d1987a4'
 or md5(replace(pg_get_functiondef('public.list_project_website_version_checks(uuid,uuid,uuid,uuid,text,integer,integer)'::regprocedure),chr(13),''))<>'4e4a85193b55f8dac4602812c41b7868' then raise exception 'Exact site finding read/source/check prerequisites changed' using errcode='55000';end if;
end $$;
create function public.list_project_website_site_findings(p_organization_id uuid,p_project_id uuid,p_architecture_version_id uuid,p_query text default '',p_severity text default null,p_category text default null,p_offset integer default 0,p_limit integer default 25)
returns jsonb language plpgsql security definer set search_path='' as $$
declare root uuid;engagement uuid;brand uuid;source jsonb;source_state text:='available';source_total integer;registered bigint;checked bigint;total bigint;matching bigint;row record;rows jsonb:='[]';cache jsonb:='{}';status jsonb;current_check jsonb;planned jsonb;j jsonb;begin
 perform private.website_read_authorized(p_organization_id,p_project_id);
 if p_architecture_version_id is null or p_query is null or length(p_query)>120 or p_query~'[[:cntrl:]]' or p_offset is null or p_offset not between 0 and 10000 or p_limit is null or p_limit not between 1 and 50 or (p_severity is not null and p_severity not in ('info','warning','critical')) or (p_category is not null and p_category not in ('indexing','schema','performance','content','technical')) then raise exception 'Choose exact bounded site finding filters' using errcode='22023';end if;
 select a.id,a.engagement_id,a.brand_id into root,engagement,brand from public.artifact_versions v join public.artifacts a on a.id=v.artifact_id and a.organization_id=v.organization_id where v.id=p_architecture_version_id and v.organization_id=p_organization_id and a.project_id=p_project_id and a.artifact_type='website_architecture' for share of v,a;
 if not found then raise exception 'Exact same-project architecture source required' using errcode='42501';end if;
 if exists(select 1 from public.projects where id=p_project_id and organization_id=p_organization_id and archived_at is not null) then source_state:='archived';else
 begin source:=private.website_approved_source(p_organization_id,p_project_id,p_architecture_version_id);source_total:=jsonb_array_length(source->'pages');
 exception when sqlstate '42501' or sqlstate '55000' or sqlstate '22023' then source_state:='approved_source_unavailable';end;end if;
 select count(*) into registered from public.project_website_pages p where p.organization_id=p_organization_id and p.project_id=p_project_id and p.architecture_artifact_id=root and p.engagement_id=engagement and p.brand_id=brand;
 select count(*) into checked from public.project_website_pages p where p.organization_id=p_organization_id and p.project_id=p_project_id and p.architecture_artifact_id=root and p.engagement_id=engagement and p.brand_id=brand and exists(select 1 from public.project_website_version_checks c where c.page_id=p.id and c.organization_id=p_organization_id and c.project_id=p_project_id);
 select coalesce(sum(jsonb_array_length(c.evidence->'findings')),0) into total from public.project_website_pages p join lateral(select evidence from public.project_website_version_checks c where c.page_id=p.id and c.organization_id=p_organization_id and c.project_id=p_project_id order by c.created_at desc,c.id limit 1)c on true where p.organization_id=p_organization_id and p.project_id=p_project_id and p.architecture_artifact_id=root and p.engagement_id=engagement and p.brand_id=brand;
 select count(*) into matching from public.project_website_pages p join lateral(select evidence from public.project_website_version_checks c where c.page_id=p.id and c.organization_id=p_organization_id and c.project_id=p_project_id order by c.created_at desc,c.id limit 1)c on true cross join lateral jsonb_array_elements(c.evidence->'findings') f where p.organization_id=p_organization_id and p.project_id=p_project_id and p.architecture_artifact_id=root and p.engagement_id=engagement and p.brand_id=brand and (p_severity is null or f->>'severity'=p_severity) and (p_category is null or f->>'category'=p_category) and (p_query='' or strpos(lower(p.initial_path||' '||coalesce(f->>'description','')||' '||coalesce(f->>'evidence','')),lower(p_query))>0);
 for row in select p.id page_id,p.page_key,p.initial_path,c.id check_id,c.architecture_version_id,c.architecture_approval_id,c.checked_at,c.created_at,c.created_by,f.value finding,f.ordinality finding_number from public.project_website_pages p join lateral(select * from public.project_website_version_checks c where c.page_id=p.id and c.organization_id=p_organization_id and c.project_id=p_project_id order by c.created_at desc,c.id limit 1)c on true cross join lateral jsonb_array_elements(c.evidence->'findings') with ordinality f(value,ordinality) where p.organization_id=p_organization_id and p.project_id=p_project_id and p.architecture_artifact_id=root and p.engagement_id=engagement and p.brand_id=brand and (p_severity is null or f.value->>'severity'=p_severity) and (p_category is null or f.value->>'category'=p_category) and (p_query='' or strpos(lower(p.initial_path||' '||coalesce(f.value->>'description','')||' '||coalesce(f.value->>'evidence','')),lower(p_query))>0) order by c.checked_at desc,p.page_key,c.id,f.ordinality limit p_limit offset p_offset loop
 if not cache ? row.page_id::text then
 status:=public.list_project_website_version_checks(p_organization_id,p_project_id,row.page_id,p_architecture_version_id,'',0,1);
 current_check:=status#>'{items,0}';
 if current_check#>>'{check,id}' is distinct from row.check_id::text then raise exception 'Exact site finding page check changed; reload bounded view' using errcode='40001';end if;
 cache:=cache||jsonb_build_object(row.page_id::text,jsonb_build_object('recheck_required',current_check->'recheck_required','recheck_reasons',current_check->'recheck_reasons','state',current_check->'state','source_state',status->'source_state'));
 end if;
 status:=cache->row.page_id::text;planned:=null;
 if source is not null then select value into planned from jsonb_array_elements(source->'pages') where value->>'page_key'=row.page_key;end if;
 rows:=rows||jsonb_build_array(jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',engagement,'page_id',row.page_id,'page_key',row.page_key,'initial_path',row.initial_path,'page_title',coalesce(planned->>'title','Original /'||row.initial_path),'planned_path',planned->'path','check_id',row.check_id,'finding_number',row.finding_number,'finding',row.finding,'checked_at',row.checked_at,'created_at',row.created_at,'created_by',row.created_by,'original_architecture_version_id',row.architecture_version_id,'original_approval_id',row.architecture_approval_id,'recheck_required',status->'recheck_required','recheck_reasons',status->'recheck_reasons','state',status->'state','source_state',status->'source_state','source_type','manual','provider_verified',false));
 end loop;
 j:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',engagement,'architecture_version_id',p_architecture_version_id,'source_state',source_state,'source_total_pages',source_total,'registered_pages',registered,'pages_with_manual_checks',checked,'registered_pages_without_manual_checks',registered-checked,'items',rows,'total',total,'matching',matching,'offset',p_offset,'has_more',p_offset+jsonb_array_length(rows)<matching,'projection','latest_manual_check_per_registered_page','provider_request_made',false,'provider_verified',false);
 if octet_length(j::text)>131072 then raise exception 'Site finding response exceeds whole bounds' using errcode='22023';end if;return j;
end $$;
revoke all on function public.list_project_website_site_findings(uuid,uuid,uuid,text,text,text,integer,integer) from public,anon,authenticated,service_role;
grant execute on function public.list_project_website_site_findings(uuid,uuid,uuid,text,text,text,integer,integer) to authenticated;
commit;
