-- Bounded existing owners and exact approved campaign sources; no provider reads.
begin;
set local lock_timeout='5s';set local statement_timeout='120s';
do $$begin if md5(replace(pg_get_functiondef('private.campaign_plan_source(uuid,uuid,uuid,uuid,uuid,text)'::regprocedure),chr(13),'')) is distinct from '63a8f506bfdc5513cfb136cf5e439dea' or md5(replace(pg_get_functiondef('private.campaign_lookup_scope(uuid,uuid,uuid,text,integer,integer)'::regprocedure),chr(13),'')) is distinct from '660b1fd84782306c674b0a7cf5c08b2a' or md5(replace(pg_get_functiondef('private.website_read_authorized(uuid,uuid)'::regprocedure),chr(13),'')) is distinct from '339ae8372edf7afa3115655da7a2255f' or md5(replace(pg_get_functiondef('private.require_pipeline_approved_artifact(uuid,uuid,uuid,text,text)'::regprocedure),chr(13),'')) is distinct from '033f6c233c35b8c2641716b861a63cd2' then raise exception 'Exact plan selector prerequisites changed' using errcode='55000';end if;end $$;
create function public.list_project_campaign_plan_candidates(p_organization_id uuid,p_project_id uuid,p_engagement_id uuid,p_kind text,p_query text default '',p_offset integer default 0,p_limit integer default 25)
returns jsonb language plpgsql security definer set search_path='' as $$declare e public.engagements%rowtype;total bigint;matching bigint;items jsonb:='[]';candidate record;source jsonb;reason text;result jsonb;begin
 e:=private.campaign_lookup_scope(p_organization_id,p_project_id,p_engagement_id,p_query,p_offset,p_limit);
 if p_kind is null or p_kind not in ('owner','message','measurement','strategy') then raise exception 'Exact campaign candidate category required' using errcode='22023';end if;
 if p_kind='owner' then
 select count(*) into total from public.organization_memberships where organization_id=p_organization_id and member_kind='team' and status='active';
 select count(*) into matching from public.organization_memberships m left join public.profiles p on p.id=m.user_id where m.organization_id=p_organization_id and m.member_kind='team' and m.status='active' and (p_query='' or strpos(lower(coalesce(p.full_name,'')||' '||m.user_id::text),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.name,row.id),'[]') into items from(select m.user_id id,coalesce(nullif(p.full_name,''),'Existing Team member') name,m.department_id,m.role from public.organization_memberships m left join public.profiles p on p.id=m.user_id where m.organization_id=p_organization_id and m.member_kind='team' and m.status='active' and (p_query='' or strpos(lower(coalesce(p.full_name,'')||' '||m.user_id::text),lower(p_query))>0) order by name,m.user_id limit p_limit offset p_offset) row;
 else
 select count(*) into total from public.artifact_versions v join public.artifacts a on a.id=v.artifact_id and a.organization_id=v.organization_id where a.organization_id=p_organization_id and a.project_id=p_project_id and a.engagement_id=e.id and a.brand_id=e.brand_id and (p_kind='message' and a.artifact_type in ('campaign_messaging','scripts') or p_kind='measurement' and a.artifact_type='measurement_plan' or p_kind='strategy' and a.artifact_type in ('audience','channel_strategy','keyword_strategy')) and exists(select 1 from public.artifact_approvals ap where ap.artifact_version_id=v.id and ap.organization_id=v.organization_id);
 select count(*) into matching from public.artifact_versions v join public.artifacts a on a.id=v.artifact_id and a.organization_id=v.organization_id where a.organization_id=p_organization_id and a.project_id=p_project_id and a.engagement_id=e.id and a.brand_id=e.brand_id and (p_kind='message' and a.artifact_type in ('campaign_messaging','scripts') or p_kind='measurement' and a.artifact_type='measurement_plan' or p_kind='strategy' and a.artifact_type in ('audience','channel_strategy','keyword_strategy')) and exists(select 1 from public.artifact_approvals ap where ap.artifact_version_id=v.id and ap.organization_id=v.organization_id) and (p_query='' or strpos(lower(a.title),lower(p_query))>0);
 for candidate in select v.id from public.artifact_versions v join public.artifacts a on a.id=v.artifact_id and a.organization_id=v.organization_id where a.organization_id=p_organization_id and a.project_id=p_project_id and a.engagement_id=e.id and a.brand_id=e.brand_id and (p_kind='message' and a.artifact_type in ('campaign_messaging','scripts') or p_kind='measurement' and a.artifact_type='measurement_plan' or p_kind='strategy' and a.artifact_type in ('audience','channel_strategy','keyword_strategy')) and exists(select 1 from public.artifact_approvals ap where ap.artifact_version_id=v.id and ap.organization_id=v.organization_id) and (p_query='' or strpos(lower(a.title),lower(p_query))>0) order by v.created_at desc,v.id limit p_limit offset p_offset loop
 source:=null;reason:=null;begin if e.status not in ('planning','active') then raise exception 'Source engagement unavailable' using errcode='42501';end if;source:=private.campaign_plan_source(p_organization_id,p_project_id,e.id,e.brand_id,candidate.id,p_kind);exception when sqlstate '42501' or sqlstate '55000' or sqlstate '22023' then reason:='approved_source_unavailable';end;
 items:=items||jsonb_build_array(jsonb_build_object('id',candidate.id,'source',source,'available',reason is null,'reason',reason));end loop;
 end if;
 result:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',e.id,'brand_id',e.brand_id,'kind',p_kind,'items',items,'total',total,'matching',matching,'offset',p_offset,'has_more',p_offset+jsonb_array_length(items)<matching);
 if octet_length(result::text)>131072 then raise exception 'Candidate selection exceeds whole response bound' using errcode='22023';end if;return result;
end $$;
revoke all on function public.list_project_campaign_plan_candidates(uuid,uuid,uuid,text,text,integer,integer) from public,anon,authenticated,service_role;
grant execute on function public.list_project_campaign_plan_candidates(uuid,uuid,uuid,text,text,integer,integer) to authenticated;
commit;
