-- Bounded existing canonical deliverable selection and Team-only exact-version planning reads.
begin;
set local lock_timeout='5s';set local statement_timeout='120s';
do $$begin
 if md5(replace(pg_get_functiondef('private.campaign_lookup_scope(uuid,uuid,uuid,text,integer,integer)'::regprocedure),chr(13),'')) is distinct from '660b1fd84782306c674b0a7cf5c08b2a'
 or md5(replace(pg_get_functiondef('public.get_deliverable_version_capabilities(uuid,uuid)'::regprocedure),chr(13),'')) is distinct from '264845291ac71d988d76b1bc8d8473e2'
 or md5(replace(pg_get_functiondef('private.campaign_deliverable_plan_review(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,jsonb)'::regprocedure),chr(13),'')) is distinct from 'dd3a1e2dab05babe762c0a291124d9ba' then raise exception 'Exact deliverable planning read prerequisites changed' using errcode='55000';end if;
end $$;
create unique index campaign_deliverable_receipt_version_idx on public.project_campaign_deliverable_plan_commands(organization_id,project_id,(receipt#>>'{version,id}'));
create function public.list_project_campaign_deliverable_candidates(p_organization_id uuid,p_project_id uuid,p_engagement_id uuid,p_kind text,p_deliverable_id uuid default null,p_query text default '',p_offset integer default 0,p_limit integer default 25)
returns jsonb language plpgsql security definer set search_path='' as $$declare e public.engagements%rowtype;d public.deliverables%rowtype;total bigint;matching bigint;items jsonb;result jsonb;begin
 e:=private.campaign_lookup_scope(p_organization_id,p_project_id,p_engagement_id,p_query,p_offset,p_limit);
 if p_kind is null or p_kind not in ('deliverables','versions') or (p_kind='deliverables' and p_deliverable_id is not null) then raise exception 'Exact deliverable selector category required' using errcode='22023';end if;
 if p_kind='deliverables' then
 select count(*) into total from public.deliverables where organization_id=p_organization_id and project_id=p_project_id;
 select count(*) into matching from public.deliverables where organization_id=p_organization_id and project_id=p_project_id and (p_query='' or case when p_query ~* '^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' then id::text=lower(p_query) else strpos(lower(title),lower(p_query))>0 end);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.title,row.id),'[]') into items from(select candidate.id,candidate.organization_id,candidate.project_id,candidate.workstream_id,candidate.title,candidate.deliverable_type,candidate.status,candidate.owner_id,candidate.due_date,candidate.current_version_id,candidate.archived_at,w.department_id,w.status workstream_status,(candidate.archived_at is null and candidate.status not in ('withdrawn','archived') and w.status in ('planned','active')) available from public.deliverables candidate join public.workstreams w on w.id=candidate.workstream_id and w.organization_id=candidate.organization_id and w.project_id=candidate.project_id where candidate.organization_id=p_organization_id and candidate.project_id=p_project_id and (p_query='' or case when p_query ~* '^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' then candidate.id::text=lower(p_query) else strpos(lower(candidate.title),lower(p_query))>0 end) order by candidate.title,candidate.id limit p_limit offset p_offset) row;
 else
 select * into d from public.deliverables where id=p_deliverable_id and organization_id=p_organization_id and project_id=p_project_id;
 if not found then raise exception 'Exact existing project deliverable required' using errcode='42501';end if;
 select count(*) into total from public.deliverable_versions where organization_id=p_organization_id and project_id=p_project_id and deliverable_id=d.id;
 select count(*) into matching from public.deliverable_versions where organization_id=p_organization_id and project_id=p_project_id and deliverable_id=d.id and (p_query='' or strpos(lower(title),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.version_number desc,row.id),'[]') into items from(select v.id,v.organization_id,v.project_id,v.deliverable_id,v.title,v.version_number,v.review_status,v.state_version,v.created_by,v.created_at,v.withdrawn_at,v.client_approval_required,v.file_id,exists(select 1 from public.project_campaign_deliverable_plans l where l.deliverable_version_id=v.id and l.organization_id=v.organization_id and l.project_id=v.project_id and l.engagement_id=e.id) has_current_engagement_planning from public.deliverable_versions v where v.organization_id=p_organization_id and v.project_id=p_project_id and v.deliverable_id=d.id and (p_query='' or strpos(lower(v.title),lower(p_query))>0) order by v.version_number desc,v.id limit p_limit offset p_offset) row;
 end if;
 result:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',e.id,'brand_id',e.brand_id,'kind',p_kind,'deliverable_id',p_deliverable_id,'items',items,'total',total,'matching',matching,'offset',p_offset,'has_more',p_offset+jsonb_array_length(items)<matching,'provider_request_made',false,'external_write_authorized',false);
 if octet_length(result::text)>131072 then raise exception 'Deliverable selection exceeds whole response bound' using errcode='22023';end if;return result;
end $$;
create function public.get_project_campaign_deliverable_version(p_organization_id uuid,p_project_id uuid,p_engagement_id uuid,p_deliverable_id uuid,p_deliverable_version_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$declare e public.engagements%rowtype;d public.deliverables%rowtype;v public.deliverable_versions%rowtype;w public.workstreams%rowtype;l public.project_campaign_deliverable_plans%rowtype;service_available boolean:=false;archived boolean;original_matches boolean;capabilities jsonb;result jsonb;begin
 e:=private.campaign_lookup_scope(p_organization_id,p_project_id,p_engagement_id,'',0,1);
 select * into d from public.deliverables where id=p_deliverable_id and organization_id=p_organization_id and project_id=p_project_id;
 if not found then raise exception 'Exact project deliverable required' using errcode='42501';end if;
 select * into v from public.deliverable_versions where id=p_deliverable_version_id and organization_id=p_organization_id and project_id=p_project_id and deliverable_id=d.id;
 if not found then raise exception 'Exact selected canonical deliverable version required' using errcode='42501';end if;
 select * into w from public.workstreams where id=d.workstream_id and organization_id=d.organization_id and project_id=d.project_id;
 select * into l from public.project_campaign_deliverable_plans where deliverable_version_id=v.id and organization_id=p_organization_id and project_id=p_project_id and engagement_id=e.id;
 if l.id is not null then
 service_available:=e.status in ('planning','active') and exists(select 1 from public.engagement_services es join public.service_catalog sc on sc.id=es.service_id and sc.organization_id=es.organization_id where es.id=l.marketing_service_id and es.organization_id=p_organization_id and es.engagement_id=e.id and es.status='active' and sc.is_active and sc.department_id='marketing');
 -- Original canonical preview/file payload is separate from internal planning history.
 original_matches:=encode(sha256(convert_to(jsonb_build_object('title',v.title,'file_id',v.file_id,'change_summary',v.change_summary,'preview_metadata',v.preview_metadata)::text,'UTF8')),'hex')=encode(sha256(convert_to((select jsonb_build_object('title',r.receipt#>>'{version,title}','file_id',r.receipt#>'{version,file_id}','change_summary',r.receipt#>>'{version,change_summary}','preview_metadata',r.receipt#>'{version,preview_metadata}') from public.project_campaign_deliverable_plan_commands r where r.organization_id=p_organization_id and r.project_id=p_project_id and r.receipt#>>'{version,id}'=v.id::text limit 1)::text,'UTF8')),'hex');
 end if;
 select archived_at is not null into archived from public.projects where id=p_project_id and organization_id=p_organization_id;
 if not archived then capabilities:=public.get_deliverable_version_capabilities(p_organization_id,v.id);end if;
 result:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',e.id,'brand_id',e.brand_id,'deliverable',jsonb_build_object('id',d.id,'organization_id',d.organization_id,'project_id',d.project_id,'title',d.title,'owner_id',d.owner_id,'due_date',d.due_date,'status',d.status,'current_version_id',d.current_version_id,'archived_at',d.archived_at,'workstream_id',d.workstream_id),'workstream',jsonb_build_object('id',w.id,'organization_id',w.organization_id,'project_id',w.project_id,'department_id',w.department_id,'status',w.status),'version',to_jsonb(v),'planning',case when l.id is null then null else to_jsonb(l) end,'planning_state',case when l.id is not null then 'original_current_engagement' when exists(select 1 from public.project_campaign_deliverable_plans where deliverable_version_id=v.id and organization_id=p_organization_id and project_id=p_project_id) then 'other_engagement' else 'not_recorded' end,'current_service_available',service_available,'project_archived',archived,'original_canonical_content_matches',original_matches,'current_capabilities',capabilities,'capabilities_state',case when archived then 'archived_project' else 'canonical_current' end,'ready_to_publish',false,'external_write_authorized',false,'provider_request_made',false);
 if octet_length(result::text)>131072 then raise exception 'Exact deliverable history exceeds whole response bound' using errcode='22023';end if;return result;
end $$;
revoke all on function public.list_project_campaign_deliverable_candidates(uuid,uuid,uuid,text,uuid,text,integer,integer),public.get_project_campaign_deliverable_version(uuid,uuid,uuid,uuid,uuid) from public,anon,authenticated,service_role;
grant execute on function public.list_project_campaign_deliverable_candidates(uuid,uuid,uuid,text,uuid,text,integer,integer),public.get_project_campaign_deliverable_version(uuid,uuid,uuid,uuid,uuid) to authenticated;
commit;
