-- Bounded existing target/Task selectors and immutable opportunity histories; no providers.
begin;
set local lock_timeout='5s';set local statement_timeout='120s';
do $$begin
 if md5(replace(pg_get_functiondef('private.campaign_lookup_scope(uuid,uuid,uuid,text,integer,integer)'::regprocedure),chr(13),'')) is distinct from '660b1fd84782306c674b0a7cf5c08b2a'
 or md5(replace(pg_get_functiondef('private.marketing_opportunity_review(uuid,uuid,uuid,uuid,jsonb)'::regprocedure),chr(13),'')) is distinct from 'edb3c5ec5f0ff342aba47ffa45b20870'
 or md5(replace(pg_get_functiondef('private.marketing_opportunity_url(text)'::regprocedure),chr(13),'')) is distinct from '6a9036d1b3dc11c2b6e979b946e785e2'
 or md5(replace(pg_get_functiondef('private.website_read_authorized(uuid,uuid)'::regprocedure),chr(13),'')) is distinct from '339ae8372edf7afa3115655da7a2255f' then raise exception 'Exact opportunity read prerequisites changed' using errcode='55000';end if;
end $$;
create function public.list_project_marketing_opportunity_candidates(p_organization_id uuid,p_project_id uuid,p_engagement_id uuid,p_kind text,p_query text default '',p_offset integer default 0,p_limit integer default 25)
returns jsonb language plpgsql security definer set search_path='' as $$declare e public.engagements%rowtype;total bigint;matching bigint;items jsonb;result jsonb;begin
 e:=private.campaign_lookup_scope(p_organization_id,p_project_id,p_engagement_id,p_query,p_offset,p_limit);
 if p_kind is null or p_kind not in ('canonical_targets','research_candidates','project_tasks') then raise exception 'Exact opportunity selector category required' using errcode='22023';end if;
 if p_kind='canonical_targets' then
 select count(*) into total from public.backlink_targets where organization_id=p_organization_id and brand_id=e.brand_id;
 select count(*) into matching from public.backlink_targets where organization_id=p_organization_id and brand_id=e.brand_id and (p_query='' or strpos(lower(site_name||' '||coalesce(site_url,'')),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.site_name,row.id),'[]') into items from(select id,organization_id,brand_id,site_name,site_url,industry_category,domain_authority,estimated_traffic,relevance_score,link_type,cost_type,outreach_status,created_by,created_at,updated_at from public.backlink_targets where organization_id=p_organization_id and brand_id=e.brand_id and (p_query='' or strpos(lower(site_name||' '||coalesce(site_url,'')),lower(p_query))>0) order by site_name,id limit p_limit offset p_offset) row;
 elsif p_kind='project_tasks' then
 select count(*) into total from public.tasks where organization_id=p_organization_id and project_id=p_project_id and department_id='marketing' and archived_at is null and status<>'cancelled';
 select count(*) into matching from public.tasks where organization_id=p_organization_id and project_id=p_project_id and department_id='marketing' and archived_at is null and status<>'cancelled' and (p_query='' or strpos(lower(title),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.title,row.id),'[]') into items from(select id,organization_id,project_id,title,department_id,row_version,assigned_to assignee_id,due_date,status from public.tasks where organization_id=p_organization_id and project_id=p_project_id and department_id='marketing' and archived_at is null and status<>'cancelled' and (p_query='' or strpos(lower(title),lower(p_query))>0) order by title,id limit p_limit offset p_offset) row;
 else
 select count(*) into total from public.project_marketing_opportunities where organization_id=p_organization_id and project_id=p_project_id and engagement_id=e.id and brand_id=e.brand_id;
 select count(*) into matching from public.project_marketing_opportunities c where organization_id=p_organization_id and project_id=p_project_id and engagement_id=e.id and brand_id=e.brand_id and (p_query='' or strpos(lower(c.normalized_site_url||' '||c.candidate_kind),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.created_at desc,row.id),'[]') into items from(select c.*,coalesce((select count(*) from public.project_marketing_opportunity_observations o where o.candidate_id=c.id and o.organization_id=c.organization_id),0) observation_count,coalesce((select count(*) from public.project_marketing_opportunity_task_links l where l.candidate_id=c.id and l.organization_id=c.organization_id),0) task_link_count from public.project_marketing_opportunities c where organization_id=p_organization_id and project_id=p_project_id and engagement_id=e.id and brand_id=e.brand_id and (p_query='' or strpos(lower(c.normalized_site_url||' '||c.candidate_kind),lower(p_query))>0) order by c.created_at desc,c.id limit p_limit offset p_offset) row;
 end if;
 result:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',e.id,'brand_id',e.brand_id,'kind',p_kind,'items',items,'total',total,'matching',matching,'offset',p_offset,'has_more',p_offset+jsonb_array_length(items)<matching,'provider_request_made',false,'provider_verified',false,'external_write_authorized',false);
 if octet_length(result::text)>131072 then raise exception 'Opportunity selection exceeds whole response bound' using errcode='22023';end if;return result;
end $$;
create function public.list_project_marketing_opportunity_history(p_organization_id uuid,p_project_id uuid,p_engagement_id uuid,p_candidate_id uuid,p_kind text,p_query text default '',p_offset integer default 0,p_limit integer default 25)
returns jsonb language plpgsql security definer set search_path='' as $$declare e public.engagements%rowtype;c public.project_marketing_opportunities%rowtype;total bigint;matching bigint;items jsonb;result jsonb;service_available boolean;archived boolean;begin
 e:=private.campaign_lookup_scope(p_organization_id,p_project_id,p_engagement_id,p_query,p_offset,p_limit);
 if p_kind is null or p_kind not in ('observations','task_links') then raise exception 'Exact research/commitment history category required' using errcode='22023';end if;
 select * into c from public.project_marketing_opportunities where id=p_candidate_id and organization_id=p_organization_id and project_id=p_project_id and engagement_id=e.id and brand_id=e.brand_id;
 if not found then raise exception 'Exact current-project opportunity required' using errcode='42501';end if;
 select archived_at is not null into archived from public.projects where id=p_project_id and organization_id=p_organization_id;
 service_available:=e.status in ('planning','active') and exists(select 1 from public.engagement_services es join public.service_catalog sc on sc.id=es.service_id and sc.organization_id=es.organization_id where es.id=c.marketing_service_id and es.organization_id=c.organization_id and es.engagement_id=e.id and es.status='active' and sc.is_active and sc.department_id='marketing');
 if p_kind='observations' then
 select count(*) into total from public.project_marketing_opportunity_observations where candidate_id=c.id and organization_id=c.organization_id;
 select count(*) into matching from public.project_marketing_opportunity_observations where candidate_id=c.id and organization_id=c.organization_id and (p_query='' or strpos(lower(source_url||' '||notes),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.created_at desc,row.id),'[]') into items from(select o.*,coalesce(encode(sha256(convert_to(to_jsonb(t)::text,'UTF8')),'hex')=o.target_checksum,false) current_target_matches,service_available current_service_available,archived project_archived,false provider_verified from public.project_marketing_opportunity_observations o left join public.backlink_targets t on t.id=o.target_id and t.organization_id=o.organization_id and t.brand_id=c.brand_id where o.candidate_id=c.id and o.organization_id=c.organization_id and (p_query='' or strpos(lower(o.source_url||' '||o.notes),lower(p_query))>0) order by o.created_at desc,o.id limit p_limit offset p_offset) row;
 else
 select count(*) into total from public.project_marketing_opportunity_task_links where candidate_id=c.id and organization_id=c.organization_id;
 select count(*) into matching from public.project_marketing_opportunity_task_links l where candidate_id=c.id and organization_id=c.organization_id and (p_query='' or strpos(lower(coalesce(l.reference_snapshot#>>'{task,title}','')),lower(p_query))>0);
 select coalesce(jsonb_agg(to_jsonb(row) order by row.created_at desc,row.id),'[]') into items from(select l.*,coalesce(encode(sha256(convert_to(to_jsonb(t)::text,'UTF8')),'hex')=o.target_checksum,false) current_target_matches,coalesce(task.archived_at is null and task.department_id='marketing' and task.status<>'cancelled' and task.row_version=(l.reference_snapshot#>>'{task,row_version}')::bigint,false) current_task_matches,case when task.id is null then null else jsonb_build_object('kind','project_task','id',task.id,'title',task.title,'assignee_id',task.assigned_to,'due_date',task.due_date,'status',task.status,'row_version',task.row_version,'archived',task.archived_at is not null) end current_task,service_available current_service_available,archived project_archived,false ready_to_submit,false provider_verified from public.project_marketing_opportunity_task_links l join public.project_marketing_opportunity_observations o on o.id=l.observation_id and o.organization_id=l.organization_id and o.candidate_id=c.id left join public.backlink_targets t on t.id=o.target_id and t.organization_id=o.organization_id and t.brand_id=c.brand_id left join public.tasks task on task.id=l.task_id and task.organization_id=l.organization_id and task.project_id=c.project_id where l.candidate_id=c.id and l.organization_id=c.organization_id and (p_query='' or strpos(lower(coalesce(l.reference_snapshot#>>'{task,title}','')),lower(p_query))>0) order by l.created_at desc,l.id limit p_limit offset p_offset) row;
 end if;
 result:=jsonb_build_object('organization_id',p_organization_id,'project_id',p_project_id,'engagement_id',e.id,'brand_id',e.brand_id,'candidate',to_jsonb(c),'kind',p_kind,'items',items,'total',total,'matching',matching,'offset',p_offset,'has_more',p_offset+jsonb_array_length(items)<matching,'current_service_available',service_available,'project_archived',archived,'provider_request_made',false,'provider_verified',false,'external_write_authorized',false);
 if octet_length(result::text)>131072 then raise exception 'Opportunity history exceeds whole bound; choose a smaller page' using errcode='22023';end if;return result;
end $$;
revoke all on function public.list_project_marketing_opportunity_candidates(uuid,uuid,uuid,text,text,integer,integer),public.list_project_marketing_opportunity_history(uuid,uuid,uuid,uuid,text,text,integer,integer) from public,anon,authenticated,service_role;
grant execute on function public.list_project_marketing_opportunity_candidates(uuid,uuid,uuid,text,text,integer,integer),public.list_project_marketing_opportunity_history(uuid,uuid,uuid,uuid,text,text,integer,integer) to authenticated;
commit;
